function storyItem(category,variant){
 if(category==='TWO-STEP REASONING'){const p=storyCore(variant%2?'subtractThenAdd':'addThenSubtract');return profMC('2.OA.A.1',category,p.story,p.final,[p.final-1,p.final+1,p.mid], '',{problem:p})}
 if(category==='PROBLEM SITUATION'){let a=rand(18,35),b=rand(5,14);const take=Math.random()<.5,ans=take?a-b:a+b;const text=take?`A box had ${a} markers. ${b} were taken out. Which operation matches the story?`:`A box had ${a} markers. ${b} more were added. Which operation matches the story?`;return profMC('2.OA.A.1',category,text,take?'SUBTRACT':'ADD',[take?'ADD':'SUBTRACT','MULTIPLY','NO OPERATION'],'',{a,b,ans})}
 if(category==='UNKNOWN POSITION'){if(variant===0){let whole=rand(20,60),part=rand(6,whole-7),miss=whole-part;return profMC('2.OA.A.1',category,`Some pencils were in a cup. ${part} more were added. Now there are ${whole}. How many were there at first?`,miss,[miss-1,miss+1,part], '',{equation:`? + ${part} = ${whole}`})}let whole=rand(22,65),left=rand(8,whole-8),removed=whole-left;return profMC('2.OA.A.1',category,`There were ${whole} blocks. Some were put away. ${left} blocks are left. How many were put away?`,removed,[removed-1,removed+1,left], '',{equation:`${whole} − ? = ${left}`})}
 if(category==='EQUATION REPRESENTATION'){const p=storyCore(variant%2?'subtractThenAdd':'addThenSubtract');const wrong1=p.kind==='addThenSubtract'?`${p.start} + ${p.a} + ${p.b}`:`${p.start} + ${p.a} + ${p.b}`;const wrong2=p.kind==='addThenSubtract'?`${p.start} − ${p.a} + ${p.b}`:`${p.start} − ${p.a} − ${p.b}`;return profMC('2.OA.A.1',category,`${p.story}\nWhich equation matches both steps?`,p.equation,[wrong1,wrong2,`${p.start} + ${p.b}`], '',{problem:p})}
 const p=storyCore('putTogether');return profMC('2.OA.A.1',category,`Which bar model matches this story?\n${p.story}`,`${p.start} + ${p.b} then − ${p.a}`,[`${p.start} − ${p.b} then + ${p.a}`,`${p.start} + ${p.a} only`,`${p.start} − ${p.a} only`],profBarModelHtml([p.start,p.b]),{problem:p})
}
function nbtItem(category,variant){
 if(category==='ADDITION NO REGROUPING'){let a=10*rand(2,6)+rand(1,4),b=10*rand(1,2)+rand(1,4);while(a+b>99||a%10+b%10>=10){a=10*rand(2,6)+rand(1,4);b=10*rand(1,2)+rand(1,4)}let n=a+b;return profMC('2.NBT.B.5',category,`${a} + ${b} = ?`,n,[n-10,n+10,n-1])}
 if(category==='ADDITION WITH REGROUPING'){let a=10*rand(2,6)+rand(5,9),b=10*rand(1,2)+rand(2,8);while(a+b>99||a%10+b%10<10){a=10*rand(2,6)+rand(5,9);b=10*rand(1,2)+rand(2,8)}let n=a+b;if(variant===0)return profMC('2.NBT.B.5',category,`${a} + ${b} = ?`,n,[n-10,n+10,n-1]);let ones=a%10+b%10;return profMC('2.NBT.B.5',category,`When solving ${a} + ${b}, the ones make ${ones}. What should happen next?`,`Compose 10 ones as 1 ten.`,[`Keep ${ones} ones with no new ten.`,`Remove 10 from the answer.`,`Change one ten into 10 ones.`])}
 if(category==='SUBTRACTION NO REGROUPING'){let tens=rand(4,8),ones=rand(4,9),a=10*tens+ones,b=10*rand(1,tens-2)+rand(1,ones-1),n=a-b;return profMC('2.NBT.B.5',category,`${a} − ${b} = ?`,n,[n-10,n+10,n+1])}
 if(category==='SUBTRACTION WITH REGROUPING'){let a=10*rand(4,9)+rand(0,4),b=10*rand(1,Math.floor(a/10)-1)+rand(5,9);while(b>=a||a%10>=b%10){a=10*rand(4,9)+rand(0,4);b=10*rand(1,Math.floor(a/10)-1)+rand(5,9)}let n=a-b;if(variant===0)return profMC('2.NBT.B.5',category,`${a} − ${b} = ?`,n,[n-10,n+10,n-1]);return profMC('2.NBT.B.5',category,`Why can you decompose one ten when solving ${a} − ${b}?`,`One ten can be renamed as 10 ones.`,[`One ten is worth 1 one.`,`Subtracting always adds a ten.`,`You may erase the ones digit.`])}
 let a=10*rand(2,6)+rand(5,9),b=10*rand(1,2)+rand(2,8);while(a+b>99||a%10+b%10<10)b=10*rand(1,2)+rand(2,8);let n=a+b;if(variant===0)return profMC('2.NBT.B.5',category,`Which place-value strategy correctly solves ${a} + ${b}?`,`${a-a%10} + ${b-b%10} + ${a%10+b%10} = ${n}`,[`${a} + ${b%10} = ${n}`,`${a-a%10} + ${b-b%10} = ${n}`,`${a%10} + ${b%10} = ${n}`]);return profMC('2.NBT.B.5',category,`Which statement explains why ${a} + ${b} may make a new ten?`,`The ones can compose a group of 10.`,[`The tens disappear.`,`The ones become hundreds.`,`Addition always changes both tens digits.`])
}
const GRAPH_LABEL_SETS=[['Apples','Bananas','Pears','Grapes'],['Cats','Dogs','Fish','Birds'],['Red','Blue','Green','Yellow'],['Soccer','Tag','Swings','Chalk'],['Rain','Sun','Wind','Clouds']];
function graphData(){const labels=shuffle(pick(GRAPH_LABEL_SETS)).slice(0,rand(3,4)),values=[];while(values.length<labels.length){const v=rand(2,9);if(!values.includes(v))values.push(v)}return {labels,values}}
function graphItem(category,variant){
 const d=graphData();
 if(category==='READ PICTURE GRAPH'){const i=rand(0,d.labels.length-1);return profMC('2.MD.10',category,`How many chose ${d.labels[i]}?`,d.values[i],[d.values[i]-1,d.values[i]+1,pick(d.values.filter((_,j)=>j!==i))],profGraphHtml(d,'picture'),{data:d,graphType:'picture'})}
 if(category==='READ BAR GRAPH'){const i=rand(0,d.labels.length-1);return profMC('2.MD.10',category,`How many are shown for ${d.labels[i]}?`,d.values[i],[d.values[i]-1,d.values[i]+1,pick(d.values.filter((_,j)=>j!==i))],profGraphHtml(d,'bar'),{data:d,graphType:'bar'})}
 if(category==='REPRESENT DATA'){const i=rand(0,d.labels.length-1),v=d.values[i];if(variant===0)return profMC('2.MD.10',category,`The data table says ${d.labels[i]} = ${v}. How tall should that bar be?`,v,[v-1,v+1,pick(d.values.filter(x=>x!==v))],profGraphHtml(d,'bar',i),{data:d,hidden:i});return profMC('2.MD.10',category,`Which statement correctly represents this data?`,`${d.labels[i]} = ${v}`,[`${d.labels[i]} = ${v+1}`,`${d.labels[(i+1)%d.labels.length]} = ${v}`,`${d.labels[i]} = ${Math.max(0,v-1)}`],profGraphHtml(d,'picture'),{data:d})}
 if(category==='PUT TOGETHER / TAKE APART'){let i=0,j=1;if(variant===0){const ans=d.values[i]+d.values[j];return profMC('2.MD.10',category,`How many chose ${d.labels[i]} and ${d.labels[j]} altogether?`,ans,[ans-1,ans+1,Math.abs(d.values[i]-d.values[j])],profGraphHtml(d,'bar'),{data:d,indices:[i,j]})}const total=d.values[i]+d.values[j],known=d.values[i],ans=d.values[j];return profMC('2.MD.10',category,`${total} students chose ${d.labels[i]} or ${d.labels[j]} altogether. ${known} chose ${d.labels[i]}. How many chose ${d.labels[j]}?`,ans,[ans-1,ans+1,total],profGraphHtml(d,'picture'),{data:d,indices:[i,j]})}
 let hi=0,lo=1;if(d.values[lo]>d.values[hi]){hi=1;lo=0}const diff=Math.abs(d.values[hi]-d.values[lo]);if(variant===0)return profMC('2.MD.10',category,`How many more chose ${d.labels[hi]} than ${d.labels[lo]}?`,diff,[diff+1,Math.max(0,diff-1),d.values[hi]],profGraphHtml(d,'bar'),{data:d,indices:[hi,lo]});return profMC('2.MD.10',category,`How many fewer chose ${d.labels[lo]} than ${d.labels[hi]}?`,diff,[diff+1,Math.max(0,diff-1),d.values[lo]],profGraphHtml(d,'picture'),{data:d,indices:[hi,lo]})
}
function profGenerator(standard,category,variant){if(standard==='2.OA.B.2')return addItem(category,variant);if(standard==='2.OA.C.3')return oddEvenItem(category,variant);if(standard==='2.OA.A.1')return storyItem(category,variant);if(standard==='2.NBT.B.5')return nbtItem(category,variant);if(standard==='2.MD.10')return graphItem(category,variant);throw new Error('Unknown proficiency standard')}
function buildProficiencyItems(standard){const def=PROF_STANDARDS[standard],cats=[];Object.entries(def.counts).forEach(([cat,n])=>{for(let i=0;i<n;i++)cats.push({cat,variant:i})});const first=shuffle(cats.filter(x=>x.variant===0)),rest=shuffle(cats.filter(x=>x.variant>0));return [...first,...rest].map(x=>profGenerator(standard,x.cat,x.variant))}
function profEvidence(standard,items,responses){const def=PROF_STANDARDS[standard],out={};def.components.forEach(c=>out[c]={answered:0,correct:0,total:def.counts[c]});items.forEach((it,i)=>{const r=responses[i];if(!r)return;out[it.category].answered++;if(r.correct)out[it.category].correct++});return out}
function determineProficiencyOutcome(standard,items,responses,timedOut=false){
 const def=PROF_STANDARDS[standard],evidence=profEvidence(standard,items,responses),answered=responses.filter(Boolean).length,correct=responses.filter(r=>r?.correct).length;
 const decisiveFail=def.components.find(c=>evidence[c].answered>=def.counts[c]&&def.counts[c]>=2&&evidence[c].correct===0);if(decisiveFail)return {result:'NOT YET',answered,correct,evidence,reason:`${decisiveFail} was not yet demonstrated.`};
 const allSampled=def.components.every(c=>evidence[c].answered>=1),allShown=def.components.every(c=>evidence[c].correct>=1),earlyThreshold=Math.max(def.components.length,def.requiredCorrect-1);
 if(answered>=def.minEarly&&allSampled&&allShown&&correct>=earlyThreshold)return {result:'LEVEL 3 DEMONSTRATED',answered,correct,evidence,reason:'Required Level 3 components were demonstrated.'};
 if(answered>=def.total){if(correct>=def.requiredCorrect&&allShown)return {result:'LEVEL 3 DEMONSTRATED',answered,correct,evidence,reason:'Required Level 3 components were demonstrated.'};return {result:'NOT YET',answered,correct,evidence,reason:'At least one required Level 3 component was not demonstrated strongly enough.'}}
 if(timedOut)return {result:'NOT ENOUGH EVIDENCE',answered,correct,evidence,reason:`The ${Math.round(def.timer/60)}-minute work window ended before enough evidence was collected.`};return {result:'CONTINUE',answered,correct,evidence,reason:''}
}
function profWeakComponents(attempt){const entries=Object.entries(attempt.evidence||{});const zero=entries.filter(([k,v])=>v.correct===0).map(([k])=>k);if(zero.length)return zero;return entries.filter(([k,v])=>v.correct<v.answered||v.answered===0).map(([k])=>k)}
function suggestedWinFromAttempt(attempt){const weak=profWeakComponents(attempt),c=weak[0]||'';
 if(attempt.standard==='2.OA.B.2'){if(c==='MISSING PART / RELATED FACT')return {skill:'MISSING PART',level:'BRIDGE',focus:'Missing Part / Related Facts'};if(c==='EFFICIENT STRATEGY')return {skill:'MAKE 10',level:'BRIDGE',focus:'Make Ten / Efficient Strategy'};if(c==='SUBTRACTION')return {skill:'SUBTRACTION WITHIN 20',level:'BRIDGE',focus:'Subtraction Within 20'};return {skill:'ADDITION WITHIN 20',level:'BRIDGE',focus:c||'Add & Subtract Within 20'}}
 if(attempt.standard==='2.OA.C.3'){const foundation=weak.some(x=>x==='IDENTIFY ODD / EVEN'||x==='OBJECT GROUP');return {skill:'ODD / EVEN',level:foundation?'FOUNDATION':'BRIDGE',focus:c||'Odd / Even'}}
 if(attempt.standard==='2.OA.A.1'){if(c==='UNKNOWN POSITION')return {skill:'MISSING PART',level:'BRIDGE',focus:'Unknown Position / Missing Part'};return {skill:'WORD PROBLEMS',level:c==='PROBLEM SITUATION'?'FOUNDATION':'BRIDGE',focus:c||'Story Problem Reasoning'}}
 if(attempt.standard==='2.NBT.B.5'){if(c==='PLACE-VALUE STRATEGY')return {skill:'PLACE VALUE',level:'BRIDGE',focus:'Place-Value Strategy'};if(c.includes('SUBTRACTION'))return {skill:'SUBTRACTION WITHIN 100',level:c.includes('WITH REGROUPING')?'BRIDGE':'GRADE 2 TARGET',focus:c};if(c.includes('ADDITION'))return {skill:'ADDITION WITHIN 100',level:c.includes('WITH REGROUPING')?'BRIDGE':'GRADE 2 TARGET',focus:c};return {skill:'TENS + ONES',level:'BRIDGE',focus:c||'Tens & Ones'}}
 return {skill:'COMPARE NUMBERS',level:'BRIDGE',focus:c||'Read / Compare Graph Data'}
}
function initProficiencySetup(){profState.student=profState.student||state.students[0]||roster()[0]||'';const options=[...roster().map(n=>({value:n,label:n})),{value:PROF_SPECIAL.DEMO,label:'MR. FRANK — DEMO / TEACH'},{value:PROF_SPECIAL.CUSTOM,label:'CUSTOM — NO STUDENT'}];if(!options.some(o=>o.value===profState.student))profState.student=roster()[0]||PROF_SPECIAL.CUSTOM;$('#profStudent').innerHTML=options.map(o=>`<option value="${esc(o.value)}" ${o.value===profState.student?'selected':''}>${esc(o.label)}</option>`).join('');$('#profStudent').value=profState.student;renderProfCurrentStatus()}
function renderProfCurrentStatus(){const student=$('#profStudent')?.value||profState.student;if(!student)return;if(!isRealRosterStudent(student)){const note=student===PROF_SPECIAL.DEMO?'Demo mode · full Q1 checks work normally · no student evidence is saved.':'No-student mode · preview/test freely · no student evidence is saved.';$('#profCurrentStatus').innerHTML=`<div><b>${esc(profIdentityLabel(student))}</b></div><div class="small">${esc(note)}</div>`;return}const shown=Object.entries(PROF_STANDARDS).map(([code,s])=>{const st=currentProficiency(student,code);return `<div>${st?'✓ LEVEL 3 SHOWN':'○ READY TO TRY'} · ${esc(s.studentName)}</div>`}).join('');$('#profCurrentStatus').innerHTML=shown}
function renderProfStudentMenu(){const identity=profIdentityLabel(profState.student),first=isSpecialProfIdentity(profState.student)?identity:profState.student.split(/\s+/)[0];$('#profStudentArea').innerHTML=`<div><h1>SHOW WHAT YOU KNOW</h1><div class="small" style="font-weight:900;letter-spacing:1px">Q1 MATH</div><div class="lead">${esc(first.toUpperCase())}</div><div class="prof-standard-list">${Object.entries(PROF_STANDARDS).map(([code,s])=>{const shown=isRealRosterStudent(profState.student)&&currentProficiency(profState.student,code);return `<button class="prof-standard-btn" data-standard="${code}"><strong>${esc(s.studentName)}</strong><span>${shown?'✓ LEVEL 3 SHOWN':'READY TO TRY'}</span></button>`}).join('')}</div><button id="profStudentBack" class="secondary teacher-return" style="margin-top:24px">TEACHER BACK</button></div>`;$$('.prof-standard-btn').forEach(b=>b.onclick=()=>prepareProficiencyAttempt(b.dataset.standard));$('#profStudentBack').onclick=()=>{initProficiencySetup();setScreen('proficiencySetup')}}
function profTimeText(seconds){return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}
function prepareProficiencyAttempt(standard){stopProfTimer();const def=PROF_STANDARDS[standard];profState.standard=standard;profState.items=buildProficiencyItems(standard);profState.responses=Array(def.total).fill(null);profState.index=0;profState.selected=null;profState.startTime=null;profState.endTime=null;profState.timerRemaining=def.timer;profState.result=null;profState.attempt=null;$('#profStudentArea').innerHTML=`<div><h1>SHOW WHAT YOU KNOW</h1><div class="lead">${esc(def.studentName)}</div><div class="prof-timer" style="margin:22px 0">${profTimeText(def.timer)}</div><button id="profStartCheck" class="primary" style="font-size:24px;padding:16px 34px">START</button><button id="profChooseOther" class="secondary teacher-return" style="margin-left:8px">BACK</button></div>`;$('#profStartCheck').onclick=startProficiencyAttempt;$('#profChooseOther').onclick=renderProfStudentMenu}
function startProficiencyAttempt(){profState.startTime=new Date().toISOString();startProfTimer();renderProfQuestion()}
function stopProfTimer(){if(profState.timerId){clearInterval(profState.timerId);profState.timerId=null}}
function startProfTimer(){stopProfTimer();updateProfTimerDisplay();profState.timerId=setInterval(()=>{profState.timerRemaining--;updateProfTimerDisplay();if(profState.timerRemaining<=0){profState.timerRemaining=0;stopProfTimer();finishProficiency(true)}},1000)}
function updateProfTimerDisplay(){const el=$('.prof-timer');if(el)el.textContent=profTimeText(Math.max(0,profState.timerRemaining))}
