const MORNING_MATH_FAMILIES=['TENS + ONES','REPRESENT A NUMBER','COMPOSE / DECOMPOSE','COMPARE NUMBERS','ADDITION WITHIN 20','SUBTRACTION WITHIN 20','ADD / SUBTRACT TENS','EARLY WITHIN 100','MISSING PART','MAKE 10','ODD / EVEN','SKIP COUNTING','HUNDRED CHART','NUMBER PATTERN','WORD PROBLEM','SHOW ANOTHER WAY'];
const MORNING_ELA_FAMILIES=['CAPITALIZATION','ENDING PUNCTUATION','FIX A SENTENCE','COMPLETE A SENTENCE','IMPROVE A SENTENCE','CHOOSE THE WORD','PHONICS / SPELLING','CHANGE ONE SOUND','VOCABULARY CONTEXT','TINY COMPREHENSION'];
const MORNING_MOVES=['Do 5 jumping jacks.','Do 5 slow squats.','March in place for 10 seconds.','Do 5 cross-body taps on each side.','Reach high, then touch your toes 5 times.','Do 10 quiet toe taps.','Do 5 calf raises.','Balance on one foot for 5 seconds, then switch.','Roll your shoulders 10 times.','Pretend to jump rope for 10 seconds.','Shake out your hands and arms for 10 seconds.','Take 3 big breaths while raising and lowering your arms.'];
function morningPrefs(){const d={message:'',reminder:'',minutes:18,mathFamilies:[...MORNING_MATH_FAMILIES],elaFamilies:[...MORNING_ELA_FAMILIES]};const m=store.get('winMorning',d)||d;return{...d,...m,mathFamilies:Array.isArray(m.mathFamilies)&&m.mathFamilies.length?m.mathFamilies:d.mathFamilies,elaFamilies:Array.isArray(m.elaFamilies)&&m.elaFamilies.length?m.elaFamilies:d.elaFamilies}}
function mathMorningProblem(f){let a,b,n,tens,ones;switch(f){
case 'TENS + ONES':n=rand(12,89);return `${n} = ___ tens + ___ ones`;
case 'REPRESENT A NUMBER':n=rand(11,79);return `Show ${n} with a quick drawing of tens and ones.`;
case 'COMPOSE / DECOMPOSE':n=rand(8,20);a=rand(2,n-2);return `${n} = ${a} + ___\nWrite one more way to break apart ${n}.`;
case 'COMPARE NUMBERS':a=rand(21,89);do{b=rand(21,89)}while(a===b);return `Which is greater?\n${a} or ${b}\nWrite >, <, or =.`;
case 'ADDITION WITHIN 20':a=rand(4,12);b=rand(3,Math.min(9,20-a));return `${a} + ${b} = ___\nShow a strategy.`;
case 'SUBTRACTION WITHIN 20':a=rand(9,20);b=rand(2,a-3);return `${a} − ${b} = ___\nShow how you know.`;
case 'ADD / SUBTRACT TENS':a=rand(2,7)*10+rand(1,8);b=pick([10,20,30].filter(x=>a+x<100));return Math.random()<.5?`${a} + ${b} = ___`:`${a+b} − ${b} = ___`;
case 'EARLY WITHIN 100':tens=rand(2,6)*10;ones=rand(2,9);b=rand(2,8);return Math.random()<.5?`${tens+ones} + ${b} = ___\nThink tens and ones.`:`${tens+ones+b} − ${b} = ___\nThink tens and ones.`;
case 'MISSING PART':a=rand(5,15);b=rand(2,Math.min(9,20-a));return `${a} + ___ = ${a+b}`;
case 'MAKE 10':a=rand(1,9);return `${a} + ___ = 10`;
case 'ODD / EVEN':n=rand(12,49);return `Is ${n} odd or even?\nHow do you know?`;
case 'SKIP COUNTING':n=pick([2,5,10]);a=n*rand(1,4);return `Count by ${n}s:\n${a}, ___, ___, ___, ___`;
case 'HUNDRED CHART':n=rand(22,78);return `On a hundred chart, what number is:\n10 more than ${n}? ___\n1 less than ${n}? ___`;
case 'NUMBER PATTERN':a=rand(11,39);b=pick([2,5,10]);return `${a}, ${a+b}, ${a+2*b}, ___, ___\nWhat is the rule?`;
case 'WORD PROBLEM':a=rand(6,14);b=rand(2,7);return Math.random()<.5?`Lani has ${a} stickers. She gets ${b} more.\nHow many stickers now? ___`:`There are ${a+b} shells. ${b} are moved away.\nHow many are left? ___`;
case 'SHOW ANOTHER WAY':n=rand(10,30);return `Show ${n} in TWO different ways.\nUse numbers, a drawing, or tens and ones.`;
default:return 'Show 18 in two different ways.'}}
function elaMorningProblem(f){const names=['The dog','My friend','A small bird','The puppy','Our class'];switch(f){
case 'CAPITALIZATION':return `Fix the capital letter:\n${pick(['my brother likes soccer.','we went to the park.','maria has a blue bag.','on monday we read together.'])}`;
case 'ENDING PUNCTUATION':return `Add the best ending mark:\n${pick(['Where is my pencil___','I like to draw___','Watch out___','Can you help me___'])}`;
case 'FIX A SENTENCE':return `Fix the sentence:\n${pick(['the cat ran home','my friend has a red bike','we played outside today','the frog jumped in the pond'])}`;
case 'COMPLETE A SENTENCE':return `Finish the sentence with a complete thought:\n${pick(['After school, I __________.','In the morning, we __________.','My favorite game is __________ because __________.','When it rains, I __________.'])}`;
case 'IMPROVE A SENTENCE':return `Add TWO details:\n${pick(['The bird flew.','The dog ran.','The girl laughed.','The car stopped.'])}`;
case 'CHOOSE THE WORD':return `Choose the word that makes sense:\n${pick(['The puppy (run / runs) home.','The birds (fly / flies) over the tree.','My friend (play / plays) soccer.','We (walk / walks) to class.'])}`;
case 'PHONICS / SPELLING':{const sets=[['ship','shop','fish'],['chat','chin','much'],['thin','bath','moth'],['cake','game','late'],['seed','feet','keep']];const s=pick(sets);return `Read the words. What pattern do you notice?\n${s.join('   ')}`}
case 'CHANGE ONE SOUND':{const chains=[['map','mat'],['sit','sat'],['fin','fit'],['hop','hot'],['chip','chin']];const c=pick(chains);return `Change ONE sound to make a new word:\n${c[0]} → ${c[1]}`}
case 'VOCABULARY CONTEXT':{const qs=[['The tiny ant carried a crumb.','tiny','small','loud'],['Mia was glad when she found her book.','glad','happy','angry'],['The wet floor was slippery.','slippery','easy to slide on','very dry']];const q=pick(qs);return `${q[0]}\n${q[1]} means: ${q[2]} or ${q[3]}?`}
case 'TINY COMPREHENSION':{const qs=[['Kai packed a hat because the sun was bright. Then he walked to the park.','Why did Kai pack a hat?'],['The frog jumped from the rock into the pond. It swam under a leaf.','Where did the frog go after the rock?'],['Nia fed the dog before she ate breakfast. The dog wagged its tail.','What did Nia do first?']];const q=pick(qs);return `${q[0]}\n${q[1]}`}
default:return `${pick(names)} ran home.\nAdd one detail.`}}
function newMorningData(){const p=morningPrefs(),mf=shuffle(p.mathFamilies).slice(0,Math.min(3,p.mathFamilies.length)),ef=shuffle(p.elaFamilies).slice(0,Math.min(2,p.elaFamilies.length));while(mf.length<3)mf.push(pick(p.mathFamilies));while(ef.length<2)ef.push(pick(p.elaFamilies));return{math:mf.map(f=>({family:f,text:mathMorningProblem(f)})),movement:pick(MORNING_MOVES),ela:ef.map(f=>({family:f,text:elaMorningProblem(f)}))}}
function morningData(){let d=store.get('winMorningCurrent',null);if(!d||!Array.isArray(d.math)||d.math.length!==3||!Array.isArray(d.ela)||d.ela.length!==2){d=newMorningData();store.set('winMorningCurrent',d)}return d}
function renderMorningFamilies(){const p=morningPrefs();$('#morningMathFamilies').innerHTML=MORNING_MATH_FAMILIES.map(f=>`<label class="family-option"><input type="checkbox" data-mf="${esc(f)}" ${p.mathFamilies.includes(f)?'checked':''}> ${esc(f)}</label>`).join('');$('#morningElaFamilies').innerHTML=MORNING_ELA_FAMILIES.map(f=>`<label class="family-option"><input type="checkbox" data-ef="${esc(f)}" ${p.elaFamilies.includes(f)?'checked':''}> ${esc(f)}</label>`).join('')}
function renderMorning(){const d=morningData();$('#morningMath').innerHTML=d.math.map((x,i)=>`<div class="morning-problem"><div class="problem-text"><b>${i+1}.</b> ${esc(x.text)}</div><button class="reroll no-print morning-math-reroll" data-i="${i}" title="New math problem">↻</button></div>`).join('');$('#morningMovement').textContent=d.movement;$('#morningEla').innerHTML=d.ela.map((x,i)=>`<div class="morning-problem"><div class="problem-text"><b>${i+1}.</b> ${esc(x.text)}</div><button class="reroll no-print morning-ela-reroll" data-i="${i}" title="New ELA problem">↻</button></div>`).join('');$$('.morning-math-reroll').forEach(b=>b.onclick=()=>rerollMorningMath(+b.dataset.i));$$('.morning-ela-reroll').forEach(b=>b.onclick=()=>rerollMorningEla(+b.dataset.i))}
function rerollMorningMath(i){const d=morningData(),p=morningPrefs(),used=d.math.map(x=>x.family),choices=p.mathFamilies.filter(f=>f!==d.math[i].family&&!used.includes(f)),f=pick(choices.length?choices:p.mathFamilies);d.math[i]={family:f,text:mathMorningProblem(f)};store.set('winMorningCurrent',d);renderMorning()}
function rerollMorningEla(i){const d=morningData(),p=morningPrefs(),used=d.ela.map(x=>x.family),choices=p.elaFamilies.filter(f=>f!==d.ela[i].family&&!used.includes(f)),f=pick(choices.length?choices:p.elaFamilies);d.ela[i]={family:f,text:elaMorningProblem(f)};store.set('winMorningCurrent',d);renderMorning()}
function loadMorning(){const m=morningPrefs();$('#morningMessage').value=m.message||'';$('#morningReminder').value=m.reminder||'';$('#morningMinutes').value=m.minutes||18;const md=$('#morningMessageDisplay');md.textContent=m.message||'';md.classList.toggle('hidden',!m.message);$('#morningReminderDisplay').innerHTML=m.reminder?`<div class="reset-note"><b>REMEMBER:</b> ${esc(m.reminder)}</div>`:'';renderMorningFamilies();renderMorning();state.timerRemaining=(m.minutes||18)*60;renderTimer()}
$('#newMorningBtn').onclick=()=>{store.set('winMorningCurrent',newMorningData());renderMorning()};$('#rerollMovement').onclick=()=>{const d=morningData(),choices=MORNING_MOVES.filter(x=>x!==d.movement);d.movement=pick(choices);store.set('winMorningCurrent',d);renderMorning()};
$('#morningEditBtn').onclick=()=>{$('#morningEdit').classList.remove('hidden');renderMorningFamilies()};$('#cancelMorning').onclick=()=>$('#morningEdit').classList.add('hidden');$('#saveMorning').onclick=()=>{const mathFamilies=$$('[data-mf]:checked').map(x=>x.dataset.mf),elaFamilies=$$('[data-ef]:checked').map(x=>x.dataset.ef);if(!mathFamilies.length||!elaFamilies.length)return alert('Keep at least one Math family and one ELA family enabled.');const m={message:$('#morningMessage').value.trim(),reminder:$('#morningReminder').value.trim(),minutes:Math.max(1,Math.min(60,+$('#morningMinutes').value||18)),mathFamilies,elaFamilies};store.set('winMorning',m);store.set('winMorningCurrent',newMorningData());$('#morningEdit').classList.add('hidden');loadMorning()};
function renderTimer(){const s=Math.max(0,state.timerRemaining);$('#timerDisplay').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
$('#timerStart').onclick=()=>{if(state.timer){clearInterval(state.timer);state.timer=null;$('#timerStart').textContent='START TIMER';return}if(state.timerRemaining<=0){state.timerRemaining=morningPrefs().minutes*60;renderTimer()}$('#timerStart').textContent='PAUSE';state.timer=setInterval(()=>{state.timerRemaining--;renderTimer();if(state.timerRemaining<=0){clearInterval(state.timer);state.timer=null;$('#timerStart').textContent='START TIMER'}},1000)};$('#timerReset').onclick=()=>{if(state.timer){clearInterval(state.timer);state.timer=null}$('#timerStart').textContent='START TIMER';state.timerRemaining=morningPrefs().minutes*60;renderTimer()};
function init(){renderStudents();renderSkills();bindSegments();updateStartHint();updateLevelHint();renderGroupSelect();updateLastTime();loadMorning()}init();
