$('#startBtn').onclick=()=>{state.skill=$('#skillSelect').value;if(state.students.length<2)return alert('Pick at least 2 students.');state.session=generateSession();renderSession()};
$('#newVariationBtn').onclick=()=>{state.session=generateSession();renderSession()};$('#backWinBtn').onclick=()=>setScreen('win');
$$('.result-buttons button').forEach(b=>b.onclick=()=>{state.result=b.dataset.result;$$('.result-buttons button').forEach(x=>x.classList.toggle('sel',x===b))});
$('#saveResultBtn').onclick=()=>{if(!state.result)return alert('Choose GOT IT, ALMOST, or NOT YET.');const d=state.session.decisions;const next=state.result==='GOT IT'?d.got:state.result==='ALMOST'?d.almost:d.notyet;const rec={date:new Date().toISOString(),students:[...state.students],subject:state.subject,skill:state.skill,level:state.level,result:state.result,note:$('#sessionNote').value.trim(),next};const h=history();h.unshift(rec);store.set('winHistory',h.slice(0,200));$('#saveFeedback').textContent=`Saved. Suggested next: ${next}`;updateLastTime()};
function renderHistory(){
 const f=$('#historyFilter').value;
 const wins=history().map(x=>({...x,type:'WIN'}));
 const profs=proficiencyAttempts();
 const curriculum=curriculumAssessments();
 let all=[...wins,...profs,...curriculum].sort((a,b)=>new Date(b.date)-new Date(a.date));
 if(f==='PROFICIENCY')all=all.filter(x=>x.type==='PROFICIENCY');
 else if(f==='CURRICULUM')all=all.filter(x=>x.type==='CURRICULUM_ASSESSMENT');
 else if(f!=='ALL')all=all.filter(x=>x.type==='WIN'&&x.result===f);
 $('#historyList').innerHTML=all.length?all.map(x=>{
  if(x.type==='PROFICIENCY')return `<div class="history-item history-prof"><div><span class="pill prof">PROFICIENCY</span><span class="pill">${esc(x.standard)}</span></div><strong>${esc(x.standardName)}</strong> · ${fmtDate(x.date)}<br><span class="small">${esc(x.student)} · ${esc(x.result)} · ${x.answered} answered / ${x.correct} correct</span>${x.recordedLevel3?'<div class="small"><b>✓ LEVEL 3 SHOWN</b></div>':''}${x.result==='NOT YET'?`<div class="small"><b>WIN focus:</b> ${esc(x.suggestedWin?.focus||'Review prerequisite')}</div>`:''}<div class="actions" style="margin-top:8px"><button class="secondary prof-detail" data-id="${esc(x.id)}">VIEW DETAILS</button></div></div>`;
  if(x.type==='CURRICULUM_ASSESSMENT')return `<div class="history-item history-curriculum"><div><span class="pill curriculum">CURRICULUM ASSESSMENT</span></div><strong>${esc(x.assessmentName)}</strong> · ${fmtDate(x.date)}<br><span class="small">${esc(x.studentName)}</span><div class="small" style="margin-top:6px">Vocabulary: ${x.vocabularyCorrect} / ${x.vocabularyTotal}<br>Comprehension: ${x.comprehensionCorrect} / ${x.comprehensionTotal}<br><b>Total: ${x.totalCorrect} / ${x.totalItems} · ${x.percent}%</b></div><div class="actions" style="margin-top:8px"><button class="secondary curriculum-detail" data-id="${esc(x.id)}">VIEW RESULTS</button></div></div>`;
  return `<div class="history-item"><div><span class="pill ${x.result==='GOT IT'?'got':x.result==='ALMOST'?'almost':'notyet'}">${esc(x.result)}</span><span class="pill">${esc(x.subject)}</span><span class="pill">${esc(x.level)}</span></div><strong>${esc(x.skill)}</strong> · ${fmtDate(x.date)}<br><span class="small">${esc(x.students.join(', '))}</span>${x.note?`<div style="margin-top:6px">${esc(x.note)}</div>`:''}<div class="small" style="margin-top:5px"><b>Next:</b> ${esc(x.next)}</div></div>`;
 }).join(''):'<div class="empty">No saved WIN sessions, proficiency attempts, or curriculum assessments yet.</div>';
 $$('.prof-detail').forEach(b=>b.onclick=()=>openProficiencyDetail(b.dataset.id));
 $$('.curriculum-detail').forEach(b=>b.onclick=()=>openCurriculumAssessmentDetail(b.dataset.id));
}
function openCurriculumAssessmentDetail(id){
 const x=curriculumAssessments().find(a=>a.id===id);if(!x)return;
 const when=new Date(x.date).toLocaleString();
 $('#historyList').innerHTML=`<div class="card"><div class="actions" style="margin-top:0"><button id="backCurriculumHistory" class="secondary">← BACK TO HISTORY</button></div><div class="eyebrow">CURRICULUM ASSESSMENT</div><h2 style="margin-bottom:4px">${esc(x.studentName)}</h2><h3 style="margin-top:0">${esc(x.assessmentName)}</h3><div class="small">${esc(when)}</div><div class="assessment-score-grid"><div class="assessment-score-box"><b>VOCABULARY</b><div class="precheck-score" style="font-size:28px">${x.vocabularyCorrect} / ${x.vocabularyTotal}</div></div><div class="assessment-score-box"><b>COMPREHENSION</b><div class="precheck-score" style="font-size:28px">${x.comprehensionCorrect} / ${x.comprehensionTotal}</div></div><div class="assessment-score-box"><b>TOTAL</b><div class="precheck-score" style="font-size:28px">${x.totalCorrect} / ${x.totalItems}</div><div><b>${x.percent}%</b></div></div></div><h3>RESPONSE REVIEW</h3><div>${x.responses.map((r,i)=>`<div class="assessment-response"><b>Question ${r.questionNumber||i+1}</b>${r.prompt?`<div style="margin-top:4px">${esc(r.prompt)}</div>`:''}<div class="small" style="margin-top:6px">Student answer: <b>${esc(r.studentAnswer??'No answer')}</b><br>Correct answer: <b>${esc(r.expectedAnswer??'')}</b></div><div style="margin-top:5px;font-weight:900">${r.correct?'✓':'✗'}</div></div>`).join('')}</div></div>`;
 $('#backCurriculumHistory').onclick=renderHistory;
}
$('#historyFilter').onchange=renderHistory;$('#clearHistory').onclick=()=>{if(confirm('Clear local WIN, proficiency, and curriculum assessment history?')){store.set('winHistory',[]);store.set('winProficiencyAttempts',[]);store.set('winProficiencyStatus',{});store.set('winCurriculumAssessments',[]);renderHistory();updateLastTime()}};
function renderSettings(){const r=roster();$('#rosterText').value=r.join('\n');const gs=groups();$('#savedGroupsList').innerHTML=gs.length?gs.map((g,i)=>`<div class="group-row"><div><strong>${esc(g.name)}</strong><div class="small">${esc(g.students.join(', '))}<br>${esc(g.subject)} · ${esc(g.skill)} · ${esc(g.level)}</div></div><button class="danger delete-group" data-i="${i}">DELETE</button></div>`).join(''):'<div class="empty">No saved groups yet.</div>';$$('.delete-group').forEach(b=>b.onclick=()=>{const arr=groups();arr.splice(+b.dataset.i,1);store.set('winGroups',arr);renderSettings();renderGroupSelect()})}
$('#saveRoster').onclick=()=>{const arr=$('#rosterText').value.split(/\n/).map(x=>x.trim()).filter(Boolean);if(!arr.length)return alert('Roster cannot be empty.');store.set('winRoster',[...new Set(arr)]);state.students=state.students.filter(n=>arr.includes(n));renderStudents();renderGroupSelect();alert('Roster saved locally.')};$('#resetRoster').onclick=()=>{store.set('winRoster',DEFAULT_ROSTER);renderSettings();renderStudents();renderGroupSelect()};
