// TEACH — isolated whole-class task generator. WIN and Morning generators remain untouched.
const TEACH_SKILLS={
MATH:['NUMBER SENSE','TENS + ONES','COMPOSE / DECOMPOSE','COMPARE NUMBERS','MAKE 10','ADDITION / SUBTRACTION WITHIN 20','ADDITION / SUBTRACTION WITHIN 100','MISSING PART','ODD / EVEN','SKIP COUNTING','HUNDRED CHART','NUMBER LINE','WORD PROBLEMS','BAR MODELS: PARTS & WHOLE','ERROR ANALYSIS','STRATEGY COMPARISON','SHOW ANOTHER WAY / CONVINCE ME'],
ELA:['PHONICS','WORD READING','SPELLING PATTERNS','FLUENCY','PHRASE READING','SENTENCE CONVENTIONS','SENTENCE EXPANSION','SENTENCE COMBINING','VOCABULARY / WORD CHOICE']};
let teachState={subject:'MATH',skill:'TENS + ONES',mode:'FIGURE IT OUT',sequence:null,index:0,lastKey:'',timerSeconds:120,timerBase:120,timerId:null};
function teachGoal(skill){const g={
'NUMBER SENSE':'Students notice quantity relationships and justify what they see.','TENS + ONES':'Students flexibly compose and decompose two-digit numbers and explain equivalence.','COMPOSE / DECOMPOSE':'Students represent one quantity in multiple equivalent ways.','COMPARE NUMBERS':'Students compare quantities using place-value reasoning, not digit guessing.','MAKE 10':'Students use 10 as a helpful benchmark for mental math.','ADDITION / SUBTRACTION WITHIN 20':'Students choose and explain efficient strategies within 20.','ADDITION / SUBTRACTION WITHIN 100':'Students reason with tens and ones and compare valid strategies.','MISSING PART':'Students reason about an unknown part using relationships among quantities.','ODD / EVEN':'Students justify parity using pairs or equal groups.','SKIP COUNTING':'Students notice and extend equal-step number patterns.','HUNDRED CHART':'Students use +1, -1, +10, and -10 structure to reason.','NUMBER LINE':'Students locate and compare numbers relationally on a number line.','WORD PROBLEMS':'Students represent a short situation and defend the operation they choose.','BAR MODELS: PARTS & WHOLE':'Students identify parts and whole, use bar models to represent story problems, and connect the model to an equation.','ERROR ANALYSIS':'Students identify a mathematical error and explain how to repair it.','STRATEGY COMPARISON':'Students compare two valid approaches for efficiency and clarity.','SHOW ANOTHER WAY / CONVINCE ME':'Students produce multiple representations and defend equivalence.',
'PHONICS':'Students use a visible sound-spelling pattern to read and manipulate words.','WORD READING':'Students attend to all parts of a word and explain how they decoded it.','SPELLING PATTERNS':'Students notice a spelling pattern and use it to reason about new words.','FLUENCY':'Students reread short text accurately, smoothly, and with appropriate phrasing.','PHRASE READING':'Students group words into meaningful phrases while reading aloud.','SENTENCE CONVENTIONS':'Students notice and repair capitalization, punctuation, and agreement.','SENTENCE EXPANSION':'Students add precise details that strengthen a simple sentence.','SENTENCE COMBINING':'Students combine related ideas into one clear sentence.','VOCABULARY / WORD CHOICE':'Students choose precise words using sentence context and explain why.'};return g[skill]||'Students explain their thinking and respond to another idea.'}
function teachMathPrompt(skill,mode){let a,b,n,t,o;
const q=(prompt,sub='')=>({prompt,sub});
switch(skill){
case 'NUMBER SENSE': n=rand(14,39); if(mode==='BTC')return [q(`Find as many ways as you can to make ${n}.`,`Use numbers, drawings, or groups. Can your group prove two representations are equal?`),q('Compare with another group.','Find one way that is different from yours.')]; if(mode==='DISCUSS')return [q(`Which tells you more about ${n}?\n${Math.floor(n/10)} tens and ${n%10} ones   OR   ${n-5} + 5`,`Why? Could both be useful?`)]; return [q(`What do you notice about ${n}?`,`Show two relationships you can use to describe it.`),q(`Now change ${n} by 10.`,`What changes? What stays the same?`)];
case 'TENS + ONES': n=rand(32,78); if(mode==='BTC')return [q(`Build ${n} in as many tens-and-ones combinations as you can.`,`How many can your group find?`),q(`Can ${n} be ${Math.floor(n/10)-1} tens and ${n%10+10} ones?`,`Convince another group.`),q('Find a representation another group may not have.')]; if(mode==='DISCUSS')return [q(`A student says ${n} can ONLY be ${Math.floor(n/10)} tens and ${n%10} ones.`,`Agree or disagree? Convince us.`)]; return [q(`Build ${n} two different ways.`,`Can your group find a third?`),q(`Compare your ways.`,`What stayed equal even though the tens and ones changed?`),q(`Quick check: represent ${n+1} in a nonstandard way.`)];
case 'COMPOSE / DECOMPOSE': n=rand(12,30); if(mode==='BTC')return [q(`Write as many equations as you can that equal ${n}.`,`Try to make every equation look different.`),q('Circle two equations that show the same relationship in different ways.','Convince another group.')]; if(mode==='DISCUSS')return [q(`${n} = ${rand(3,n-4)} + ___\nIs there only one useful way to break apart ${n}?`,`Which decomposition would help you calculate quickly?`)]; return [q(`Break apart ${n} in THREE ways.`),q('Which way would be most helpful for mental math?','Explain why.')];
case 'COMPARE NUMBERS': a=rand(32,89); do{b=rand(32,89)}while(a===b); if(mode==='BTC')return [q(`Make a two-digit number greater than ${Math.min(a,b)} but less than ${Math.max(a,b)}.`,`How many can your group find?`),q('Order your answers from least to greatest.','What shortcut helped?')]; if(mode==='DISCUSS')return [q(`Which matters first when comparing ${a} and ${b}: tens or ones?`,`Explain when that rule could fail or why it cannot.`)]; return [q(`Which is greater?\n${a}   or   ${b}`,`Explain without counting by ones.`),q(`Make a number BETWEEN them.`)];
case 'MAKE 10': a=rand(5,9);b=rand(4,9); if(a+b<=10)b=rand(11-a,9); if(mode==='BTC')return [q(`Use make-10 to solve ${a} + ${b}.`,`Find TWO ways to rearrange or break apart the addends.`),q('Which strategy is easiest to explain at the board?')]; if(mode==='DISCUSS')return [q(`For ${a} + ${b}, would you make 10 with ${a} or ${b}?`,`Does it matter? Defend your choice.`)]; return [q(`${a} + ${b} = ?`,`Make 10 first. Show what moves.`),q('Now solve it a different way.','Which felt faster?')];
case 'ADDITION / SUBTRACTION WITHIN 20': a=rand(8,16);b=rand(3,Math.min(9,20-a)); if(mode==='BTC')return [q(`Solve ${a} + ${b} in as many ways as your group can.`,`No repeated strategy with different drawings.`),q(`Which method would you teach a first grader?`,`Why that one?`)]; if(mode==='DISCUSS')return [q(`Two students solve ${a+b} − ${b}.\nOne counts back. One thinks “${b} + what = ${a+b}?”`,`Which strategy makes more sense here? Why?`)]; return [q(`${a} + ${b} = ?`,`Solve mentally. Be ready to explain what you changed.`),q(`${a+b} − ${a} = ?`,`How is this connected to the first problem?`)];
case 'ADDITION / SUBTRACTION WITHIN 100': a=rand(24,68);b=rand(11,29);if(a+b>96)b=rand(11,96-a); if(mode==='BTC')return [q(`Solve ${a} + ${b} THREE ways.`,`Try tens-and-ones, an open number line, and one strategy your group invents.`),q('Rank your strategies from easiest to hardest to explain.','Defend your ranking.'),q(`Now change one addend by +1.`,`What changes in the answer without starting over?`)]; if(mode==='DISCUSS')return [q(`A student solves ${a} + ${b} by adding tens first.\nAnother jumps by ${b} on a number line.`,`Which strategy is clearer for THIS problem? Why?`)]; return [q(`${a} + ${b} = ?`,`Solve without the standard algorithm. Show the tens and ones.`),q('Find a second strategy.','What is the same in both?')];
case 'MISSING PART': a=rand(12,38);b=rand(4,15); if(mode==='BTC')return [q(`${a} + □ = ${a+b}`,`Find THREE ways to prove the missing part.`),q(`Write a DIFFERENT missing-part equation with the same answer.`)]; if(mode==='DISCUSS')return [q(`${a} + □ = ${a+b}`,`Would you add on or subtract? Which is more efficient?`)]; return [q(`${a} + □ = ${a+b}`,`Solve it without guessing.`),q('Write the related subtraction equation.')];
case 'ODD / EVEN': n=rand(21,58); if(mode==='BTC')return [q(`Find FIVE numbers near ${n} that are even.`,`Prove each one using pairs or equal groups.`),q('Make a rule that predicts whether the next number is odd or even.')]; if(mode==='DISCUSS')return [q(`A student says ${n} is ${n%2?'odd':'even'} because its last digit is ${n%10}.`,`That rule works. But WHY does it work?`)]; return [q(`Is ${n} odd or even?`,`Prove it TWO ways.`)];
case 'SKIP COUNTING': t=pick([2,5,10]);n=t*rand(2,6); if(mode==='BTC')return [q(`Start at ${n}. Count by ${t}s.`,`Write as many numbers as you can in 60 seconds, then find patterns in the digits.`),q('Make one prediction about a number much later in the pattern.','Prove it without listing every number.')]; if(mode==='DISCUSS')return [q(`When counting by ${t}s, what can you predict about the ones digit?`,`Why does that pattern repeat?`)]; return [q(`${n}, ${n+t}, ${n+2*t}, ___, ___`,`What is changing each time?`),q('Predict the 10th number without writing every step.')];
case 'HUNDRED CHART': n=rand(23,76); if(mode==='BTC')return [q(`Start at ${n}. Find FOUR different paths to ${n+11} on a hundred chart.`,`Write each path with +1, -1, +10, -10.`),q('Which path is shortest?','Can two different paths use the same number of moves?')]; if(mode==='DISCUSS')return [q(`A student says 10 more than ${n} is ${n+1}.`,`What did the student misunderstand? How would the hundred chart prove it?`)]; return [q(`Hundred-chart mystery:\nI am 10 more than ${n} and 1 less than ${n+11}.\nWhat number am I?`),q('Create a new clue for the same number.')];
case 'NUMBER LINE': a=rand(18,45);b=rand(a+12,79);n=rand(a+2,b-2); if(mode==='BTC')return [q(`Place ${a}, ${n}, and ${b} on a blank number line.`,`No tick marks are given. Convince another group your spacing makes sense.`),q('Add one number that belongs between the first two.','Explain its location relationally.')]; if(mode==='DISCUSS')return [q(`Which is closer to ${n}: ${a} or ${b}?`,`How can you tell without drawing every tick mark?`)]; return [q(`Where would ${n} go between ${a} and ${b}?`,`Draw a quick number line and defend the location.`)];
case 'WORD PROBLEMS': a=rand(18,38);b=rand(6,17); if(mode==='BTC')return [q(`There are ${a} markers. A teacher adds ${b} more.\nHow many now?`,`Represent the story THREE different ways. Which representation makes the action clearest?`),q('Change the story so subtraction is needed but the same three numbers can appear.')]; if(mode==='DISCUSS')return [q(`Mia has ${a} cards. She gets ${b} more.`,`What tells you whether to add or subtract? What information matters?`)]; return [q(`There are ${a} shells. ${b} more are added.\nHow many shells now?`,`Solve and show how the story appears in your equation.`)];
case 'ERROR ANALYSIS': a=rand(31,68);b=pick([10,20]); if(mode==='BTC')return [q(`A student says ${a} + ${b} = ${a+b-10}.`,`Find the mistake. Then show TWO ways to prove the correct answer.`),q('Write a new wrong answer that reveals a DIFFERENT misconception.','Can another group diagnose it?')]; return [q(`A student says:\n${a} + ${b} = ${a+b-10}`,`What probably happened? Convince us of the correct answer.`)];
case 'STRATEGY COMPARISON': a=rand(26,57);b=rand(12,28);if(a+b>90)b=12; return [q(`Solve ${a} + ${b}.`,`Strategy A: break apart tens and ones.\nStrategy B: make a friendly number first.`),q('Which strategy is more efficient HERE?','Could the other strategy still be correct?')];
case 'SHOW ANOTHER WAY / CONVINCE ME': n=rand(24,74); if(mode==='BTC')return [q(`Show ${n} as many ways as possible.`,`Every representation must make the SAME quantity obvious.`),q(`Someone claims ${n} = ${Math.floor(n/10)-1} tens + ${n%10+10} ones.`,`Prove or disprove it.`)]; return [q(`Show ${n} THREE different ways.`,`Numbers, drawings, tens/ones, or a number line.`),q('Choose your strangest correct representation.','Convince us it is equal to the others.')];
default:return [q('Show 47 in two different ways.','Explain why both representations are equal.')];}}
function teachQuickMath(skill){let a,b,n;switch(skill){case 'TENS + ONES':n=rand(12,89);return `${n} = ___ tens + ___ ones`;case 'COMPOSE / DECOMPOSE':n=rand(9,20);a=rand(2,n-2);return `${n} = ${a} + ___`;case 'COMPARE NUMBERS':a=rand(21,89);b=rand(21,89);return `${a} ___ ${b}`;case 'MAKE 10':a=rand(1,9);return `${a} + ___ = 10`;case 'ADDITION / SUBTRACTION WITHIN 20':a=rand(5,13);b=rand(2,Math.min(7,20-a));return Math.random()<.5?`${a} + ${b} = ?`:`${a+b} − ${b} = ?`;case 'ADDITION / SUBTRACTION WITHIN 100':a=rand(21,69);b=pick([10,20]);return Math.random()<.5?`${a} + ${b} = ?`:`${a+b} − ${b} = ?`;case 'MISSING PART':a=rand(8,16);b=rand(2,8);return `${a} + ___ = ${a+b}`;case 'ODD / EVEN':n=rand(11,79);return `${n}: odd or even?`;case 'SKIP COUNTING':n=pick([2,5,10]);a=n*rand(2,6);return `${a}, ${a+n}, ${a+2*n}, ___`;case 'HUNDRED CHART':n=rand(22,78);return `10 more than ${n}?`;case 'NUMBER LINE':a=rand(20,60);return `What is ${a+10} − 10?`;case 'WORD PROBLEMS':a=rand(8,18);b=rand(2,8);return `${a} birds + ${b} more. How many?`;case 'ERROR ANALYSIS':a=rand(23,67);return `True or false: ${a} + 10 = ${a+1}`;case 'STRATEGY COMPARISON':a=rand(6,9);b=rand(5,9);return `${a} + ${b}: make 10 or count on?`;case 'SHOW ANOTHER WAY / CONVINCE ME':n=rand(12,59);return `Show ${n} another way.`;default:n=rand(12,49);return `What do you notice about ${n}?`}}
