function teachElaPrompt(skill,mode){const q=(prompt,sub='')=>({prompt,sub});const words={PHONICS:[['ship','shop','fish'],['chat','chin','much'],['thin','bath','moth'],['cake','game','late'],['seed','feet','keep']], 'WORD READING':[['stamp','stop','step'],['plan','clip','frog'],['shine','chop','thin']], 'SPELLING PATTERNS':[['rain','train','paint'],['boat','coat','road'],['play','stay','tray']]};
if(skill==='PHONICS'||skill==='WORD READING'||skill==='SPELLING PATTERNS'){const w=pick(words[skill]);if(mode==='BTC')return [q(w.join('     '),`Sort or group these words in a way your team can defend.`),q('Add TWO new words that follow the same pattern.','Can another group read them?')];if(mode==='DISCUSS')return [q(w.join('     '),`What spelling or sound pattern connects these words? Where do you see it?`)];return [q(w.join('     '),`Read them. What do you notice?`),q('Change one letter or sound.','Make a new real word.')];}
if(skill==='FLUENCY'||skill==='PHRASE READING'){const s=pick(['After the rain stopped, the children hurried outside to play.','The small brown rabbit paused, listened, and hopped under the bush.','Before lunch, our class quietly finished the last page of the story.']);if(mode==='DISCUSS')return [q(s,`Where should your voice pause? Why?`)];return [q(s,`Read it once accurately.`),q(s,`Read it again smoothly. Group words that belong together.`)];}
if(skill==='SENTENCE CONVENTIONS'){const s=pick(['my friend plays soccer','where did the puppy go','the birds flies over the tree']);if(mode==='BTC')return [q(s,`Fix every convention problem you can find. Be ready to defend each change.`),q('Write a NEW sentence with the same kind of convention challenge for another group.')];if(mode==='DISCUSS')return [q(s,`What needs to change? Which correction matters first for the reader?`)];return [q(s,`Fix the sentence.`),q('Explain one correction.')];}
if(skill==='SENTENCE EXPANSION'){const pair=pick([['The bird flew.','The bright red bird flew over the wet playground.'],['The dog ran.','The muddy dog ran quickly toward the open gate.'],['The girl laughed.','The girl laughed loudly when the puppy chased its tail.'],['The truck stopped.','The blue delivery truck stopped beside our school.']]),s=pair[0];if(mode==='BTC')return [q(s,`Make this sentence create the CLEAREST picture.`),q('Compare with another group.','Which details changed the picture most?')];if(mode==='DISCUSS')return [q(`${s}\n${pair[1]}`,`Which sentence is stronger? What exactly made it stronger?`)];return [q(s,`Add WHO/WHAT, WHERE, WHEN, or HOW details.`),q('Remove one weak detail.','Did the sentence get stronger or weaker?')];}
if(skill==='SENTENCE COMBINING'){const pair=pick([['The dog was wet.','The dog shook its fur.'],['Mia found a shell.','The shell was shiny.'],['The rain stopped.','We went outside.']]);if(mode==='BTC')return [q(`${pair[0]}\n${pair[1]}`,`Combine these in as many clear ways as your group can.`),q('Which combined sentence sounds best?','Defend your choice.')];return [q(`${pair[0]}\n${pair[1]}`,`Combine the ideas into ONE clear sentence.`),q('Read it aloud.','Does it sound smooth?')];}
const c=pick([['The tiny ant carried a crumb.','tiny','small','noisy'],['Maya stared at the enormous wave.','enormous','very large','very quiet'],['The puppy dashed across the yard.','dashed','ran quickly','slept']]);if(mode==='BTC')return [q(c[0],`Replace “${c[1]}” with TWO words that could still fit.`),q('Which replacement is most precise?','Convince another group.')];if(mode==='DISCUSS')return [q(c[0],`Does “${c[1]}” mean ${c[2]} or ${c[3]}? What clue helps?`)];return [q(c[0],`What does “${c[1]}” mean here?`),q('Replace it with another word that keeps the meaning.')];}
function teachQuickEla(skill){if(skill==='PHONICS'||skill==='SPELLING PATTERNS')return pick(['ship   shop   fish','rain   train   paint','cake   game   late','seed   feet   keep']);if(skill==='WORD READING')return pick(['stamp','clip','shine','frog','chop']);if(skill==='FLUENCY'||skill==='PHRASE READING')return pick(['Read smoothly: The small dog ran across the yard.','Read smoothly: After lunch, we walked quietly inside.']);if(skill==='SENTENCE CONVENTIONS')return pick(['Fix: my dog likes to run','Fix: where is my book','Choose: The birds (fly / flies).']);if(skill==='SENTENCE EXPANSION')return pick(['Add one strong detail: The bird flew.','Add one strong detail: The dog ran.']);if(skill==='SENTENCE COMBINING')return 'Combine: The cat was tired. The cat slept.';return pick(['Best word: The puppy (dashed / slept) home.','What does tiny mean in: The tiny ant moved?'])}

function teachBarModelHtml(left,right,whole,opts={}){
 const hideLeft=opts.hideLeft===true,hideRight=opts.hideRight===true,hideWhole=opts.hideWhole===true,blank=opts.blank===true;
 const safeLeft=Math.max(1,Number(left)||1),safeRight=Math.max(1,Number(right)||1);
 const leftLabel=blank?'':(hideLeft?'?':left),rightLabel=blank?'':(hideRight?'?':right),wholeLabel=blank?'':(hideWhole?'?':whole);
 return `<div class="teach-bar-model"><div class="teach-bar-label">PARTS</div><div class="teach-bar-parts"><div class="teach-bar-part" style="flex:${safeLeft}">${leftLabel}</div><div class="teach-bar-part alt" style="flex:${safeRight}">${rightLabel}</div></div><div class="teach-bar-label" style="margin-top:3px">WHOLE</div><div class="teach-bar-whole">${wholeLabel}</div></div>`
}
function barModelTeachSequence(mode){
 const knownA=rand(4,8),knownB=rand(3,7),knownWhole=knownA+knownB;
 const wholeA=rand(5,9),wholeB=rand(4,8),whole=wholeA+wholeB;
 const missingWhole=rand(12,18),knownPart=rand(4,missingWhole-5),missingPart=missingWhole-knownPart;
 const buildWhole=rand(13,19),buildKnown=rand(5,buildWhole-5),buildMissing=buildWhole-buildKnown;
 const eqWhole=rand(12,18),eqKnown=rand(4,eqWhole-5),eqMissing=eqWhole-eqKnown;
 const tryWhole=rand(13,19),tryKnown=rand(5,tryWhole-5),tryMissing=tryWhole-tryKnown;
 const q=(prompt,sub,visualHtml='')=>({prompt,sub,visualHtml});
 const groupCue=mode==='BTC'?' Work it at your board with your group.':mode==='DISCUSS'?' Decide first, then defend your reasoning.':'';
 return [
  q('PART + PART = WHOLE\nA bar model shows how the parts make the whole.',`SEE IT · 3 MIN\nWhich numbers are the parts? Which number is the whole?${groupCue}`,teachBarModelHtml(knownA,knownB,knownWhole)),
  q(`FIND THE WHOLE\nThere are ${wholeA} kids reading. ${wholeB} more join them. How many kids are reading now?`,`3 MIN · We know BOTH parts. What is the whole? Write the equation.${groupCue}`,teachBarModelHtml(wholeA,wholeB,whole,{hideWhole:true})),
  q(`FIND THE MISSING PART\nThere are ${missingWhole} crayons altogether. ${knownPart} are red. The rest are blue. How many are blue?`,`4 MIN · We know the whole and one part. What part is missing?${groupCue}`,teachBarModelHtml(knownPart,missingPart,missingWhole,{hideRight:true})),
  q(`BUILD IT FROM THE STORY\nThere are ${buildWhole} books on a shelf. ${buildKnown} are nonfiction. The rest are fiction.`,`3 MIN · Tell me where ${buildWhole} and ${buildKnown} belong before we solve. What should the unknown box represent?${groupCue}`,teachBarModelHtml(buildKnown,buildMissing,buildWhole,{hideRight:true})),
  q(`MATCH THE EQUATION\nThe whole is ${eqWhole}. One part is ${eqKnown}. The other part is missing.`,`3 MIN · Which equations can help? ${eqWhole} − ${eqKnown} = □   or   ${eqKnown} + □ = ${eqWhole}? Explain why.${groupCue}`,teachBarModelHtml(eqKnown,eqMissing,eqWhole,{hideRight:true})),
  q(`YOUR TURN · INDEPENDENT\nThere are ${tryWhole} stickers altogether. ${tryKnown} are stars. The rest are circles. How many are circles?`,`4 MIN · Draw the bar model yourself. Write an equation. Solve. Then name the whole, known part, and missing part.`,teachBarModelHtml(1,1,1,{blank:true}))
 ]
}

const TEACH_TO_WIN={
'NUMBER SENSE':'COMPOSE / DECOMPOSE','TENS + ONES':'TENS + ONES','COMPOSE / DECOMPOSE':'COMPOSE / DECOMPOSE','COMPARE NUMBERS':'COMPARE NUMBERS','MAKE 10':'MAKE 10','MISSING PART':'MISSING PART','ODD / EVEN':'ODD / EVEN','SKIP COUNTING':'SKIP COUNTING','HUNDRED CHART':'HUNDRED CHART','NUMBER LINE':'NUMBER LINE','WORD PROBLEMS':'WORD PROBLEMS','SHOW ANOTHER WAY / CONVINCE ME':'PLACE VALUE'};
function teachMathSet(skill,mode){if(skill==='BAR MODELS: PARTS & WHOLE')return barModelTeachSequence(mode);if(mode==='QUICK FIRE'){const out=[],seen=new Set();for(let g=0;g<100&&out.length<8;g++){const p=teachQuickMath(skill);if(!seen.has(p)){seen.add(p);out.push({prompt:p,sub:''})}}return out}
if(skill==='ERROR ANALYSIS'||skill==='STRATEGY COMPARISON'){const out=[],seen=new Set();for(let g=0;g<60&&out.length<6;g++){for(const x of teachMathPrompt(skill,mode)){const key=x.prompt+'|'+x.sub;if(!seen.has(key)){seen.add(key);out.push(x);if(out.length===6)break}}}return out}
const winSkill=skill==='ADDITION / SUBTRACTION WITHIN 20'?null:skill==='ADDITION / SUBTRACTION WITHIN 100'?null:TEACH_TO_WIN[skill]||'COMPOSE / DECOMPOSE';const slots=mode==='DISCUSS'?[4,5,3,4,5,3]:mode==='BTC'?[1,2,3,4,5,3]:[0,1,2,3,4,5];const out=[];for(let i=0;i<6;i++){let q;if(skill==='ADDITION / SUBTRACTION WITHIN 20')q=mathWinQuestion(i%2===0?'ADDITION WITHIN 20':'SUBTRACTION WITHIN 20','GRADE 2 TARGET',slots[i]);else if(skill==='ADDITION / SUBTRACTION WITHIN 100')q=mathWinQuestion(i%2===0?'ADDITION WITHIN 100':'SUBTRACTION WITHIN 100','GRADE 2 TARGET',slots[i]);else q=mathWinQuestion(winSkill,'GRADE 2 TARGET',slots[i]);let sub='';if(mode==='BTC')sub=pick(['At your board: show at least two ways and be ready to defend one.','Compare with another group. What is the same and what is different?','Can your group prove the claim without only saying the answer?','Find a representation or strategy another group might not use.']);else if(mode==='DISCUSS')sub=pick(['Decide whether you agree, then use evidence.','Which reasoning is strongest? Explain why.','What misconception could cause a wrong answer here?','Convince someone who disagrees.']);else sub=i<2?'Think first. Then show how you know.':i<4?'Try it, then compare your approach with a partner.':'Be ready to explain or defend your reasoning.';out.push({prompt:q.prompt,sub})}return out}
const TEACH_PHONICS_BANKS=[
{label:'sh',words:['ship','shop','fish','rush','shut','dish','shell','wish'],phrases:['the fish','rush the ship','a red shell'],sentences:['The fish can rush past.','Josh can shut the shop.']},
{label:'ch',words:['chat','chin','chop','much','rich','chip','lunch','bench'],phrases:['chat at lunch','a rich lunch','the chip'],sentences:['Chad can chop the yam.','We chat at lunch.']},
{label:'short a',words:['map','sat','cat','jam','hat','ram','tap','cap'],phrases:['a fat cat','the tan ram','a red cap'],sentences:['Sam has a tan cap.','The cat sat on the mat.']},
{label:'long a',words:['cake','game','late','made','same','gate','name','lake'],phrases:['a late game','the same cake','by the gate'],sentences:['Jake made the cake.','The game was late.']},
{label:'ee',words:['seed','feet','keep','green','sleep','meet','deep','week'],phrases:['green feet','keep the seed','a deep sleep'],sentences:['Keep the green seed.','We meet this week.']}
];
