function newTeachSequence(){let seq=teachState.subject==='MATH'?teachMathSet(teachState.skill,teachState.mode):teachElaSet(teachState.skill,teachState.mode);if(!seq||!seq.length)seq=teachState.subject==='MATH'?teachMathPrompt(teachState.skill,teachState.mode):teachElaPrompt(teachState.skill,teachState.mode);teachState.sequence=seq;teachState.index=0;teachState.lastKey=[teachState.subject,teachState.skill,teachState.mode,seq[0]?.prompt].join('|');renderTeachProjector()}
function renderTeachSkills(){const list=TEACH_SKILLS[teachState.subject];if(!list.includes(teachState.skill))teachState.skill=list[0];$('#teachSkillSelect').innerHTML=list.map(x=>`<option>${esc(x)}</option>`).join('');$('#teachSkillSelect').value=teachState.skill}
function loadTeach(){renderTeachSkills();$$('#teachSubjectButtons button').forEach(b=>b.classList.toggle('selected',b.dataset.value===teachState.subject));$$('#teachModeButtons button').forEach(b=>b.classList.toggle('selected',b.dataset.value===teachState.mode))}
function renderTeachProjector(){if(!teachState.sequence)return;const x=teachState.sequence[teachState.index];$('#teachGoal').textContent=teachGoal(teachState.skill);$('#teachPrompt').textContent=x.prompt;const visual=$('#teachVisual');visual.innerHTML=x.visualHtml||'';visual.classList.toggle('teach-hidden',!x.visualHtml);$('#teachSubprompt').textContent=x.sub||'';$('#teachSubprompt').classList.toggle('teach-hidden',!x.sub);$('#teachProgress').textContent=`${teachState.index+1} / ${teachState.sequence.length}`;$('#teachPrev').disabled=teachState.index===0;$('#teachNext').textContent=teachState.index===teachState.sequence.length-1?(teachState.mode==='QUICK FIRE'?'MORE':'DONE'):'NEXT'}
$$('#teachSubjectButtons button').forEach(b=>b.onclick=()=>{teachState.subject=b.dataset.value;$$('#teachSubjectButtons button').forEach(x=>x.classList.toggle('selected',x===b));teachState.skill=TEACH_SKILLS[teachState.subject][0];renderTeachSkills()});
$('#teachSkillSelect').onchange=()=>teachState.skill=$('#teachSkillSelect').value;
$$('#teachModeButtons button').forEach(b=>b.onclick=()=>{teachState.mode=b.dataset.value;$$('#teachModeButtons button').forEach(x=>x.classList.toggle('selected',x===b))});
$('#teachStartBtn').onclick=()=>{$('#teachSetup').classList.add('teach-hidden');$('#teachProjector').classList.remove('teach-hidden');newTeachSequence()};
$('#teachBackSetup').onclick=()=>{$('#teachProjector').classList.add('teach-hidden');$('#teachSetup').classList.remove('teach-hidden')};
$('#teachNew').onclick=newTeachSequence;$('#teachPrev').onclick=()=>{if(teachState.index>0){teachState.index--;renderTeachProjector()}};$('#teachNext').onclick=()=>{if(teachState.index<teachState.sequence.length-1){teachState.index++;renderTeachProjector()}else if(teachState.mode==='QUICK FIRE'){newTeachSequence()}else{$('#teachProjector').classList.add('teach-hidden');$('#teachSetup').classList.remove('teach-hidden')}};
$('#teachFullscreen').onclick=()=>{const el=$('#teachProjector');if(!document.fullscreenElement&&el.requestFullscreen)el.requestFullscreen().catch(()=>{});else if(document.exitFullscreen)document.exitFullscreen()};
function renderTeachTimer(){const s=Math.max(0,teachState.timerSeconds);$('#teachTimerDisplay').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function stopTeachTimer(){if(teachState.timerId){clearInterval(teachState.timerId);teachState.timerId=null}$('#teachTimerStart').textContent='START'}
$$('[data-t]').forEach(b=>b.onclick=()=>{stopTeachTimer();teachState.timerBase=+b.dataset.t;teachState.timerSeconds=teachState.timerBase;renderTeachTimer()});
$('#teachTimerStart').onclick=()=>{if(teachState.timerId){stopTeachTimer();return}if(teachState.timerSeconds<=0)teachState.timerSeconds=teachState.timerBase;$('#teachTimerStart').textContent='PAUSE';teachState.timerId=setInterval(()=>{teachState.timerSeconds--;renderTeachTimer();if(teachState.timerSeconds<=0)stopTeachTimer()},1000)};
$('#teachTimerReset').onclick=()=>{stopTeachTimer();teachState.timerSeconds=teachState.timerBase;renderTeachTimer()};renderTeachTimer();
$('#barModelTeachBtn').onclick=()=>{teachState.subject='MATH';teachState.skill='BAR MODELS: PARTS & WHOLE';teachState.mode='FIGURE IT OUT';setScreen('teach')};
