function readingWinQuestion(skill,level,slot){slot=clampWinSlot(slot);const stage=WIN_STAGES[slot];const cvc=['map','sat','fin','rug','hop','red','lip','sun','bed','fox'],dig=['ship','chat','thin','shop','fish','chin','rush','much'];let p='';
 switch(skill){
 case 'PHONOLOGICAL AWARENESS':{const sets=[['sun','map','fish'],['lip','bed','rug']];const w=pick(sets);p=level==='FOUNDATION'?[`Say “sunset.” What two word parts do you hear?`,`Blend: rain — bow. What word?`,`Split “table” into its syllables.`,`Say “sunset” without “sun.”`,`Which has more syllables: “rabbit” or “cat”? Explain how you checked.`,`Make a two-part word, then take one part away and say what remains.`][slot]:[`Blend: /m/ /a/ /p/.`,`Blend: /s/ /u/ /n/.`,`Segment “fish” into its sounds.`,`Change the first sound in “map” to /s/. What word now?`,`A student says “ship” has four sounds because it has four letters. Do you agree?`,`Choose a CVC word. Segment it, change ONE phoneme, and blend the new word.`][slot];break}
 case 'LETTER / SOUND':{const pairs=[['m','/m/'],['s','/s/'],['f','/f/'],['r','/r/'],['t','/t/']];const [l,s]=pick(pairs);p=[`What sound does ${l.toUpperCase()} usually spell?`,`Which letter spells ${s}?`,`Say a word that begins with ${s}.`,`Which does NOT begin with ${s}: ${pick(['map','sun','fish'])}, ${pick(['rug','top','fin'])}, or ${pick(['moon','sit','fan'])}? Explain.`,`A student sees ${l.toUpperCase()} and says the wrong sound. What should they check with their mouth or a known word?`,`Give TWO words with ${s}: one at the beginning and one where you can hear it somewhere else.`][slot];break}
 case 'BLENDING':{const words=level==='FOUNDATION'?cvc:dig;const w=pick(words),w2=pick(words.filter(x=>x!==w));const phrase=level==='FOUNDATION'?pick(['a red fox','the sun','a big rug','the map']):pick(['the fish','a thin ship','the shop','much fish']);const sent=level==='FOUNDATION'?pick(['Sam can hop.','The fox can run.','The map is red.','Sit on the rug.']):pick(['The fish is in the shop.','The ship can rush past.','Chad can shut the lid.','The thin fish can swim.']);p=[`Read: ${w}`,`Blend it slowly, then read it fast: ${w2}`,`Change one sound in ${w} to make a new real word.`,`Read this phrase: “${phrase}”`,`Read: “${sent}”`,`Read two new words with the same kind of sound pattern: ${pick(words)} · ${pick(words)}.`][slot];break}
 case 'SEGMENTING':{const w=pick(cvc),w2=pick(cvc.filter(x=>x!==w));p=[`Say the sounds in “${w}.”`,`Push one counter for each sound in “${w2}.”`,`How many phonemes are in “${w}”? Say them in order.`,`Change ONE sound in “${w}” to make a new word. Which sound changed?`,`A student writes one letter for every mouth movement instead of every phoneme. How could you help them segment “${w2}”?`,`Choose a CVC word, segment it, then map each phoneme to a grapheme.`][slot];break}
 case 'PHONICS PATTERN':{const words=level==='FOUNDATION'?['map','sat','cat','jam','hat','ram']:level==='BRIDGE'?['ship','shop','fish','rush','shut','dish']:['chat','chin','chop','much','rich','such'];const label=level==='FOUNDATION'?'short a':level==='BRIDGE'?'sh':'ch';const w=pick(words),w2=pick(words.filter(x=>x!==w));const sort=[...words].sort(()=>Math.random()-.5).slice(0,3);p=[`Read: ${w}`,`Read: ${w2}. What ${label} spelling pattern helps you?`,`Read these ${label} words: ${sort.join(' · ')}. What stays the same?`,`Spell “${w}” after stretching each sound.`,`Read this ${label} phrase: “${level==='FOUNDATION'?pick(['a fat cat','a tan ram','the jam']):level==='BRIDGE'?pick(['the fish','a shut shop','rush the ship']):pick(['much chat','a rich chin','chop it'])}.” Read it smoothly, then name the pattern.`,`Write a new ${label} word, then use it in a short sentence.`][slot];break}
 case 'WORD READING':{const words=[...cvc,...dig];const w=pick(words);p=[`Read: ${w}`,`Read two words: ${pick(words)} · ${pick(words)}`,`Read three mixed words without guessing: ${pick(words)} · ${pick(words)} · ${pick(words)}`,`Read this phrase smoothly: “the ${w} can run”`,`Read: “The ${w} is on the rug.”`,`Read a fresh mixed stack: ${pick(words)} · ${pick(words)} · ${pick(words)} · ${pick(words)}. Which word needed the most decoding?`][slot];break}
 case 'HIGH-FREQUENCY WORDS':{const h=['the','said','have','they','from','were','there','what'];const w=pick(h);p=[`Read: ${w}`,`Read it in a phrase: “${w} dog”`,`Read: “${w[0].toUpperCase()+w.slice(1)} kids can play.”`,`Which part of “${w}” can you map by sound? Which part must you remember?`,`Read “${w}” in two different short sentences without stopping on the word.`,`Write a short sentence using “${w},” then reread it smoothly.`][slot];break}
 case 'FLUENCY':{const s1='The small dog ran to the gate.',s2='After lunch, Mia found a red shell.';p=[`Read this word smoothly: “small.”`,`Read this phrase: “the small dog”`,`Read: “${s1}”`,`Reread: “${s2}” Make your voice pause naturally at the comma.`,`Which reading helps meaning more: word-by-word or in meaningful phrases? Demonstrate both with “${s1}”`,`Read these two sentences smoothly: “${s1} ${s2}” Then tell one thing that happened.`][slot];break}
 case 'PHRASE READING':{const s='After lunch / the small dog / ran to the gate.';p=[`Read: “after lunch”`,`Read: “the small dog”`,`Read by phrases: “${s}”`,`Where should your voice pause in: “Before school the kids waited by the door.”`,`A student reads “the / small / dog / ran / to / the / gate.” What would you change to make meaning clearer?`,`Mark phrase breaks in: “When the rain stopped the children ran outside to play.” Then read it smoothly.`][slot];break}
 case 'SHORT COMPREHENSION':{const passage='Mia found a tiny crab near a tide pool. It hid under a rock when she stepped closer.';p=[`Read: “${passage}” Who is the text about?`,`What did Mia find?`,`What happened after Mia stepped closer?`,`Why might the crab have hidden? Use the text plus a reasonable idea.`,`Which detail best proves where Mia was: “tiny crab,” “near a tide pool,” or “stepped closer”? Explain.`,`Retell the two sentences in your own words without changing the important information.`][slot];break}
 default:p=[`Try one example of ${skill.toLowerCase()}.`,`Try another related example.`,`Explain how you handled the target pattern.`,`Use the skill in a short phrase or sentence.`,`Explain an error or compare two attempts.`,`Create or read one new example that proves the same skill.`][slot];
 }
 return winQ(stage,slot,p,'')}

const WIN_MATERIAL_THEMES={
'classroom':{subjects:['Maya','our class','the reading group'],actions:['opened their notebooks','sorted the word cards','carried the books to the shelf'],places:['near the whiteboard','at the back table','beside the classroom library'],events:['the bell rang','the teacher gave the signal','the timer ended'],reasons:['they were ready to begin','the materials were mixed up','everyone could see the examples']},
'playground':{subjects:['the children','Kai','two friends'],actions:['ran toward the swings','passed the ball across the court','waited beside the slide'],places:['near the basketball court','under the big tree','beside the playground gate'],events:['recess began','the whistle blew','the rain stopped'],reasons:['they wanted one more turn','the court was finally open','they needed to join their class']},
'home':{subjects:['my brother','Lena','the family'],actions:['stacked the clean dishes','carried the laundry upstairs','set the table for dinner'],places:['in the kitchen','beside the couch','near the front door'],events:['dinner was ready','the movie ended','the doorbell rang'],reasons:['the room needed to be tidy','everyone was getting hungry','they were expecting a visitor']},
'animals':{subjects:['the small rabbit','a bright green gecko','the sleepy puppy'],actions:['hid beneath the leaves','scurried across the warm rock','curled beside the blanket'],places:['near the garden wall','under the porch','beside the water bowl'],events:['the wind grew stronger','the sun came out','a loud truck passed'],reasons:['it heard a sudden sound','the ground felt warm','it wanted a quiet place']},
'weather':{subjects:['the dark clouds','a cool breeze','the morning rain'],actions:['moved across the valley','shook the palm leaves','tapped against the window'],places:['above the mountains','across the playground','outside the classroom'],events:['the sky grew darker','the storm moved closer','the sun appeared'],reasons:['the weather was changing','a storm was nearby','the air had cooled']},
'outdoors':{subjects:['the hikers','Niko','our group'],actions:['followed the narrow trail','crossed the wooden bridge','stopped to study a tiny flower'],places:['near the stream','under the tall trees','beside the rocky hill'],events:['the trail turned uphill','they reached the lookout','a bird called nearby'],reasons:['they wanted a closer look','the path became steep','everyone needed a short rest']},
'sports':{subjects:['the soccer team','Malia','the goalie'],actions:['passed the ball quickly','raced toward the goal','caught the bouncing ball'],places:['near the sideline','across the field','beside the goal'],events:['the game began','the coach called time','the final whistle blew'],reasons:['a teammate was open','the score was tied','they had one last chance']},
'food':{subjects:['Dad','the cook','Ana'],actions:['mixed the pancake batter','cut the fruit into small pieces','carried the warm bread to the table'],places:['in the kitchen','beside the counter','near the picnic table'],events:['breakfast began','the timer beeped','the guests arrived'],reasons:['everyone was hungry','the food was almost ready','the recipe needed one more step']},
'neighborhood':{subjects:['the mail carrier','two neighbors','Keahi'],actions:['walked past the corner store','waved from across the street','rolled the recycling bin to the curb'],places:['near the crosswalk','beside the blue house','at the end of the block'],events:['the school bus arrived','the streetlight changed','a bicycle bell rang'],reasons:['traffic was moving again','the delivery was finished','it was time to head home']},
'nature':{subjects:['a monarch butterfly','the tiny seedling','three small crabs'],actions:['rested on a yellow flower','bent toward the sunlight','crawled between the wet rocks'],places:['near the tide pool','beside the garden path','under a broad leaf'],events:['the tide moved out','the sun warmed the ground','a shadow passed overhead'],reasons:['the rocks were still wet','the flower held fresh nectar','the soil had plenty of water']},
'imaginative':{subjects:['the purple robot','a tiny dragon','the moon explorer'],actions:['rolled across the silver bridge','hid a glowing key','floated past the quiet crater'],places:['inside the glass castle','beside the rocket','under a striped cloud'],events:['the clock chimed twelve','the secret door opened','a star flashed brightly'],reasons:['the mission had begun','someone was following close behind','the map showed a hidden path']},
'transportation':{subjects:['the city bus','a red canoe','the small delivery truck'],actions:['turned slowly at the corner','glided across the calm water','stopped beside the market'],places:['near the bus stop','beside the dock','at the busy intersection'],events:['the light turned green','the wind became calm','the driver checked the map'],reasons:['passengers were waiting','the channel was finally clear','the next stop was nearby']}
};
const WIN_SENTENCE_STRUCTURES=['SIMPLE','TIME','LOCATION','COMPOUND','BECAUSE','WHEN','AFTER','DIALOGUE'];
function winMaterialPatternHistory(){return store.get('winMaterialPatterns',[])}
function rememberWinMaterialPattern(target,structure,theme,length,pattern=''){const h=winMaterialPatternHistory();h.unshift({target,structure,theme,length,pattern});store.set('winMaterialPatterns',h.slice(0,24))}
function chooseWinMaterialCombo(target,pattern=''){const recent=winMaterialPatternHistory().filter(x=>x.target===target).slice(0,8);let combos=[];for(const theme of Object.keys(WIN_MATERIAL_THEMES))for(const structure of WIN_SENTENCE_STRUCTURES)combos.push({theme,structure});combos=shuffle(combos);const choice=combos.find(c=>!recent.some(r=>r.theme===c.theme&&r.structure===c.structure&&(!pattern||r.pattern===pattern)))||combos[0];return choice}
function generatedSentence(target='FLUENCY',forcedPattern=''){const combo=chooseWinMaterialCombo(target,forcedPattern),d=WIN_MATERIAL_THEMES[combo.theme];const subject=pick(d.subjects),action=pick(d.actions),place=pick(d.places),event=pick(d.events),reason=pick(d.reasons);let chunks=[];switch(combo.structure){
case 'SIMPLE':chunks=[subject,action];break;
case 'TIME':chunks=[pick(['This morning','After lunch','Before dinner','Late in the afternoon']),subject,action];break;
case 'LOCATION':chunks=[place[0].toUpperCase()+place.slice(1),subject,action];break;
case 'COMPOUND':chunks=[subject,action+' and '+pick(d.actions.filter(x=>x!==action))];break;
case 'BECAUSE':chunks=[subject,action,'because '+reason];break;
case 'WHEN':chunks=['When '+event,subject,action];break;
case 'AFTER':chunks=['After '+event,subject,action];break;
default:chunks=[pick(['“Look over here!”','“I found it!”','“Ready to go?”']),subject+' called',place];break}
const plain=chunks.join(' ').replace(/\s+/g,' ').trim()+'.';const phrased=chunks.join(' / ').replace(/\s+/g,' ').trim()+'.';const length=plain.length<55?'short':plain.length<85?'medium':'long';rememberWinMaterialPattern(target,combo.structure,combo.theme,length,forcedPattern);return{plain,phrased,theme:combo.theme,structure:combo.structure,length}}
function controlledPhonics(level){if(level==='FOUNDATION')return{label:'short a CVC',words:['map','sat','cat','jam','hat','ram','tap','van','bag','cap'],phrases:['a fat cat','the tan ram','a red cap','the jam pan'],sentences:['Sam has a tan cap.','The cat sat on the mat.','A ram can tap the bag.','Pam has jam in a pan.','The van had a flat tire.']};if(level==='BRIDGE')return{label:'sh',words:['ship','shop','fish','rush','shut','dish','shell','shed','wish','cash'],phrases:['the fish','a shut shop','rush the ship','a red shell'],sentences:['The fish can rush past.','Shay shut the shop.','I wish for a shell.','The ship had a red shell.','Josh can rush to the shed.']};return{label:'ch',words:['chat','chin','chop','much','rich','such','chip','chest','lunch','bench'],phrases:['much chat','a rich lunch','chop it','the chip'],sentences:['Chad can chop the yam.','We chat at lunch.','The chip fell by the bench.','The rich child had lunch.','Chad sat on the bench.']}}
function badPhraseVersion(sentence){const words=sentence.replace(/[.,!?]/g,'').split(/\s+/);if(words.length<6)return words.slice(0,2).join(' ')+' / '+words.slice(2).join(' ')+'.';const a=rand(1,2),b=rand(Math.max(a+2,3),Math.min(words.length-2,5));return words.slice(0,a).join(' ')+' / '+words.slice(a,b).join(' ')+' / '+words.slice(b).join(' ')+'.'}
