function generatedMiniPassage(){const options=[
()=>{const name=pick(['Mia','Kai','Nia','Luca']);const item=pick(['shiny shell','smooth stone','bright feather']);const place=pick(['near the tide pool','beside the garden path','under the playground tree']);return{passage:`${name} found a ${item} ${place}. ${name} picked it up and looked closely at its colors. Then ${name} showed it to a friend before putting it back.`,questions:[`What did ${name} find?`,`What did ${name} do after looking closely?`,`Why do you think ${name} put it back? Use one detail from the passage.`]}} ,
()=>{const name=pick(['Ari','Maya','Noah','Lena']);const task=pick(['build a tall block tower','finish a puzzle','carry a box of books']);return{passage:`${name} tried to ${task}, but the first attempt did not work. ${name} stopped, changed the plan, and tried again. This time the job was finished successfully.`,questions:[`What problem did ${name} have?`,`What did ${name} change?`,`Which sentence shows that the second attempt worked?`]}} ,
()=>{const animal=pick(['small gecko','green frog','tiny crab','brown bird']);const place=pick(['warm rock','wet leaf','shallow puddle','low branch']);return{passage:`A ${animal} rested on a ${place}. A sudden sound made the animal move quickly to a safer spot. A moment later, it peeked out and became still again.`,questions:[`Where did the animal rest at first?`,`What made it move?`,`What happened after it reached a safer spot?`]}} ,
()=>{const name=pick(['Malia','Jonah','Lea','Ben']);const weather=pick(['dark clouds','strong wind','steady rain']);return{passage:`${name} noticed ${weather} outside before leaving home. ${name} grabbed the right gear and headed toward the bus stop. When the weather changed on the way, ${name} was ready.`,questions:[`What did ${name} notice?`,`What did ${name} do before leaving?`,`Why was ${name} ready when the weather changed?`]}} ,
()=>{const name=pick(['Ana','Micah','Sora','Eli']);const food=pick(['fruit salad','sandwiches','pancakes']);return{passage:`${name} helped make ${food} for the family. First, ${name} gathered the ingredients and checked what was needed. After the food was ready, everyone carried it to the table together.`,questions:[`What was ${name} helping make?`,`What happened first?`,`What happened after the food was ready?`]}}
];const x=pick(options)();return x}
function winReadingTeachingMaterial(skill,level,steps){const mk=(i,instruction,examples,note='')=>({title:steps[i]?.title||`STEP ${i+1}`,time:steps[i]?.time||'',instruction,examples,note});const phon=controlledPhonics(level);switch(skill){
case 'PHONOLOGICAL AWARENESS':{const words=level==='FOUNDATION'?['sunset','rainbow','cupcake','toothbrush','playground']:['map','sun','fish','rug','ship'];return [mk(0,'Say each item aloud. Keep this oral.',words.map(w=>level==='FOUNDATION'?`Blend or split: ${w}`:`Blend or segment: ${w}`)),mk(1,'Model one, then let students manipulate the rest.',level==='FOUNDATION'?['sun-set → sunset','rain-bow → rainbow','cup-cake → cupcake','tooth-brush → toothbrush']:['/m/ /a/ /p/ → map','/s/ /u/ /n/ → sun','/f/ /i/ /sh/ → fish','/r/ /u/ /g/ → rug']),mk(2,'Try these together.',words.slice(0,4).map(w=>`Say the parts/sounds in “${w}.”`)),mk(3,'Change or remove one sound/part.',level==='FOUNDATION'?['sunset without sun → set','cupcake without cup → cake','rainbow without rain → bow','playground without play → ground']:['map: /m/→/s/ = sap','sun: /s/→/r/ = run','rug: /r/→/b/ = bug','fish: change /f/ to /d/ → dish']),mk(4,'Fresh check.',[level==='FOUNDATION'?'Blend “rain-bow.”':'Blend /ch/ /i/ /p/.',level==='FOUNDATION'?'Split “table.”':'Segment “shop.”'])]}
case 'LETTER / SOUND':{const pairs=[['m','/m/','map'],['s','/s/','sun'],['f','/f/','fish'],['r','/r/','rug'],['t','/t/','top']];return [mk(0,'Say the sound, not the letter name.',pairs.map(x=>`${x[0]} → ${x[1]}`)),mk(1,'Connect the sound to a word.',pairs.map(x=>`${x[0]} as in ${x[2]}`)),mk(2,'Contrast two sounds.',pairs.slice(0,4).map((x,i)=>`${x[0]} / ${pairs[(i+1)%pairs.length][0]}: which starts “${x[2]}”?`)),mk(3,'Read a tiny controlled set.',pairs.map(x=>x[2])),mk(4,'Fresh check.',shuffle(pairs).slice(0,3).map(x=>`What sound? ${x[0]}`))]}
case 'BLENDING':{const words=shuffle(phon.words).slice(0,8);return [mk(0,`Stretch and blend ${phon.label} words.`,words.slice(0,5)),mk(1,'Use this word chain. Change only one sound when possible.',words.slice(0,5).map((w,i)=>i?`${words[i-1]} → ${w}`:w)),mk(2,'Read these short phrases.',shuffle(phon.phrases).slice(0,4)),mk(3,'Read these controlled sentences.',shuffle(phon.sentences).slice(0,4)),mk(4,'Fresh check words.',words.slice(5).concat(shuffle(phon.words).slice(0,2)))]}
case 'SEGMENTING':{const words=shuffle(controlledPhonics('FOUNDATION').words).slice(0,7);return [mk(0,'Say each word, then tap one time for each sound.',words.slice(0,5)),mk(1,'Push one counter for each phoneme.',words.slice(1,6)),mk(2,'Map sounds to letters.',words.slice(0,5).map(w=>`${w} → ___ sounds → write the letters`)),mk(3,'Change one phoneme and say the new word.', ['map → change /m/ to /s/','sat → change /s/ to /m/','cap → change /c/ to /t/','ram → change /r/ to /j/']),mk(4,'Fresh check.',words.slice(5).map(w=>`Segment “${w}.”`))]}
case 'PHONICS PATTERN':{const words=shuffle(phon.words);return [mk(0,`Read these ${phon.label} words.`,words.slice(0,5)),mk(1,'Notice and name the target spelling pattern.',words.slice(2,7).map(w=>`${w} — underline the ${phon.label} part`)),mk(2,'Read these phrases.',shuffle(phon.phrases).slice(0,4)),mk(3,'Read these controlled sentences.',shuffle(phon.sentences).slice(0,3)),mk(4,'Fresh read/spell check.',words.slice(7).concat(words.slice(0,2)).slice(0,4))]}
case 'WORD READING':{const words=shuffle([...controlledPhonics('FOUNDATION').words,...controlledPhonics('BRIDGE').words]);return [mk(0,'Blend these words accurately.',words.slice(0,5)),mk(1,'Read the stack again with less stopping.',words.slice(0,7)),mk(2,'Read mixed phrases.', ['a red shell','the tan cap','rush the ship','the fish can swim','a small rug']),mk(3,'Read short sentences.',[generatedSentence('WORD READING').plain,generatedSentence('WORD READING').plain,generatedSentence('WORD READING').plain,generatedSentence('WORD READING').plain]),mk(4,'Fresh mixed check.',words.slice(8,13))]}
case 'HIGH-FREQUENCY WORDS':{const h=shuffle(['the','said','have','they','from','were','there','what']);return [mk(0,'Read each word.',h.slice(0,5)),mk(1,'Read in phrases.',h.slice(0,5).map(w=>`${w} ${pick(['kids','books','games','birds','chairs'])}`)),mk(2,'Read in sentences.',h.slice(0,4).map(w=>`${w[0].toUpperCase()+w.slice(1)} ${pick(['kids can play.','books are here.','birds can fly.','games are fun.'])}`)),mk(3,'Map the regular and unexpected parts.',h.slice(0,4).map(w=>`Map “${w}.” Which part is regular? Which part must you remember?`)),mk(4,'Fresh automaticity check.',h.slice(4))]}
case 'FLUENCY':
case 'PHRASE READING':{const target=skill==='FLUENCY'?'FLUENCY':'PHRASE FLUENCY';const a=generatedSentence(target),b=generatedSentence(target),c=generatedSentence(target),d=generatedSentence(target),e=generatedSentence(target),check=generatedSentence(target);return [mk(0,'Teacher reads the first sentence word-by-word, then naturally. Ask which is easier to understand.',[a.plain,b.plain]),mk(1,'Mark natural phrase breaks, then read each sentence.',[b.phrased,c.phrased,d.phrased]),mk(2,'Echo-read, then reread independently.',[a.phrased,b.phrased,c.phrased,d.phrased,e.phrased]),mk(3,'Fix the awkward phrase breaks and explain the better grouping.',[badPhraseVersion(c.plain),badPhraseVersion(d.plain)]),mk(4,'Fresh check: read naturally, then answer the meaning question.',[check.plain,`Meaning question: What happened in the sentence? Tell who or what did something and what they did.`])]}
case 'SHORT COMPREHENSION':{const mini=generatedMiniPassage(),fresh=generatedMiniPassage();return [mk(0,'Read this short ORIGINAL passage.',[mini.passage]),mk(1,'Retell the important information.',[mini.questions[0],'What happened first?','What happened next?']),mk(2,'Find evidence in the passage.',[mini.questions[1],'Read the exact words that support your answer.']),mk(3,'Reason from the text.',[mini.questions[2],'Which detail helped you answer?']),mk(4,'Fresh check.',[fresh.passage,fresh.questions[0],fresh.questions[1]])]}
default:return steps.map((st,i)=>mk(i,'Use these generated examples.',Array.from({length:4},()=>readingWinQuestion(skill,level,Math.min(5,i)).prompt)))}}
function winMathTeachingMaterial(skill,level,steps){return steps.map((st,i)=>{const slots=[Math.min(5,i),Math.min(5,i),Math.min(5,i+1),Math.min(5,i+1)];const seen=new Set(),examples=[];for(let tries=0;tries<16&&examples.length<4;tries++){const q=mathWinQuestion(skill,level,pick(slots)).prompt;if(!seen.has(q)){seen.add(q);examples.push(q)}}while(examples.length<4)examples.push(mathWinQuestion(skill,level,Math.min(5,i)).prompt);return{title:st.title,time:st.time,instruction:i<2?'Teach one slowly, then choose more if needed.':i<4?'Let students try, explain, or compare.':'Use one fresh item as the check.',examples,note:''}})}
function buildWinTeachingMaterial(subject,skill,level,steps){return subject==='MATH'?winMathTeachingMaterial(skill,level,steps):winReadingTeachingMaterial(skill,level,steps)}
function renderWinTeachingMaterial(s){if(!s.teachingMaterial)return'';return `<div class="win-materials"><div class="win-materials-head"><div><div class="eyebrow">TEACHING MATERIAL</div><strong>Use what you need. The question ladder follows.</strong></div><div class="small">Generated for this exact target</div></div><div class="win-materials-grid">${s.teachingMaterial.map(m=>`<div class="win-material-step"><div class="win-material-step-head"><div class="win-material-step-title">${esc(m.title)}</div><div class="win-material-time">${esc(m.time)}</div></div><div class="win-material-instruction">${esc(m.instruction)}</div><ol class="win-material-list">${m.examples.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${m.note?`<div class="win-material-note">${esc(m.note)}</div>`:''}</div>`).join('')}</div></div>`}
function makeWinQuestion(subject,skill,level,slot){const key=`${subject}|${skill}|${level}|${slot}`;return freshWinPrompt(key,()=>subject==='MATH'?mathWinQuestion(skill,level,slot):readingWinQuestion(skill,level,slot))}
function buildWinLadder(subject,skill,level){return Array.from({length:6},(_,i)=>makeWinQuestion(subject,skill,level,i))}
function generateSession(){const s=state.subject==='MATH'?mathSession(state.skill,state.level):readingSession(state.skill,state.level);s.teachingMaterial=buildWinTeachingMaterial(state.subject,state.skill,state.level,s.steps||[]);s.questions=buildWinLadder(state.subject,state.skill,state.level);s.questionIndex=0;return s}
function renderWinQuestion(){const s=state.session;if(!s||!s.questions)return;const i=s.questionIndex||0,q=s.questions[i];$('#winQuestionArea').innerHTML=`<div class="win-question-shell ${i>=3?'quick':''}"><div class="win-question-top"><div><div class="win-question-count">QUESTION ${i+1} OF ${s.questions.length}</div><div class="win-question-stage">${esc(q.stage)}</div></div><div class="small">${i<3?'Teach slowly · discuss thinking':'Ready for faster pacing if they are successful'}</div></div><div class="win-question-prompt">${q.prompt}</div>${q.note?`<div class="win-question-note">${esc(q.note)}</div>`:''}<div class="win-q-controls no-print"><button id="winPrevQ" class="secondary" ${i===0?'disabled':''}>BACK</button><button id="winNextQ" class="primary" ${i===s.questions.length-1?'disabled':''}>NEXT</button><button id="winMoreLike" class="secondary">MORE LIKE THIS</button></div><div class="win-difficulty no-print"><button id="winEasier" class="secondary">EASIER</button><button id="winSame" class="secondary">SAME</button><button id="winHarder" class="secondary">HARDER</button></div><div class="win-difficulty no-print"><button id="winGotIt" class="secondary">✓ GOT IT → NEXT</button><button id="winAlmost" class="secondary">△ ALMOST → SAME</button><button id="winNotYet" class="secondary">✗ NOT YET → EASIER</button></div><div class="win-ladder-hint no-print">These teaching controls change only the current question. The saved session result below remains separate.</div></div>`;
 $('#winPrevQ').onclick=()=>{if(s.questionIndex>0){s.questionIndex--;renderWinQuestion()}};
 $('#winNextQ').onclick=()=>{if(s.questionIndex<s.questions.length-1){s.questionIndex++;renderWinQuestion()}};
 $('#winMoreLike').onclick=()=>replaceWinQuestion(i);
 $('#winSame').onclick=()=>replaceWinQuestion(i);
 $('#winEasier').onclick=()=>replaceWinQuestion(Math.max(0,i-1),i);
 $('#winHarder').onclick=()=>replaceWinQuestion(Math.min(5,i+1),i);
 $('#winGotIt').onclick=()=>{if(s.questionIndex<s.questions.length-1){s.questionIndex++;renderWinQuestion()}};
 $('#winAlmost').onclick=()=>replaceWinQuestion(i);
 $('#winNotYet').onclick=()=>replaceWinQuestion(Math.max(0,i-1),i);
}
function replaceWinQuestion(sourceSlot,targetIndex=null){const s=state.session,idx=targetIndex===null?s.questionIndex:targetIndex;s.questions[idx]=makeWinQuestion(s.subject,s.skill,s.level,sourceSlot);renderWinQuestion()}
function renderSession(){const s=state.session;const names=state.students.join(', ');const d=s.decisions;$('#sessionCard').innerHTML=`<div class="session-head"><div><div class="session-title">ROOM 22 WIN</div><div class="small">${esc(names)}</div></div><div class="minutes">12–15 MINUTES</div></div><div class="target"><div class="eyebrow">TARGET · ${esc(s.level)}</div><strong>${esc(s.target)}</strong><div class="small">${esc(s.std)}</div></div>${renderWinTeachingMaterial(s)}<div id="winQuestionArea"></div><div class="step no-print"><div class="step-title">TEACHER DECISION</div><div class="decision-grid"><div class="decision got"><b>✓ GOT IT</b>${esc(d.got)}</div><div class="decision almost"><b>△ ALMOST</b>${esc(d.almost)}</div><div class="decision notyet"><b>✗ NOT YET</b>${esc(d.notyet)}</div></div></div>`;renderWinQuestion();state.result=null;$('#sessionNote').value='';$$('.result-buttons button').forEach(b=>b.classList.remove('sel'));$('#saveFeedback').textContent='';setScreen('winSession')}
