const WORDS={cvc:['map','sat','fin','hot','rug','lip','bed','sun','jam','pet','fox','cup'],digraph:['ship','chat','thin','whip','rush','chin','shop','math'],blend:['flag','step','frog','clip','drum','spin','plan','grin'],hfw:['the','said','you','was','are','they','have','from']};
function readingSession(skill,level){let target='',std='Reading intervention',steps=[];switch(skill){
case 'PHONOLOGICAL AWARENESS':target=level==='FOUNDATION'?'Hear and manipulate larger sound parts orally':'Blend and segment individual phonemes orally';steps=[activity('LISTEN','2 MIN',level==='FOUNDATION'?'Say “sunset.” “Say it without sun.” Repeat with 3 compound words.':'Say /m/ /a/ /p/. Students blend: map. Repeat with 4 words.'),activity('MODEL','3 MIN',level==='FOUNDATION'?'Clap syllables, then remove or combine one syllable. No print.':'Push one counter for each phoneme in a CVC word. Keep letters out of sight.'),activity('TRY TOGETHER','4 MIN',level==='FOUNDATION'?'Blend and split 5 one- or two-syllable words orally.':'Blend/segment: sun, lip, map, bed, fox.'),activity('QUICK GAME','3 MIN','Robot talk: teacher says sound parts; students say the whole word. Students take one teacher turn.'),activity('CHECK','2 MIN',level==='FOUNDATION'?'Blend “rain-bow” and split “table.”':'Blend /f/ /i/ /sh/ and segment “rug.”')];break;
case 'LETTER / SOUND':target='Connect common graphemes to their sounds quickly and accurately';steps=[activity('QUICK SOUND','2 MIN','Show 6 known letters. Students give sound, not letter name, unless asked.'),activity('MODEL','3 MIN','Contrast two easily confused sounds or spellings. Mouth position + keyword picture may be used briefly.'),activity('SORT IT','4 MIN','Sort 8 picture/word cards by beginning sound. Keep the contrast set small.'),activity('QUICK GAME','3 MIN','Sound hunt: teacher says a sound; students point to its grapheme from 4 cards.'),activity('CHECK','2 MIN','Show 5 graphemes in mixed order. Student produces the sounds without a picture cue.')];break;
case 'BLENDING':{const list=level==='FOUNDATION'?shuffle(WORDS.cvc).slice(0,6):shuffle([...WORDS.cvc,...WORDS.digraph]).slice(0,6);target=level==='FOUNDATION'?'Blend 2–3 phoneme short-vowel words':'Blend decodable words accurately and with decreasing effort';steps=[activity('SOUND WARM-UP','2 MIN','Teacher says 3 isolated sounds from today’s words. Students repeat and connect them.'),activity('BLEND','3 MIN',list.slice(0,3).map(w=>w.split('').join(' · ')+` → ${w}`).join('<br>'), 'Stretch continuous sounds; avoid adding “uh” to stop sounds.'),activity('CHANGE ONE','4 MIN',level==='FOUNDATION'?'map → mat → sat → sit':'ship → shop; thin → chin; chat → chap. Read after each change.'),activity('READ IT','3 MIN',`Read: “${pick(['The cat sat on the rug.','The fish is in the shop.','Sam can fix the lid.'])}”`),activity('CHECK','2 MIN',list.slice(3).join(' · ')+' — three fresh words, no teacher blending first.')];break}
case 'SEGMENTING':target='Segment spoken words into individual phonemes and map the sound sequence';steps=[activity('SAY IT','2 MIN','Teacher says 4 short words. Students repeat normally.'),activity('PUSH IT','3 MIN','For each word, push one counter for each sound. Count sounds only after segmenting.'),activity('TRY TOGETHER','4 MIN',shuffle(WORDS.cvc).slice(0,5).join(' · ')+' — segment orally, then optionally map sounds to letters.'),activity('CHANGE ONE','3 MIN','Change one phoneme: map → mat → sat. Students say which sound changed.'),activity('CHECK','2 MIN','Segment two fresh CVC words independently. If ready, write the graphemes after segmenting.')];break;
case 'PHONICS PATTERN':{const pattern=level==='FOUNDATION'?'short vowels in CVC words':'common digraphs (sh, ch, th)';const list=level==='FOUNDATION'?shuffle(WORDS.cvc).slice(0,6):shuffle(WORDS.digraph).slice(0,6);target=`Read words with ${pattern}`;steps=[activity('NOTICE','2 MIN',`Show 3 words: ${list.slice(0,3).join(', ')}. “What spelling pattern is doing the important work?”`),activity('MODEL','3 MIN','Map one word sound-by-sound, then blend through the whole word.'),activity('SORT / READ','4 MIN',`${list.join(' · ')} — read, then sort by vowel or digraph.`),activity('READ IT','3 MIN',level==='FOUNDATION'?'“The fox can sit on the rug.”':'“The fish can rush to the shop.”'),activity('CHECK','2 MIN','Read 3 fresh words with the same pattern, then spell one from dictation.')];break}
case 'WORD READING':{const list=shuffle([...WORDS.cvc,...WORDS.digraph]).slice(0,8);target='Read controlled decodable words accurately, then reread for automaticity';steps=[activity('MAP ONE','2 MIN',`Map and blend: ${list[0]}.`),activity('READ','3 MIN',list.slice(1,5).join(' · ')),activity('MIX IT','4 MIN','Mix known patterns instead of drilling one visual pattern only. Student names the sound-spelling move when stuck.'),activity('QUICK GAME','3 MIN','Beat your own accuracy: read the same 6-word stack twice, aiming for smoother reading without guessing.'),activity('CHECK','2 MIN',list.slice(5).join(' · ')+' — fresh mixed words.')];break}
case 'HIGH-FREQUENCY WORDS':{const list=shuffle(WORDS.hfw).slice(0,4);target='Read a small set of high-frequency words accurately and map the regular/irregular parts';steps=[activity('HEAR / MAP','2 MIN',`Say “${list[0]}.” Stretch the sounds you can hear and match regular spellings.`),activity('NOTICE','3 MIN',`Words: ${list.join(', ')}. Mark the part that must be remembered if it is not fully regular.`),activity('READ IT','4 MIN',list.map(w=>`Read: ${w}`).join(' · ')+' Then mix the order.'),activity('IN A SENTENCE','3 MIN',`Read: “${pick(['You have the red cup.','They said the bus was here.','The dogs are from the park.'])}”`),activity('CHECK','2 MIN','Read the 4 target words from a mixed stack without picture cues.')];break}
case 'FLUENCY':target='Read a short controlled passage accurately, smoothly, and with attention to meaning';steps=[activity('PREVIEW','2 MIN','Preview 3 potentially tricky words. Decode them before reading the passage.'),activity('ECHO READ','3 MIN','Teacher reads one sentence with natural phrasing. Students echo once.'),activity('REPEATED READ','4 MIN','Read the same short 3–4 sentence original passage twice. First goal: accuracy. Second goal: smoother phrasing.'),activity('MEANING CHECK','3 MIN','Ask one literal question so fluency stays connected to meaning.'),activity('CHECK','2 MIN','Student reads one fresh sentence independently. Note accuracy, phrasing, and whether meaning survived.')];break;
case 'PHRASE READING':target='Read in meaningful phrases instead of word-by-word';steps=[activity('HEAR IT','2 MIN','Teacher reads one sentence twice: choppy, then phrased. “Which was easier to understand?”'),activity('MARK IT','3 MIN','Mark phrase breaks in: “After lunch / the small dog / ran to the gate.”'),activity('ECHO / READ','4 MIN','Echo each phrase, then reread the full sentence. Repeat with 3 sentences.'),activity('MIX IT','3 MIN','Give one sentence with silly phrase breaks. Students fix them and explain why.'),activity('CHECK','2 MIN','Read one new sentence with natural phrase groups and answer a quick meaning question.')];break;
case 'SHORT COMPREHENSION':target='Read or hear a short original text and identify key information with evidence';steps=[activity('READ','2 MIN','“Mia found a tiny crab near a tide pool. She watched it hide under a rock, then called her brother over to see it.”'),activity('RETELL','3 MIN','“Who was the text about? What happened first? What happened next?”'),activity('FIND IT','4 MIN','“Why did Mia call her brother?” Student points to or repeats the part that supports the answer.'),activity('CHANGE ONE','3 MIN','Change one detail orally. “If the crab ran into the water instead, what part of our retell changes?”'),activity('CHECK','2 MIN','Read one new 2-sentence text and answer one who/what question plus one why question supported by the text.')];break;
default:target=skill;steps=[activity('WARM-UP','2 MIN','Activate the exact prerequisite.'),activity('MODEL','3 MIN','Model one concise example.'),activity('TRY TOGETHER','4 MIN','Practice 3–5 controlled examples.'),activity('QUICK GAME','3 MIN','Use a fast sort, match, or change-one routine.'),activity('CHECK','2 MIN','Give 2–3 fresh examples independently.')];}
return{subject:'READING',skill,level,target,std,steps,decisions:decision(skill,level)}}
function winQ(stage,slot,prompt,note=''){return{stage,slot,prompt,note}}
const WIN_STAGES=['ENTRY','ENTRY / PRACTICE','PRACTICE','APPLY','REASON','CHALLENGE'];
function clampWinSlot(n){return Math.max(0,Math.min(5,n))}
function freshWinPrompt(key,make){let recent=[];try{recent=JSON.parse(localStorage.getItem('room22_win_recent_questions')||'[]')}catch(e){}let q=null;for(let i=0;i<6;i++){q=make();if(!recent.some(x=>x.key===key&&x.prompt===q.prompt))break}recent.unshift({key,prompt:q.prompt});recent=recent.slice(0,30);localStorage.setItem('room22_win_recent_questions',JSON.stringify(recent));return q}
