function mathWinQuestion(skill,level,slot){slot=clampWinSlot(slot);const stage=WIN_STAGES[slot];const two=()=>rand(21,89), teen=()=>rand(11,19);let p='',note='';
 switch(skill){
 case 'COUNTING / QUANTITY':{const n=level==='FOUNDATION'?rand(8,18):rand(22,48);p=[`Count a collection of ${n}. How will you keep track so you count every object once?`,`Organize ${n} objects so another person can tell how many without recounting every one.`,`Show ${n} in two different organized arrangements. What stayed the same?`,`Someone counted ${n} objects by making groups. What grouping would make the count fastest? Explain.`,`Two students organized the same ${n} objects differently. How could both arrangements still show ${n}?`,`Design THREE ways to organize ${n} objects. Which representation makes the quantity easiest to see? Defend your choice.`][slot];break}
 case 'SUBITIZING':{const n=slot<2?rand(5,8):rand(7,12);p=[`Look quickly at a pattern showing ${n}. How many do you see without counting one-by-one?`,`Show ${n} as two easy-to-see parts.`,`Show ${n} a different way. What parts do you see now?`,`Which is easier to see quickly: ${n} as 5 + ${n-5}, or another split? Explain.`,`A student says a dot pattern for ${n} must be counted one dot at a time. Convince them otherwise.`,`Create TWO dot patterns for ${n} that make the total easy to see. Explain the parts in each.`][slot];break}
 case 'COMPOSE / DECOMPOSE':{const n=level==='FOUNDATION'?rand(7,10):rand(12,20),a=rand(2,n-3);p=[`${n} = ${a} + ___`,`Show ${n} as two parts in a different way.`,`Write THREE addition equations that equal ${n}.`,`If ${n} is split into ${a+1} and another part, what is missing? Explain how you know.`,`A student says ${a} + ${n-a} is the only way to break apart ${n}. Do you agree?`,`Find FOUR different decompositions of ${n}. Put them in an order that shows a pattern.`][slot];break}
 case 'MAKE 10':{const a=rand(3,9),partner=10-a,d1=partner===1?3:partner-1,d2=partner>=8?partner-2:partner+1,b=rand(6,9);let extra=rand(4,8);while(b+extra<=10)extra=rand(4,8);p=[`${a} + ___ = 10`,`Which pair makes 10? ${a} + ${partner}, ${a} + ${d1}, or ${a} + ${d2}?`,`You have ${b}. How many more makes 10? Show it on a ten-frame or with a quick sketch.`,`Solve ${b} + ${extra} by making 10 first. Show what you moved or broke apart.`,`Two students solve ${b} + ${extra}. One makes 10 first. One counts on. Which strategy is more efficient here? Why?`,`A student says ${b} + ${extra} can’t use make-10 because neither addend is 10. Convince them or correct them.`][slot];break}
 case 'TEEN NUMBERS':{const n=teen();p=[`${n} = 10 + ___`,`Build ${n} as one ten and some ones.`,`Write ${n} in THREE forms: numeral, tens/ones, and an equation.`,`If you trade the ten in ${n} for ones, how many loose ones would you have?`,`A student says the 1 in ${n} is worth 1. Explain the mistake using one ten and ${n%10} ones.`,`Represent ${n} in TWO different ways without changing its value. Prove both equal ${n}.`][slot];break}
 case 'TENS + ONES':{const n=rand(24,89),t=Math.floor(n/10),o=n%10;p=[`${n} = ___ tens and ___ ones`,`${t} tens and ${o} ones = ___`,`Write ${n} as ${t*10} + ___.`,`Is ${t-1} tens and ${o+10} ones equal to ${n}? Explain.`,`A student says ${n} can only be shown as ${t} tens and ${o} ones. Do you agree? Why?`,`Find THREE different tens-and-ones representations of ${n}. Prove they are equivalent.`][slot];break}
 case 'PLACE VALUE':{const n=rand(21,98),t=Math.floor(n/10),o=n%10;p=[`In ${n}, what value does the digit ${t} have?`,`Represent ${n} as tens, ones, and expanded form.`,`What changes if one ten in ${n} is traded for 10 ones? What stays the same?`,`Which representation is equal to ${n}: ${t-1} tens and ${o+10} ones, or ${t} tens and ${Math.max(0,o-1)} ones? Explain.`,`A student says the ${t} in ${n} is worth ${t}. Explain the mistake.`,`Create a number where the digit ${t} has a DIFFERENT value than it has in ${n}. Explain why its value changed.`][slot];break}
 case 'COMPARE NUMBERS':{let a=two(),b=two();while(a===b)b=two();p=[`Which is greater: ${a} or ${b}?`,`Compare ${a} and ${b} using tens first, then ones if needed.`,`Choose <, >, or = : ${a} ___ ${b}. Explain your choice.`,`Without building both numbers, how can place value prove which is greater: ${a} or ${b}?`,`A student says the number with the larger ones digit is always greater. Use ${a} and ${b} to test the claim.`,`Make a two-digit number that is greater than ${Math.min(a,b)} but less than ${Math.max(a,b)}. Find more than one if you can.`][slot];break}
 case 'HUNDRED CHART':{const n=rand(22,78);p=[`On a hundred chart, what number is directly below ${n}?`,`What are the numbers directly left and right of ${n}?`,`Start at ${n}. Move +10, then -1. Where do you land?`,`A hidden chart square is 10 more than ${n} and 1 less than another number. What numbers could be around it?`,`A student moves from ${n} to ${n+10} by counting ten individual squares to the right. What should they notice instead?`,`Create a 3 × 3 hundred-chart window with ${n} in the center. Fill every missing number and explain the pattern.`][slot];break}
 case 'NUMBER LINE':{const a=rand(3,14),b=rand(a+3,20);p=[`Place ${a} on a number line from 0 to 20. What benchmark helps you?`,`Show a jump from ${a} to ${b}. How big is the jump?`,`Start at ${a}. Make two jumps that land on ${b}.`,`Which route from ${a} to ${b} is easier to see: one jump or two useful jumps? Explain.`,`A student places ${b} closer to 10 than ${a}. Could that be correct? Use the number line to justify.`,`Create TWO different jump paths from ${a} to ${b} that have the same total distance. Prove they match.`][slot];break}
 case 'ADDITION WITHIN 20':{const a=rand(5,9),b=rand(3,9),sum=a+b;p=[`${a} + ${b} = ___`,`Show ${a} + ${b} with a drawing, fingers, counters, or a ten-frame.`,`Solve ${a} + ${b} using a strategy you can explain.`,`___ + ${b} = ${sum}. How can the known total help?`,`Compare two strategies for ${a} + ${b}: make ten and count on. Which is more efficient here?`,`A student says ${a} + ${b} = ${sum+1}. Find the mistake and prove the correct sum in TWO ways.`][slot];break}
 case 'SUBTRACTION WITHIN 20':{const total=rand(11,19),take=rand(3,total-5),left=total-take;p=[`${total} - ${take} = ___`,`Show ${total} - ${take} with a drawing, counters, or jumps.`,`Think addition: ${take} + ___ = ${total}. How does that help solve the subtraction?`,`___ - ${take} = ${left}. What number must be missing?`,`Compare taking away and finding the missing part for ${total} - ${take}. Which is easier here?`,`A student says ${total} - ${take} = ${left+2}. Prove the correct difference without only recounting everything.`][slot];break}
 case 'ADDITION WITHIN 100':{const a=rand(22,69),tens=rand(1,3)*10,b=slot<3?tens:rand(11,29),sum=a+b<=99?a+b:a-(10)+b;p=[`${a} + ${tens} = ___`,`Break ${a} into tens and ones. Add ${tens}. What changes?`,`Solve ${a} + ${b} by adding tens and ones. Show your strategy.`,`Find a second strategy for ${a} + ${b}.`,`Two students solve ${a} + ${b} differently. What must both strategies preserve about tens and ones?`,`A student says ${a} + ${b} = ${Math.max(0,(a+b)-10)}. Explain the place-value mistake and prove the correct sum.`][slot];break}
 case 'SUBTRACTION WITHIN 100':{const a=rand(45,89),tens=rand(1,3)*10,b=slot<3?tens:rand(11,29);const safe=b<a?b:11;p=[`${a} - ${tens} = ___`,`Break ${a} into tens and ones. Subtract ${tens}. What changes?`,`Solve ${a} - ${safe} using tens and ones.`,`Show a second way to solve ${a} - ${safe}.`,`Which strategy for ${a} - ${safe} makes the place-value change easiest to see? Why?`,`A student subtracts the ones correctly but forgets to change the tens in ${a} - ${safe}. Explain the mistake and repair it.`][slot];break}
 case 'MISSING PART':{const total=rand(10,20),part=rand(2,total-3),missing=total-part;p=[`${part} + ___ = ${total}`,`___ + ${part} = ${total}`,`${total} - ___ = ${part}`,`Write a short part-part-whole story for ${part} + ___ = ${total}.`,`A student says the blank in ${part} + ___ = ${total} should be ${total}. Explain the mistake.`,`Write THREE different equations that all show the same missing part ${missing} connected to total ${total}.`][slot];break}
 case 'WORD PROBLEMS':{const start=rand(7,15),change=rand(3,8),end=start+change;p=[`There are ${start} shells. ${change} more are added. How many shells are there now?`,`There are ${end} shells. ${change} are taken away. How many remain?`,`There are ${start} shells. Some more arrive. Now there are ${end}. How many arrived?`,`Draw or write an equation for a story where ${start} changes to ${end}. What is unknown?`,`Two students choose different operations for the same story. What words or quantities should they examine before deciding?`,`Write your own add-to or take-from story using ${start}, ${change}, and ${end}. Hide a DIFFERENT part than the first problem did.`][slot];break}
 case 'ODD / EVEN':{const n=rand(12,38);p=[`Is ${n} odd or even?`,`Show ${n} as pairs. Is anything left over?`,`Write ${n} as two equal addends if you can. What does that tell you?`,`Without drawing every object, how can you decide whether ${n+2} has the same odd/even type as ${n}?`,`A student says every number ending in 2 is odd because 2 is an odd-looking shape. How would you prove the real rule?`,`Find THREE even numbers and THREE odd numbers between ${Math.max(1,n-6)} and ${n+6}. Explain the pattern you used.`][slot];break}
 case 'SKIP COUNTING':{const by=pick([2,5,10]),start=by===10?10:by;p=[`Skip-count by ${by}: ${start}, ${start+by}, ___, ___, ___.`,`Build ${rand(3,5)} equal groups of ${by}. How many altogether?`,`How does skip-counting by ${by} connect to equal groups?`,`Start at ${start+by}. Continue the pattern by ${by}. What changes each step?`,`A student skips a number while counting by ${by}. How could equal groups help catch the mistake?`,`Create a skip-counting clue whose answer is ${by*rand(4,8)}. Let the group solve your mystery.`][slot];break}
 default:p=[`Show what you know about ${skill.toLowerCase()}.`,`Try another example of ${skill.toLowerCase()} and explain your thinking.`,`Represent the same idea in a second way.`,`Apply ${skill.toLowerCase()} to a new example.`,`Explain or compare two possible approaches.`,`Create an example that proves you understand ${skill.toLowerCase()}.`][slot];
 }
 return winQ(stage,slot,p,note)}
