(function(){
  const B=window.PRAXIS_BLUEPRINT, Q=window.PRAXIS_QUESTIONS;
  const app=document.getElementById('app'), timerEl=document.getElementById('timer'), metaEl=document.getElementById('sessionMeta');
  const letters=['A','B','C','D','E','F'];
  const STORE='praxis5001-study-v1';
  let data=load(), session=null, tick=null;
  function load(){try{return JSON.parse(localStorage.getItem(STORE))||fresh()}catch{return fresh()}}
  function fresh(){return {attempts:[], recentFingerprints:[], settings:{reviewMode:'instant',fullMode:'study'}, version:2}}
  function save(){localStorage.setItem(STORE,JSON.stringify(data))}
  function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function btn(label,fn,cls='action'){const b=document.createElement('button');b.className=cls;b.textContent=label;b.onclick=fn;return b}
  document.getElementById('homeBtn').onclick=home;
  function clearTimer(){if(tick)clearInterval(tick);tick=null;timerEl.textContent='';timerEl.className=''}
  function home(){clearTimer();session=null;metaEl.textContent='';app.innerHTML='';
    const hero=document.createElement('section');hero.className='hero';hero.innerHTML=`<div class="mode-kicker">LOCAL STUDY ENGINE</div><h1>PRAXIS 5001</h1><p>Original local practice built around the official ETS content blueprint. Train weak skills, run harder mock sets, review mistakes, and keep your results on this device.</p>`;app.append(hero);
    const g=document.createElement('div');g.className='grid home-actions';
    [['STUDY',chooseStudy,'Browse compact topic guides and drill a topic.'],['PRACTICE',()=>chooseSubject('practice'),'Quick sets, custom sets, instant review or test mode.'],['FULL TEST',()=>chooseSubject('full'),'Run a full official-length subtest simulation.'],['RESULTS',results,'See accuracy, weak areas, history, and missed concepts.']].forEach(([name,fn,desc])=>{const c=document.createElement('button');c.className='card action';c.innerHTML=`<strong>${name}</strong><span>${desc}</span>`;c.onclick=fn;g.append(c)}); app.append(g);
    const p=document.createElement('p');p.className='subtle';p.style.marginTop='22px';p.textContent='All generated questions are original. Practice accuracy is not an ETS scaled-score prediction.';app.append(p);
  }
  function subjects(includeMixed=true){const a=Object.entries(B.config.subtests).map(([k,v])=>[k,`${k} ${v.short}`,`${v.questions} questions • ${v.minutes} minutes`]);if(includeMixed)a.push(['MIXED','MIXED','All four subtests']);return a}
  function chooseSubject(kind,presetSmart=false){clearTimer();app.innerHTML='<h2>Choose a subject</h2>';const g=document.createElement('div');g.className='grid';subjects(true).forEach(([code,name,desc])=>{const c=document.createElement('button');c.className='card action subject';c.innerHTML=`<strong>${name}</strong><span>${desc}</span>`;c.onclick=()=>kind==='full'?configure(code,true):configure(code,false,null,presetSmart);g.append(c)});app.append(g)}
  function chooseStudy(){clearTimer();app.innerHTML='<h2>Study by subject</h2>';const g=document.createElement('div');g.className='grid';subjects(false).forEach(([code,name])=>{const c=document.createElement('button');c.className='card action subject';c.innerHTML=`<strong>${name}</strong><span>${B.topics[code].length} topic guides</span>`;c.onclick=()=>studySubject(code);g.append(c)});app.append(g)}
  function studySubject(code){app.innerHTML=`<h2>${code} ${esc(B.config.subtests[code].name)}</h2><p class="subtle">Official-domain study cards, compressed for review.</p>`;B.config.subtests[code].domains.forEach(d=>{const h=document.createElement('h3');h.textContent=d.name;app.append(h);B.topics[code].filter(t=>t.domain===d.id).forEach(t=>{const c=document.createElement('section');c.className='card study-topic';c.innerHTML=`<h3>${esc(t.name)}</h3><dl><dt>WHAT YOU NEED TO KNOW</dt><dd>${esc(t.know)}</dd><dt>COMMON TRAPS</dt><dd>${esc(t.traps)}</dd><dt>QUICK EXAMPLE</dt><dd>${esc(t.example)}</dd><dt>REMEMBER THIS</dt><dd>${esc(t.remember)}</dd></dl>`;c.append(btn('PRACTICE THIS TOPIC',()=>configure(code,false,t.id),'action secondary'));app.append(c)})})}
  function configure(code,full=false,topic=null,presetSmart=false){clearTimer();app.innerHTML=`<h2>${full?'Full Subtest':'Practice'} • ${code==='MIXED'?'Mixed':code+' '+esc(B.config.subtests[code].name)}</h2>`;const p=document.createElement('section');p.className='panel settings';
    if(full){const fq=code==='MIXED'?245:B.config.subtests[code].questions, fm=code==='MIXED'?275:B.config.subtests[code].minutes;const saved=data.settings.fullMode||'study';p.innerHTML=`<p><strong>${fq} questions</strong> • ${fm} minutes • official category weighting</p><div class="mode-grid"><label class="mode-option"><input type="radio" name="fullMode" value="study" ${saved!=='exam'?'checked':''}><strong>STUDY FULL TEST</strong><span>Full length and timed, with Check Answer feedback after each question. Best for learning.</span></label><label class="mode-option"><input type="radio" name="fullMode" value="exam" ${saved==='exam'?'checked':''}><strong>EXAM SIMULATION</strong><span>Full length and timed. No correctness or explanations until you submit.</span></label></div>`;p.append(btn(code==='MIXED'?'START COMBINED TEST':'START FULL SUBTEST',()=>{const mode=p.querySelector('input[name="fullMode"]:checked').value;data.settings.fullMode=mode;save();startSession({code,count:fq,full:true,simulation:mode==='exam',reviewMode:mode==='exam'?'test':'instant',timerMode:'real',topic})},'action primary'));}
    else {p.innerHTML=`<label>Set length<select id="count"><option value="10">Quick 10</option><option value="20">Quick 20</option><option value="half">Half test</option><option value="full">Full subtest</option><option value="custom">Custom</option></select></label><label id="customWrap" style="display:none">Custom questions<input id="customCount" type="number" min="1" max="245" value="15"></label><label>Review behavior<select id="review"><option value="instant">Instant Review</option><option value="test">Test Mode</option></select></label><label>Timer<select id="timerMode"><option value="untimed">Untimed</option><option value="real">Real subtest time</option><option value="custom">Custom timer</option></select></label><label id="minutesWrap" style="display:none">Minutes<input id="minutes" type="number" min="1" max="300" value="20"></label><label><input id="smart" type="checkbox" style="width:auto" ${presetSmart?'checked':''}> Practice my weak areas</label>`;
      const count=p.querySelector('#count');count.onchange=()=>p.querySelector('#customWrap').style.display=count.value==='custom'?'block':'none';const tm=p.querySelector('#timerMode');tm.onchange=()=>p.querySelector('#minutesWrap').style.display=tm.value==='custom'?'block':'none';
      p.append(btn('START',()=>{let n=count.value;if(n==='half')n=Math.ceil((code==='MIXED'?50:B.config.subtests[code].questions)/2);else if(n==='full')n=code==='MIXED'?60:B.config.subtests[code].questions;else if(n==='custom')n=+p.querySelector('#customCount').value;else n=+n;startSession({code,count:n,full:false,simulation:false,reviewMode:p.querySelector('#review').value,timerMode:tm.value,customMinutes:+p.querySelector('#minutes').value,smart:p.querySelector('#smart').checked,topic})},'action primary'));
    } app.append(p)}
  function weaknessMap(){const out={};function add(k,a){if(!out[k])out[k]={correct:0,attempts:0,accuracy:1};out[k].attempts++;if(a.correct)out[k].correct++;out[k].accuracy=out[k].correct/out[k].attempts}for(const a of data.attempts){add(`${a.subtest}:domain:${a.domain}`,a);add(`${a.subtest}:topic:${a.topic}`,a)}return out}
  function showRuntimeError(err,context='starting the practice set'){clearTimer();session=null;metaEl.textContent='';console.error(err);app.innerHTML=`<section class="panel"><h2>Something broke while ${esc(context)}.</h2><p>The app caught the error instead of leaving a blank screen.</p><pre class="errorbox">${esc(err?.message||String(err))}</pre><div class="buttonrow"><button id="errorHome" class="action primary">BACK TO HOME</button></div></section>`;document.getElementById('errorHome').onclick=home}
  function startSession(opts){try{clearTimer();const recent=data.recentFingerprints.slice(-60);let items;if(opts.code==='MIXED'&&opts.count===245){const parts=[['5002',80],['5003',50],['5004',60],['5005',55]];items=parts.flatMap(([c,n],i)=>Q.session(c,n,{seed:(Date.now()%1000000000)+i*100003,recentFingerprints:recent,weakness:weaknessMap(),smart:opts.smart}));}else{items=Q.session(opts.code,opts.count,{recentFingerprints:recent,weakness:weaknessMap(),smart:opts.smart,topic:opts.topic});}
    if(!Array.isArray(items)||!items.length)throw new Error('No questions were generated for this session.');
    const malformed=items.find(q=>!Q.validateItem(q).ok);
    if(malformed)throw new Error('A malformed question reached the test runner.');
    session={...opts,items,index:0,answers:Array(items.length).fill(null),checkedAnswers:new Set(),flagged:new Set(),guessed:new Set(),start:Date.now(),submitted:false,remaining:null};
    if(opts.timerMode==='real'){const mins=opts.code==='MIXED'?Math.round(275*(opts.count/245)):B.config.subtests[opts.code].minutes*(opts.count/B.config.subtests[opts.code].questions);session.remaining=Math.max(60,Math.round(mins*60));startTimer()}
    else if(opts.timerMode==='custom'){session.remaining=Math.max(60,opts.customMinutes*60);startTimer()}
    renderQuestion()}catch(err){showRuntimeError(err)}}
  function startTimer(){renderTimer();tick=setInterval(()=>{if(!session||session.submitted)return;session.remaining=Math.max(0,session.remaining-1);renderTimer();if(session.remaining===0)submit(true)},1000)}
  function renderTimer(){if(session?.remaining==null){timerEl.textContent='UNTIMED';return}const m=Math.floor(session.remaining/60),s=session.remaining%60;timerEl.textContent=`${m}:${String(s).padStart(2,'0')}`;timerEl.className=session.remaining<=300?'danger':session.remaining<=600?'warn':''}
  function isAnswered(a,q){return q.questionType==='multi-select'?Array.isArray(a)&&a.length>0:q.questionType==='numeric-entry'?a!==null&&a!==undefined&&String(a).trim()!=='':a!==null}
  function correctText(q){if(q.questionType==='multi-select')return q.correctIndices.map(i=>`${letters[i]}. ${q.choices[i]}`).join('; ');if(q.questionType==='numeric-entry')return String(q.correctValue);return `${letters[q.correctIndex]}. ${q.choices[q.correctIndex]}`}
  function answerText(q,a){if(!isAnswered(a,q))return 'Unanswered';if(q.questionType==='multi-select')return a.slice().sort((x,y)=>x-y).map(i=>`${letters[i]}. ${q.choices[i]}`).join('; ');if(q.questionType==='numeric-entry')return String(a);return `${letters[a]}. ${q.choices[a]}`}
  function renderQuestion(){const q=session.items[session.index],chosen=session.answers[session.index],answered=isAnswered(chosen,q),checked=session.checkedAnswers.has(session.index),reveal=session.reviewMode==='instant'&&checked,correct=Q.gradeAnswer(q,chosen);metaEl.textContent=`${session.simulation?'EXAM SIMULATION':session.full?'STUDY FULL TEST':session.reviewMode==='instant'?'PRACTICE + FEEDBACK':'PRACTICE TEST'} • ${q.subtest} • ${session.index+1}/${session.items.length}`;app.innerHTML='';const shell=document.createElement('div');shell.className='question-shell';const main=document.createElement('section');main.className='question-main';main.innerHTML=`${session.full?'':`<div class="badge">${esc(topicName(q.subtest,q.topic))}</div>`}<h2 class="question-title">${esc(q.stem)}</h2>`;
    if(q.questionType==='numeric-entry'){const label=document.createElement('label');label.className='numeric-answer';label.innerHTML='<span>Enter a numeric answer</span>';const input=document.createElement('input');input.type='text';input.inputMode='decimal';input.value=chosen??'';input.placeholder='Numeric answer';input.disabled=reveal;input.onchange=()=>choose(input.value);input.onkeydown=e=>{if(e.key==='Enter'){choose(input.value)}};label.append(input);main.append(label)}
    else q.choices.forEach((c,i)=>{const selected=q.questionType==='multi-select'?Array.isArray(chosen)&&chosen.includes(i):chosen===i;const b=document.createElement('button');b.className='choice'+(selected?' selected':'');if(reveal&&((q.questionType==='multi-select'&&q.correctIndices.includes(i))||(q.questionType!=='multi-select'&&i===q.correctIndex)))b.classList.add('correct');if(reveal&&selected&&q.questionType==='multi-select'&&!q.correctIndices.includes(i))b.classList.add('wrong');if(reveal&&selected&&q.questionType!=='multi-select'&&i!==q.correctIndex)b.classList.add('wrong');b.innerHTML=`<span class="choice-letter">${letters[i]}.</span>${esc(c)}`;b.disabled=reveal;b.onclick=()=>choose(i);main.append(b)});
    if(session.reviewMode==='instant'&&!checked&&answered){main.append(btn('CHECK ANSWER',()=>{session.checkedAnswers.add(session.index);renderQuestion()},'action check-answer'))}
    if(reveal){const f=document.createElement('div');f.className='feedback '+(correct?'good':'bad');f.innerHTML=`<h3>${correct?'Correct':'Not quite'} • Correct answer: ${esc(correctText(q))}</h3><p>${esc(q.explanation)}</p><p class="subtle"><strong>Skill:</strong> ${esc(q.skill)} • <strong>Domain:</strong> ${esc(domainName(q.subtest,q.domain))}</p><p class="answer-locked">Answer locked after feedback.</p>`;main.append(f)}
    const nav=document.createElement('div');nav.className='buttonrow';if(session.index>0)nav.append(btn('PREVIOUS',()=>{session.index--;renderQuestion()}));nav.append(btn(session.flagged.has(session.index)?'UNFLAG':'FLAG FOR REVIEW',()=>{session.flagged.has(session.index)?session.flagged.delete(session.index):session.flagged.add(session.index);renderQuestion()},session.flagged.has(session.index)?'action flagged':'action'));nav.append(btn(session.guessed.has(session.index)?'GUESSED ✓':'I GUESSED',()=>{session.guessed.has(session.index)?session.guessed.delete(session.index):session.guessed.add(session.index);renderQuestion()}));if(session.index<session.items.length-1)nav.append(btn('NEXT',()=>{session.index++;renderQuestion()},'action primary'));else nav.append(btn('SUBMIT',()=>submit(false),'action primary'));main.append(nav);
    const side=document.createElement('aside');side.className='side';const answeredCount=session.items.filter((x,i)=>isAnswered(session.answers[i],x)).length;const info=session.full?'Question format':esc(domainName(q.subtest,q.domain));const detail=session.full?(q.questionType==='multi-select'?'Select all that apply':q.questionType==='numeric-entry'?'Numeric entry':'Select one'):`${esc(q.skill)}<br><span class="subtle">${q.questionType==='multi-select'?'Select all that apply':q.questionType==='numeric-entry'?'Numeric entry':'Select one'}</span>`;side.innerHTML=`<div class="card"><strong>Progress</strong><div class="progressbar"><span style="width:${answeredCount/session.items.length*100}%"></span></div><p>${answeredCount} answered • ${session.items.length-answeredCount} unanswered</p><p>${session.flagged.size} flagged • ${session.guessed.size} guessed</p></div><div class="card"><strong>${info}</strong><p class="subtle">${detail}</p></div>`;shell.append(main,side);app.append(shell)}
  function choose(value){if(session.reviewMode==='instant'&&session.checkedAnswers.has(session.index))return;const q=session.items[session.index];if(q.questionType==='multi-select'){const cur=Array.isArray(session.answers[session.index])?session.answers[session.index].slice():[];const at=cur.indexOf(value);if(at>=0)cur.splice(at,1);else cur.push(value);session.answers[session.index]=cur}else session.answers[session.index]=value;renderQuestion()}
  function submit(auto=false){if(session.submitted)return;const unanswered=session.items.filter((q,i)=>!isAnswered(session.answers[i],q)).length;if(!auto&&unanswered&&session.full&&!confirm(`You still have ${unanswered} unanswered question${unanswered===1?'':'s'}. Submit anyway?`))return;session.submitted=true;clearTimer();const timeUsed=Math.round((Date.now()-session.start)/1000);session.timeUsed=timeUsed;session.items.forEach((q,i)=>{const correct=Q.gradeAnswer(q,session.answers[i]);data.attempts.push({ts:Date.now(),subtest:q.subtest,domain:q.domain,topic:q.topic,skill:q.skill,praxisMethod:q.praxisMethod||'unclassified',mode:session.simulation?'exam-simulation':session.full?'study-full':session.reviewMode==='instant'?'practice-feedback':'practice-test',correct,guessed:session.guessed.has(i),questionId:q.id,fingerprint:q.fingerprint,timeUsed:Math.round(timeUsed/session.items.length)});data.recentFingerprints.push(q.fingerprint)});data.recentFingerprints=data.recentFingerprints.slice(-200);save();showSessionResults()}
  function showSessionResults(filter='all'){const total=session.items.length,correct=session.items.filter((q,i)=>Q.gradeAnswer(q,session.answers[i])).length,pct=Math.round(correct/total*100),unanswered=session.items.filter((q,i)=>!isAnswered(session.answers[i],q)).length;app.innerHTML=`<div class="results-summary"><div class="mode-kicker">SESSION COMPLETE</div><h2>${session.simulation?'Exam Simulation Results':session.full?'Full Test Results':'Practice Results'}</h2></div><div class="stats"><div class="stat"><span>RAW SCORE</span><b>${correct}/${total}</b></div><div class="stat"><span>PRACTICE ACCURACY</span><b>${pct}%</b></div><div class="stat"><span>TIME USED</span><b>${fmtTime(session.timeUsed)}</b></div><div class="stat"><span>UNANSWERED</span><b>${unanswered}</b></div></div><p class="subtle">Practice accuracy is an internal study metric, not an ETS scaled score.</p>`;
    const by={};session.items.forEach((q,i)=>{if(!by[q.domain])by[q.domain]=[0,0];by[q.domain][1]++;if(Q.gradeAnswer(q,session.answers[i]))by[q.domain][0]++});const table=document.createElement('table');table.className='breakdown';table.innerHTML='<tr><th>Domain</th><th>Correct</th><th>Accuracy</th></tr>'+Object.entries(by).map(([d,[c,n]])=>`<tr><td>${esc(domainName(null,d))}</td><td>${c}/${n}</td><td>${Math.round(c/n*100)}%</td></tr>`).join('');app.append(table);
    const methods={};session.items.forEach((q,i)=>{const m=q.praxisMethod||'unclassified';if(!methods[m])methods[m]=[0,0];methods[m][1]++;if(Q.gradeAnswer(q,session.answers[i]))methods[m][0]++});const methodEntries=Object.entries(methods).filter(([,v])=>v[1]>=2).sort((a,b)=>(a[1][0]/a[1][1])-(b[1][0]/b[1][1]));if(methodEntries.length){const mh=document.createElement('h3');mh.textContent='Method signals';app.append(mh);const mt=document.createElement('table');mt.className='breakdown';mt.innerHTML='<tr><th>Praxis method</th><th>Correct</th><th>Accuracy</th></tr>'+methodEntries.map(([m,[c,n]])=>`<tr><td>${esc(m.replace(/-/g,' '))}</td><td>${c}/${n}</td><td>${Math.round(c/n*100)}%</td></tr>`).join('');app.append(mt)}
    const filters=document.createElement('div');filters.className='buttonrow';[['all','ALL'],['missed','MISSED'],['flagged','FLAGGED'],['guessed','GUESSED']].forEach(([v,l])=>filters.append(btn(l,()=>showSessionResults(v),filter===v?'action secondary':'action')));app.append(filters);
    session.items.forEach((q,i)=>{const wrong=!Q.gradeAnswer(q,session.answers[i]);if(filter==='missed'&&!wrong)return;if(filter==='flagged'&&!session.flagged.has(i))return;if(filter==='guessed'&&!session.guessed.has(i))return;const div=document.createElement('div');div.className='review-item';div.innerHTML=`<div class="badge">${esc(topicName(q.subtest,q.topic))}</div><h4>${esc(q.stem)}</h4><p class="answerline"><strong>Your answer:</strong> ${esc(answerText(q,session.answers[i]))}</p><p class="answerline"><strong>Correct answer:</strong> ${esc(correctText(q))}</p><p>${esc(q.explanation)}</p>`;div.append(btn('PRACTICE THIS TOPIC',()=>configure(q.subtest,false,q.topic),'action secondary'));app.append(div)})
  }
  function results(){clearTimer();app.innerHTML='<div class="results-summary"><div class="mode-kicker">YOUR LOCAL DATA</div><h2>Results & Weakness Tracking</h2></div>';if(!data.attempts.length){app.innerHTML+='<div class="empty">No results yet. Take a practice set and this screen will start tracking patterns.</div>';return}const total=data.attempts.length,correct=data.attempts.filter(a=>a.correct).length;app.innerHTML+=`<div class="stats"><div class="stat"><span>ATTEMPTED</span><b>${total}</b></div><div class="stat"><span>CORRECT</span><b>${correct}</b></div><div class="stat"><span>OVERALL PRACTICE</span><b>${Math.round(correct/total*100)}%</b></div><div class="stat"><span>GUESSED</span><b>${data.attempts.filter(a=>a.guessed).length}</b></div></div><p class="subtle">Practice accuracy is a local diagnostic, not an ETS scaled-score prediction. Strong labels require repeated attempts.</p>`;
    const readiness=document.createElement('section');readiness.innerHTML='<h3>Four-subtest practice readiness</h3><p class="subtle">Hawaiʻi licensure uses subtest requirements. These are local study signals only, not ETS score predictions or pass/fail determinations.</p>';const grid=document.createElement('div');grid.className='readiness-grid';for(const code of ['5002','5003','5004','5005']){const arr=data.attempts.filter(a=>a.subtest===code),n=arr.length,c=arr.filter(a=>a.correct).length,acc=n?c/n:0;let signal='INSUFFICIENT DATA';if(n>=20)signal=acc>=.8?'STRONG PRACTICE':acc>=.65?'DEVELOPING':'PRIORITY REVIEW';const card=document.createElement('div');card.className='readiness-card';card.innerHTML=`<strong>${code}</strong><h3>${signal}</h3><p>${n?Math.round(acc*100)+'% across '+n+' attempts':'No attempts yet'}</p>`;grid.append(card)}readiness.append(grid);app.append(readiness);
    const rows=[];for(const [code,cfg] of Object.entries(B.config.subtests)){for(const d of cfg.domains){const arr=data.attempts.filter(a=>a.subtest===code&&a.domain===d.id),n=arr.length,c=arr.filter(a=>a.correct).length;if(!n)continue;const acc=c/n;let label='INSUFFICIENT DATA',cl='';if(n>=5){label=acc>=.8?'STRONG':acc>=.65?'OKAY':'NEEDS WORK';cl=acc>=.8?'strong':acc<.65?'weak':''}rows.push([code,d.name,n,c,Math.round(acc*100),label,cl])}}
    const table=document.createElement('table');table.className='breakdown';table.innerHTML='<tr><th>Subtest / Domain</th><th>Attempts</th><th>Accuracy</th><th>Status</th></tr>'+rows.map(r=>`<tr><td>${r[0]} • ${esc(r[1])}</td><td>${r[2]}</td><td>${r[4]}%</td><td><span class="badge ${r[6]}">${r[5]}</span></td></tr>`).join('');app.append(table);
    const topicRows=[];for(const [code,topics] of Object.entries(B.topics)){for(const t of topics){const arr=data.attempts.filter(a=>a.subtest===code&&a.topic===t.id),n=arr.length;if(n<3)continue;const c=arr.filter(a=>a.correct).length,acc=c/n;let label=n<5?'EARLY SIGNAL':acc>=.8?'STRONG':acc>=.65?'OKAY':'NEEDS WORK';topicRows.push({code,name:t.name,n,acc,label})}}topicRows.sort((a,b)=>a.acc-b.acc||b.n-a.n);if(topicRows.length){const h=document.createElement('h3');h.textContent='Topic signals';app.append(h);const tt=document.createElement('table');tt.className='breakdown';tt.innerHTML='<tr><th>Topic</th><th>Attempts</th><th>Accuracy</th><th>Signal</th></tr>'+topicRows.slice(0,20).map(x=>`<tr><td>${x.code} • ${esc(x.name)}</td><td>${x.n}</td><td>${Math.round(x.acc*100)}%</td><td>${x.label}</td></tr>`).join('');app.append(tt)}
    const allMethods={};for(const a of data.attempts){const m=a.praxisMethod||'unclassified';if(!allMethods[m])allMethods[m]=[0,0];allMethods[m][1]++;if(a.correct)allMethods[m][0]++}const mr=Object.entries(allMethods).filter(([,v])=>v[1]>=5).sort((a,b)=>(a[1][0]/a[1][1])-(b[1][0]/b[1][1])).slice(0,12);if(mr.length){const h=document.createElement('h3');h.textContent='Method signals';app.append(h);const t=document.createElement('table');t.className='breakdown';t.innerHTML='<tr><th>Method</th><th>Attempts</th><th>Accuracy</th></tr>'+mr.map(([m,[c,n]])=>`<tr><td>${esc(m.replace(/-/g,' '))}</td><td>${n}</td><td>${Math.round(c/n*100)}%</td></tr>`).join('');app.append(t)}
    const br=document.createElement('div');br.className='buttonrow';br.append(btn('PRACTICE MY WEAK AREAS',()=>chooseSubject('practice',true),'action primary'),btn('RESET LOCAL RESULTS',()=>{if(confirm('Delete all local Praxis results?')){data=fresh();save();results()}}));app.append(br)}
  function domainName(subtest,id){for(const [code,cfg] of Object.entries(B.config.subtests)){const d=cfg.domains.find(x=>x.id===id);if(d)return d.name}return id}
  function topicName(code,id){return B.topics[code]?.find(t=>t.id===id)?.name||id}
  function fmtTime(s){const m=Math.floor(s/60),ss=s%60;return `${m}:${String(ss).padStart(2,'0')}`}
  home();
})();
