window.PRAXIS_BLUEPRINT = {
  meta: {
    title: 'Praxis Elementary Education: Multiple Subjects (5001)',
    source: 'ETS Praxis 5001 Study Companion',
    sourceUrl: 'https://praxis.ets.org/on/demandware.static/-/Library-Sites-ets-praxisLibrary/default/dw5d326ab0/pdfs/5001.pdf',
    note: 'Blueprint categories and topic summaries are encoded from the official ETS Study Companion. Practice questions are original; external free banks were used only for calibration unless reuse rights were explicit.'
  },
  config: {
    combined: { code:'5001', questions:245, minutes:275 },
    subtests: {
      '5002': { name:'Reading and Language Arts', short:'RLA', questions:80, minutes:90, formats:['selected-response'], domains:[
        {id:'rla-reading', name:'Reading', weight:0.47},
        {id:'rla-writing', name:'Writing, Speaking, and Listening', weight:0.53}
      ]},
      '5003': { name:'Mathematics', short:'Math', questions:50, minutes:65, formats:['selected-response','numeric-entry'], domains:[
        {id:'math-number', name:'Numbers and Operations', weight:0.40},
        {id:'math-algebra', name:'Algebraic Thinking', weight:0.30},
        {id:'math-geo', name:'Geometry and Measurement, Data, Statistics, and Probability', weight:0.30}
      ]},
      '5004': { name:'Social Studies', short:'Social Studies', questions:60, minutes:60, formats:['selected-response'], domains:[
        {id:'ss-us', name:'United States History, Government, and Citizenship', weight:0.45},
        {id:'ss-geo', name:'Geography, Anthropology, and Sociology', weight:0.30},
        {id:'ss-world', name:'World History and Economics', weight:0.25}
      ]},
      '5005': { name:'Science', short:'Science', questions:55, minutes:60, formats:['selected-response'], domains:[
        {id:'sci-earth', name:'Earth Science', weight:1/3},
        {id:'sci-life', name:'Life Science', weight:1/3},
        {id:'sci-physical', name:'Physical Science', weight:1/3}
      ]}
    }
  },
  topics: {
    '5002': [
      {domain:'rla-reading', id:'phonological-awareness', name:'Phonological Awareness', know:'Phonemes, syllables, onsets/rimes, and blending, segmenting, substituting, and deleting sounds.', traps:'Confusing phonological awareness (sound only) with phonics (print-sound relationships).', example:' /m/ /a/ /p/ → map is phoneme blending.', remember:'Phonological awareness can be done with eyes closed.'},
      {domain:'rla-reading', id:'phonics-word-analysis', name:'Phonics & Word Analysis', know:'Letter-sound correspondences, spelling patterns, syllable types, roots, prefixes, suffixes, and decoding.', traps:'Treating a high-frequency irregular word as fully decodable.', example:'In “hoping,” the silent-e pattern helps explain the long o.', remember:'Phonics connects print to sound; morphology connects meaningful word parts.'},
      {domain:'rla-reading', id:'fluency', name:'Fluency', know:'Accuracy, rate, and prosody, plus their relationship to comprehension.', traps:'Equating fluency with reading fast.', example:'A reader with correct phrasing and expression demonstrates prosody.', remember:'Fluency = accurate + appropriately paced + expressive.'},
      {domain:'rla-reading', id:'key-ideas', name:'Key Ideas, Details & Inference', know:'Central idea/theme, details, inference, summary, character/plot, and relationships among ideas/events.', traps:'Choosing a true detail instead of the central idea.', example:'An inference must be supported by text evidence, not merely possible.', remember:'Best inference = text evidence + reasonable conclusion.'},
      {domain:'rla-reading', id:'text-structure', name:'Text Features & Structure', know:'Genre structures, headings/sidebars, cause-effect, compare-contrast, chronology, problem-solution, and how structure supports meaning.', traps:'Confusing topic with structure.', example:'Signal words “because” and “as a result” often indicate cause/effect.', remember:'Ask how the author organized the information.'},
      {domain:'rla-reading', id:'language-vocab', name:'Vocabulary & Language in Text', know:'Context clues, figurative language, tone, word relationships, roots and affixes.', traps:'Picking a dictionary meaning that does not fit the sentence.', example:'“The trail was grueling” can be inferred from details about exhaustion.', remember:'Meaning in context beats memorized definition.'},
      {domain:'rla-writing', id:'writing-types', name:'Writing Types & Purposes', know:'Narrative, informative/explanatory, opinion/argument, purpose, audience, and key components.', traps:'Mistaking evidence-heavy opinion writing for informational writing.', example:'A claim supported by reasons and evidence is argumentative.', remember:'Purpose drives structure and evidence.'},
      {domain:'rla-writing', id:'writing-process', name:'Writing Process & Development', know:'Planning, drafting, revising, editing, organization, cohesion, development, and developmental writing stages.', traps:'Editing grammar when the real problem is weak organization.', example:'Moving a paragraph to improve logical flow is revision.', remember:'Revise ideas/organization; edit conventions.'},
      {domain:'rla-writing', id:'grammar-usage', name:'Grammar, Usage, Mechanics & Spelling', know:'Sentence structure, agreement, pronouns, modifiers, punctuation, capitalization, spelling patterns, and common student errors.', traps:'Choosing a sentence that sounds natural but has an agreement or modifier error.', example:'“Each of the players is ready” uses singular agreement with each.', remember:'Find the grammatical subject, not the nearest noun.'},
      {domain:'rla-writing', id:'research', name:'Research & Source Literacy', know:'Credibility, bias, primary/secondary sources, integrating information, citation, paraphrase, and avoiding plagiarism.', traps:'Assuming a professional-looking website is automatically credible.', example:'A government data table is stronger evidence for a population statistic than an unsourced blog post.', remember:'Check author, evidence, date, purpose, and corroboration.'},
      {domain:'rla-writing', id:'speaking-listening', name:'Speaking & Listening', know:'Oral presentation, verbal/nonverbal elements, active listening, discussion norms, and matching communication to audience/purpose.', traps:'Treating volume alone as effective delivery.', example:'Paraphrasing a speaker before responding demonstrates active listening.', remember:'Effective communication is purposeful, clear, responsive, and audience-aware.'}
    ],
    '5003': [
      {domain:'math-number', id:'place-value', name:'Place Value & Base Ten', know:'Represent, compose/decompose, compare, round, and reason about powers of ten and digit value.', traps:'Confusing a digit with its value.', example:'In 23.12, the 2 in tens is 1,000 times the 2 in hundredths.', remember:'Moving one place left multiplies value by 10.'},
      {domain:'math-number', id:'rational-operations', name:'Operations with Rational Numbers', know:'Whole-number, fraction, and decimal operations; inverse relationships; remainders; strategies and algorithms.', traps:'Assuming multiplication always makes numbers larger.', example:'3 × 1/2 = 1.5, smaller than 3.', remember:'Magnitude depends on the multiplier/divisor.'},
      {domain:'math-number', id:'fractions-decimals', name:'Fractions, Decimals & Percents', know:'Equivalence, comparison, models, unit fractions, decimal relationships, percent, ratio/unit rate where applicable.', traps:'Adding denominators when adding fractions.', example:'1/3 + 1/6 = 1/2 after using a common denominator.', remember:'Fractions name equal-sized parts, so denominators must align for addition.'},
      {domain:'math-number', id:'factors-multiples', name:'Factors, Multiples & Number Properties', know:'Prime/composite, prime factorization, GCF, LCM, divisibility, properties, and reasonableness.', traps:'Mixing up factors and multiples.', example:'12 is a multiple of 3; 3 is a factor of 12.', remember:'Factors divide in; multiples count out.'},
      {domain:'math-number', id:'estimation', name:'Estimation & Reasonableness', know:'Mental math, rounding, benchmark numbers, and checking whether results make sense in context.', traps:'Treating an exact-looking answer as automatically reasonable.', example:'49 × 21 should be near 50 × 20 = 1,000.', remember:'Estimate before trusting the calculator.'},
      {domain:'math-algebra', id:'expressions', name:'Expressions, Equations & Formulas', know:'Translate, evaluate, simplify, use properties, and solve for unknowns.', traps:'Ignoring order of operations or reversing verbal relationships.', example:'“j is twice s” means j = 2s.', remember:'Translate the relationship, not the word order.'},
      {domain:'math-algebra', id:'linear', name:'Linear Equations & Inequalities', know:'Solve multistep equations/inequalities and interpret solutions in equations, tables, graphs, and contexts.', traps:'Forgetting to reverse an inequality when multiplying/dividing by a negative.', example:'-2x > 6 gives x < -3.', remember:'Negative multiplication/division flips the inequality.'},
      {domain:'math-algebra', id:'patterns', name:'Patterns & Relationships', know:'Identify, extend, describe, generate, and generalize numerical or shape patterns.', traps:'Assuming every pattern is additive.', example:'2, 6, 18, 54 is multiplicative ×3.', remember:'Look for operation and position relationship.'},
      {domain:'math-geo', id:'geometry', name:'Geometry', know:'Properties and classification of 2D/3D figures, angle relationships, coordinate reasoning, transformations, area/perimeter/volume.', traps:'Perimeter vs. area; classification that ignores hierarchy.', example:'Every square is a rectangle, but not every rectangle is a square.', remember:'Classification can be inclusive.'},
      {domain:'math-geo', id:'measurement', name:'Measurement & Conversion', know:'Length, area, volume, mass, capacity, time, unit choice, and customary/metric conversions.', traps:'Using a linear conversion factor for area without squaring it.', example:'3 ft = 1 yd, but 9 ft² = 1 yd².', remember:'Dimensions matter when converting units.'},
      {domain:'math-geo', id:'data-statistics', name:'Data & Statistics', know:'Tables/graphs, mean, median, mode, range, scatterplots, and effects of adding/removing values.', traps:'Using mean when an outlier makes median more representative.', example:'A single huge salary can raise the mean without changing the median much.', remember:'Center depends on the shape of the data.'},
      {domain:'math-geo', id:'probability', name:'Probability', know:'Theoretical probability, sample spaces, simple events, and interpreting chance.', traps:'Assuming previous independent results affect the next outcome.', example:'A fair die has P(rolling 4)=1/6 each roll.', remember:'Independent trials do not “owe” an outcome.'}
    ],
    '5004': [
      {domain:'ss-us', id:'exploration-colonization', name:'Exploration, Colonization & Expansion', know:'European exploration, colonization, territorial growth, westward expansion, and their causes/effects.', traps:'Flattening distinct colonial regions into one experience.', example:'Geography and economic goals shaped regional settlement patterns.', remember:'Track motive, place, people, and consequence.'},
      {domain:'ss-us', id:'revolution-founding', name:'Revolution & Founding', know:'American Revolution, Articles of Confederation, Constitution, federalism, separation of powers, and key founding documents.', traps:'Confusing Declaration purposes with Constitution purposes.', example:'The Constitution creates a governing framework; the Declaration announces and justifies independence.', remember:'Declaration = why independence; Constitution = how government works.'},
      {domain:'ss-us', id:'us-history', name:'U.S. History from Founding to Present', know:'Major events and developments including expansion, Civil War/Reconstruction, industrialization, immigration, Depression, wars, civil rights, technology, and social change.', traps:'Memorizing dates without cause/effect.', example:'Industrialization encouraged urban growth and changed labor patterns.', remember:'Praxis likes causes, consequences, and continuity/change.'},
      {domain:'ss-us', id:'government-citizenship', name:'Government & Citizenship', know:'Federal/state/local government, branches, checks and balances, rights, responsibilities, elections, and civic participation.', traps:'Assigning a power to the wrong branch or level.', example:'Congress makes laws; the executive enforces them; courts interpret them.', remember:'Power is divided horizontally and vertically.'},
      {domain:'ss-us', id:'documents-cases', name:'Key Documents, Speeches & Civic Ideas', know:'Constitution, Declaration, Bill of Rights, major speeches, landmark court ideas, and civic principles.', traps:'Treating a document’s historical context as its legal function.', example:'Marbury v. Madison is associated with judicial review.', remember:'Know the big principle attached to each landmark.'},
      {domain:'ss-geo', id:'world-regional-geography', name:'World & Regional Geography', know:'Spatial terms, regions, physical features, place, location, movement, and map interpretation.', traps:'Confusing latitude with longitude.', example:'Latitude measures north/south of the Equator.', remember:'Latitude is flat lines; longitude runs pole to pole.'},
      {domain:'ss-geo', id:'human-environment', name:'Human-Environment Interaction', know:'How environments affect people, how people modify environments, and the role of resources.', traps:'Treating environmental influence as deterministic.', example:'Irrigation can support settlement in dry regions but changes water systems.', remember:'Interaction runs both directions.'},
      {domain:'ss-geo', id:'culture-society', name:'Culture, Anthropology & Sociology', know:'Culture, family, community, social institutions, diversity, migration, diffusion, and how groups interact with environments.', traps:'Assuming all members of a cultural group behave identically.', example:'Cultural diffusion occurs when ideas or practices spread between groups.', remember:'Culture is learned, shared, dynamic, and varied.'},
      {domain:'ss-world', id:'world-history', name:'World History', know:'Major civilizations, global exchanges, revolutions, empires, conflict, modernization, and twentieth-century global connections.', traps:'Trying to memorize every ruler instead of patterns and turning points.', example:'Trade networks spread goods, technologies, religions, and disease.', remember:'Think chronology + cause/effect + exchange.'},
      {domain:'ss-world', id:'economics', name:'Economics', know:'Scarcity, choice, opportunity cost, supply/demand, markets, production, trade, specialization, money, and basic government economic roles.', traps:'Confusing a monetary price with opportunity cost.', example:'Choosing to study instead of work has an opportunity cost of foregone wages/time.', remember:'Scarcity forces choices; choices have costs.'}
    ],
    '5005': [
      {domain:'sci-earth', id:'earth-structure', name:'Earth Structure & Materials', know:'Solid Earth, rocks/minerals, layers, hydrosphere, atmosphere, and Earth materials.', traps:'Calling every naturally occurring solid a mineral.', example:'A rock can contain multiple minerals.', remember:'Mineral = naturally occurring inorganic solid with characteristic composition/structure.'},
      {domain:'sci-earth', id:'earth-processes', name:'Earth Processes', know:'Plate tectonics, weathering, erosion, deposition, earthquakes, volcanoes, water cycle, weather, climate, and ocean effects.', traps:'Confusing weathering with erosion.', example:'Weathering breaks rock down; erosion moves the pieces.', remember:'Break vs. move.'},
      {domain:'sci-earth', id:'earth-history', name:'Earth History', know:'Origins, fossils, relative/absolute dating ideas, rock record, and geologic change over time.', traps:'Assuming deeper always means older without considering disturbance.', example:'Fossils and rock layers provide evidence of past environments.', remember:'Geologic evidence is interpreted in context.'},
      {domain:'sci-earth', id:'space', name:'Earth & Space', know:'Solar system, stars/galaxies, gravity, seasons, Moon phases, tides, eclipses, and Earth-Sun-Moon relationships.', traps:'Saying seasons are caused by Earth being closer to the Sun.', example:'Seasons come from axial tilt changing sunlight angle and day length.', remember:'Tilt, not distance.'},
      {domain:'sci-life', id:'cells-systems', name:'Cells & Organ Systems', know:'Characteristics of life, cells, tissues, organs, systems, and life processes.', traps:'Confusing organ, tissue, and cell levels.', example:'Muscle tissue is made of cells; the heart is an organ containing tissues.', remember:'Cells → tissues → organs → systems.'},
      {domain:'sci-life', id:'heredity', name:'Reproduction & Heredity', know:'Growth, development, inheritance patterns, genes/chromosomes, dominant/recessive concepts, and variation.', traps:'Thinking dominant means more common or stronger.', example:'A recessive trait can appear when an organism inherits two recessive alleles.', remember:'Dominance describes expression, not frequency.'},
      {domain:'sci-life', id:'evolution-adaptation', name:'Change Over Time & Adaptation', know:'Life cycles, mutation, adaptation, natural selection, classification, unity/diversity.', traps:'Saying individuals evolve because they need to.', example:'Populations change over generations as heritable traits affect reproductive success.', remember:'Individuals acclimate; populations evolve.'},
      {domain:'sci-life', id:'ecosystems', name:'Ecology & Interdependence', know:'Populations, communities, ecosystems, food webs, energy flow, matter cycling, and organism interactions.', traps:'Treating arrows in food webs as “who eats whom” direction instead of energy flow.', example:'An arrow from grass to rabbit shows energy moving to the rabbit.', remember:'Arrows point where energy goes.'},
      {domain:'sci-physical', id:'matter', name:'Matter & Its Properties', know:'States, physical/chemical properties and changes, mixtures/solutions, atoms/molecules, conservation of matter.', traps:'Calling dissolving a chemical change.', example:'Salt dissolving in water is usually a physical change because the substance can be recovered.', remember:'New substance? Think chemical change.'},
      {domain:'sci-physical', id:'force-motion', name:'Force & Motion', know:'Position, speed, velocity basics, forces, gravity, friction, balanced/unbalanced forces, and simple machines.', traps:'Assuming motion requires a continuing net force.', example:'Net force changes motion; zero net force means constant velocity can continue.', remember:'Force changes motion, not maintains it.'},
      {domain:'sci-physical', id:'energy', name:'Energy', know:'Kinetic/potential, heat, light, sound, electrical energy, transformations, conservation, and transfer.', traps:'Treating energy as “used up” instead of transformed/transferred.', example:'A falling object converts gravitational potential energy mainly to kinetic energy.', remember:'Energy changes form and location.'},
      {domain:'sci-physical', id:'inquiry', name:'Scientific Inquiry & Evidence', know:'Questions, hypotheses, variables, controls, data, graphs, conclusions, reliability, and use of scientific sources.', traps:'Calling the dependent variable the factor intentionally changed.', example:'The independent variable is manipulated; dependent variable is measured.', remember:'Change one, measure one, control the rest.'}
    ]
  }
};
