(function(){
  const B = window.PRAXIS_BLUEPRINT;
  const letters = ['A','B','C','D'];
  function rng(seed){ let s=(seed>>>0)||1; return ()=>((s=(s*1664525+1013904223)>>>0)/4294967296); }
  function pick(r,a){ return a[Math.floor(r()*a.length)]; }
  function shuffle(r,a){ a=a.slice(); for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; }
  function gcd(a,b){ while(b){[a,b]=[b,a%b]} return Math.abs(a); }
  function lcm(a,b){ return Math.abs(a*b)/gcd(a,b); }
  function fmt(n){ return Number.isInteger(n)?String(n):String(Math.round(n*1000)/1000); }
  function mcq(base,r){
    const tagged=base.choices.map((x,i)=>({text:String(x),ok:i===base.correctIndex,rat:base.rationales?.[i]||''}));
    const mixed=shuffle(r,tagged); const ci=mixed.findIndex(x=>x.ok);
    return {...base, choices:mixed.map(x=>x.text), correctIndex:ci, distractorRationale:mixed.map(x=>x.rat)};
  }
  function q(meta, stem, choices, correctIndex, explanation, rationales=[]){ return { ...meta, questionType:'mcq', stem, choices, correctIndex, explanation, rationales }; }
  function finalize(base, seed, serial){
    const r=rng(seed*97+serial*811); const out=mcq(base,r);
    out.id=`${out.subtest}-${out.topic}-${seed}-${serial}`;
    out.fingerprint=`${out.subtest}|${out.topic}|${out.skill}|${out.stem.replace(/\d+/g,'#').slice(0,120)}`;
    out.sourceBasis='Official ETS Praxis 5001 content specification; original practice item.';
    out.difficulty=out.difficulty||'medium';
    return out;
  }

  const readingPassages = [
    {id:'garden', text:'At first, the empty lot beside the library seemed useful only as a shortcut. Then a group of neighbors asked permission to plant vegetables there. By midsummer, the lot held tomatoes, beans, herbs, and sunflowers. Children stopped to measure the plants, older residents shared gardening advice, and the library began hosting Saturday workshops beside the beds. The harvest was welcome, but the larger change was that people who had once hurried through the lot now lingered and talked.', main:'The community garden transformed an overlooked space into a place that strengthened neighborhood connections.', infer:'The garden became valuable for social and educational reasons as well as for food.', purpose:'to explain how a community project changed the use and meaning of a shared space', detail:'The library began hosting Saturday workshops beside the garden beds.'},
    {id:'octopus', text:'An octopus can squeeze through an opening much smaller than its body appears to allow. Most of its body is soft tissue, and it has no rigid skeleton. The main limitation is its beak, a hard structure used for feeding. If the beak can pass through an opening, the rest of the animal often can too. This flexibility helps an octopus hide from predators and explore narrow spaces while hunting.', main:'An octopus’s soft body allows it to move through very small openings.', infer:'The beak determines the smallest opening an octopus can pass through.', purpose:'to explain a physical adaptation that helps octopuses survive', detail:'An octopus has a hard beak used for feeding.'},
    {id:'storm', text:'Mara checked the sky before leaving for the trail. The morning was bright, but clouds had begun building over the ridge. Halfway to the lookout, she noticed the wind becoming cooler and heard a low rumble. She turned around even though the summit was less than a mile away. Rain started just as she reached the parking area. Mara was disappointed, but she knew the mountain would still be there another day.', main:'Mara makes a cautious decision to turn back when signs of a storm appear.', infer:'Mara values safety more than completing the hike that day.', purpose:'to show a character making a decision in response to changing conditions', detail:'Mara heard a low rumble while hiking.'},
    {id:'mangrove', text:'Mangrove trees grow along tropical coastlines where many other trees cannot survive. Their roots tolerate salty water and often rise above the mud in tangled networks. These roots slow waves, trap sediment, and provide shelter for young fish and other animals. Where mangrove forests are removed, shorelines may become more vulnerable to erosion and storm damage.', main:'Mangroves are specially adapted coastal trees that also protect shorelines and habitats.', infer:'Removing mangroves can affect both land stability and marine life.', purpose:'to describe mangrove adaptations and their ecological importance', detail:'Mangrove roots can slow waves and trap sediment.'},
    {id:'bell', text:'The brass bell had hung outside the school office for decades, though no one used it anymore. When the building was renovated, workers planned to throw it away. Ms. Chen asked them to wait. Her class interviewed former students and learned that the bell had once signaled recess, emergencies, and the end of the school day. The students created a small exhibit, and the bell was placed in the new entryway with photographs and recorded memories.', main:'Students preserve an old school bell after learning about its historical importance.', infer:'Objects can gain value from the memories and history connected to them.', purpose:'to tell how students discovered and preserved part of their school history', detail:'The class interviewed former students about the bell.'}
  ];

  const conceptBanks = {
    '5002': [
      ['rla-reading','phonological-awareness','phoneme manipulation','Which activity most directly practices phoneme deletion?',['Say “smile” without /s/.','Clap the two syllables in “rabbit.”','Match the printed word cat to a picture.','Underline the prefix in “unhappy.”'],0,'Deleting /s/ from “smile” requires removing one speech sound while holding the remaining sounds in memory. That is phoneme deletion, a phonological-awareness skill.',['','Clapping syllables is phonological awareness, but it practices syllable segmentation, not phoneme deletion.','Matching print to meaning does not isolate phonemes.','Identifying a prefix is morphological analysis.']],
      ['rla-reading','phonics-word-analysis','syllable type','Which word contains an open first syllable?',['robot','basket','rabbit','napkin'],0,'In “robot,” the first syllable is “ro,” which ends in a vowel sound and is open. Open syllables commonly have a long vowel sound.'],
      ['rla-reading','fluency','prosody','A student reads accurately at an appropriate rate but uses a flat voice and ignores punctuation. Which fluency component most needs support?',['Prosody','Accuracy','Decoding','Phonemic awareness'],0,'Prosody is expressive phrasing, stress, intonation, and attention to punctuation. The student already demonstrates accuracy and an adequate rate.'],
      ['rla-writing','writing-process','revision vs editing','A student has strong sentences, but the explanation gives evidence before introducing the claim. What is the best next step?',['Revise the organization of ideas.','Correct spelling errors.','Increase handwriting speed.','Replace every simple sentence with a compound sentence.'],0,'The main problem is organization, so revision is appropriate. Editing focuses more on conventions such as spelling, punctuation, and grammar.'],
      ['rla-writing','grammar-usage','subject-verb agreement','Which sentence is grammatically correct?',['Each of the science stations is ready.','Each of the science stations are ready.','Each of the science stations were ready every day.','Each of the science stations have been ready.'],0,'The subject “Each” is singular, so it takes the singular verb “is.” The nearby plural noun “stations” does not control agreement.'],
      ['rla-writing','research','source credibility','A student needs the current population of a state. Which source is generally strongest?',['A recent official census data table','An undated personal blog','A social media post with no source','An advertisement for moving services'],0,'Official, recent census data are directly relevant and provide transparent evidence for population figures.'],
      ['rla-writing','speaking-listening','active listening','Which student behavior best demonstrates active listening during a discussion?',['Paraphrasing a classmate’s idea before responding','Looking at notes while another student speaks','Waiting silently only to repeat a prepared comment','Speaking more loudly to show confidence'],0,'Paraphrasing shows the listener processed the speaker’s idea and can respond to it meaningfully.'],
      ['rla-writing','writing-types','argument writing','Which feature is most characteristic of opinion/argument writing?',['A claim supported by reasons and evidence','Events arranged to build a plot','Neutral explanation of a process only','Sensory details used only to establish setting'],0,'Argument writing advances a claim and supports it with reasons and evidence suited to the audience and purpose.']
    ],
    '5004': [
      ['ss-us','exploration-colonization','colonial regions','Which factor most directly helped shape different economic patterns among Britain’s North American colonies?',['Differences in climate, geography, and available resources','A requirement that every colony grow the same crop','Identical settlement motives in every region','A complete absence of Atlantic trade'],0,'Regional geography and resources interacted with labor systems, settlement motives, and trade to produce different colonial economies.'],
      ['ss-us','revolution-founding','founding documents','Which statement best distinguishes the Declaration of Independence from the U.S. Constitution?',['The Declaration explains and justifies independence; the Constitution establishes a governing framework.','The Declaration created three branches; the Constitution announced independence.','The Declaration is a court decision; the Constitution is a treaty.','The Declaration created federalism; the Constitution ended colonial rule immediately.'],0,'The Declaration states grievances and the rationale for independence. The Constitution, written later, structures the national government and allocates powers.'],
      ['ss-us','government-citizenship','separation of powers','Which action is primarily a legislative function at the federal level?',['Passing a law','Interpreting whether a law is constitutional','Enforcing a law through an executive agency','Negotiating a treaty on behalf of the nation'],0,'Congress is the legislative branch and passes federal laws. Courts interpret law, while the executive branch enforces law and conducts much foreign policy.'],
      ['ss-us','documents-cases','judicial review','Marbury v. Madison is most closely associated with which principle?',['Judicial review','Popular sovereignty','Reserved powers','Direct democracy'],0,'Marbury v. Madison established the Supreme Court’s authority to review government actions for constitutionality, known as judicial review.'],
      ['ss-us','us-history','industrialization','Which change was most directly associated with U.S. industrialization in the late nineteenth century?',['Rapid urban growth around factories','A broad return from cities to subsistence farms','The disappearance of immigration','The end of rail transportation'],0,'Industrial jobs and transportation networks helped cities expand rapidly. Immigration and rail growth were also important parts of the period.'],
      ['ss-geo','world-regional-geography','latitude','Which coordinate measures distance north or south of the Equator?',['Latitude','Longitude','Elevation','Scale'],0,'Latitude lines measure angular distance north or south of the Equator. Longitude measures east or west of the prime meridian.'],
      ['ss-geo','human-environment','interaction','Which is the clearest example of people modifying an environment to meet a need?',['Building irrigation canals in a dry region','A hurricane forcing residents to evacuate','A mountain range limiting road construction','Cold winters increasing demand for heating'],0,'Irrigation is a human modification of the environment. The other choices mainly show environmental conditions affecting people.'],
      ['ss-geo','culture-society','cultural diffusion','Which situation best illustrates cultural diffusion?',['A food tradition spreads to another region through migration and exchange.','A community remains completely isolated for centuries.','A law establishes a new tax rate.','A river changes course after a flood.'],0,'Cultural diffusion is the spread of cultural ideas, practices, technologies, or products between groups.'],
      ['ss-world','economics','opportunity cost','A teacher spends Saturday studying instead of working a paid shift. The opportunity cost is best described as',['the value of the paid shift and other benefits given up','the price of the study materials only','the total amount of money in the teacher’s bank account','the cost of every possible activity that exists'],0,'Opportunity cost is the value of the next-best alternative forgone when a choice is made.'],
      ['ss-world','economics','scarcity','Why is scarcity a central economic concept?',['Resources are limited while wants are not, so choices must be made.','All goods are equally difficult to produce.','Governments always set all prices.','People never change what they want.'],0,'Scarcity means available resources are insufficient to satisfy every possible want, which forces choices and tradeoffs.'],
      ['ss-world','world-history','trade networks','Historically, long-distance trade networks most often contributed to',['the exchange of goods, technologies, beliefs, and diseases','complete cultural isolation','the elimination of political conflict everywhere','identical governments in all trading regions'],0,'Trade networks connected societies, moving not just products but also ideas, technologies, religions, people, and pathogens.']
    ],
    '5005': [
      ['sci-earth','earth-history','rock record','Why are fossils found in sedimentary rock layers useful to scientists studying Earth history?',['They provide evidence about past organisms and environments.','They prove every rock layer formed at the same time.','They show that Earth’s surface has never changed.','They can occur only in rocks younger than one century.'],0,'Fossils preserved in rock layers help reconstruct past life and environments and can support relative-age interpretations when geologic context is considered.'],
      ['sci-earth','earth-processes','weathering erosion','Which statement correctly distinguishes weathering from erosion?',['Weathering breaks material down; erosion transports it.','Weathering transports material; erosion creates new minerals only.','Weathering occurs only in deserts; erosion occurs only near water.','Weathering and erosion are exactly the same process.'],0,'Weathering is the physical or chemical breakdown of rock at or near its location. Erosion is the movement of weathered material by water, wind, ice, or gravity.'],
      ['sci-earth','space','seasons','What is the primary cause of Earth’s seasons?',['Earth’s axial tilt changes sunlight angle and day length during its orbit.','Earth is dramatically closer to the Sun in summer everywhere.','The Moon blocks part of the Sun during winter.','Earth spins faster during summer.'],0,'Earth’s axis is tilted. As Earth orbits the Sun, each hemisphere alternately receives more direct sunlight and longer days. Distance from the Sun is not the main cause.'],
      ['sci-earth','space','tides','Ocean tides are caused primarily by',['gravitational interactions, especially with the Moon','Earth’s magnetic field only','daily changes in ocean salinity','photosynthesis by marine plants'],0,'The Moon’s gravity is the dominant influence on tides, with the Sun also contributing.'],
      ['sci-earth','earth-structure','rocks minerals','Which statement is correct?',['A rock may be composed of one or more minerals.','Every rock is a single pure element.','All minerals are made by living organisms.','A mineral has no characteristic composition.'],0,'Rocks are aggregates of minerals or mineral-like material. Minerals have characteristic compositions and structures.'],
      ['sci-life','cells-systems','levels organization','Which sequence goes from simplest to more complex biological organization?',['cell → tissue → organ → organ system','tissue → cell → organ system → organ','organ → cell → tissue → organism','organ system → organ → tissue → cell'],0,'Cells combine to form tissues; tissues form organs; organs coordinate in organ systems.'],
      ['sci-life','heredity','dominance','Which statement about a dominant allele is most accurate?',['Its trait can be expressed when one copy is present in a simple dominant-recessive model.','It is always the most common allele in a population.','It is always healthier than a recessive allele.','It permanently eliminates recessive alleles.'],0,'Dominance describes how alleles are expressed in a particular inheritance model. It does not mean common, beneficial, or stronger.'],
      ['sci-life','evolution-adaptation','natural selection','Which statement best describes natural selection?',['Heritable traits that improve reproductive success can become more common over generations.','Individual organisms intentionally develop needed traits and pass them on.','Every mutation improves survival.','All members of a population become identical.'],0,'Natural selection acts on heritable variation. Individuals with traits that improve reproductive success tend to contribute more offspring, shifting trait frequencies over generations.'],
      ['sci-life','ecosystems','energy flow','In a food web, an arrow from grass to a rabbit most directly represents',['energy moving from grass to rabbit','the rabbit providing energy to grass','the rabbit pollinating the grass','the grass hunting the rabbit'],0,'Food-web arrows conventionally show the direction of energy transfer, from the consumed organism to the consumer.'],
      ['sci-physical','matter','physical chemical change','Which is primarily a physical change?',['Salt dissolving in water','Iron rusting','Wood burning','An egg cooking'],0,'Dissolving salt changes its distribution in water without producing a new substance under ordinary conditions; the salt can be recovered by evaporating the water.'],
      ['sci-physical','force-motion','net force','A hockey puck moves at constant velocity in a straight line. What can be concluded about the net force on it?',['The net force is zero.','A forward net force must be present.','A backward net force must be present.','Gravity is absent.'],0,'Constant velocity means no acceleration. By Newton’s second law, zero acceleration corresponds to zero net force, even though individual forces may still act and balance.'],
      ['sci-physical','energy','energy transformation','As a ball falls, ignoring air resistance, its gravitational potential energy primarily',['decreases while kinetic energy increases','increases while kinetic energy decreases','disappears completely','becomes mass'],0,'As height decreases, gravitational potential energy is converted into kinetic energy. Total mechanical energy is conserved when air resistance is ignored.'],
      ['sci-physical','inquiry','variables','A researcher changes the amount of light plants receive and measures plant height. What is the dependent variable?',['Plant height','Amount of light','Plant species if held constant','Pot size if held constant'],0,'The dependent variable is the outcome measured in response to the manipulated independent variable. Here, height is measured while light is changed.']
    ]
  };

  conceptBanks['5004'].push(
    ['ss-us','exploration-colonization','colonial motives','Which motive most strongly encouraged many European voyages of exploration during the fifteenth and sixteenth centuries?',['Seeking new trade routes and access to valuable goods','Avoiding all overseas commerce','Creating modern nation-states in North America immediately','Ending the use of ocean navigation'],0,'European powers sought trade routes, wealth, strategic advantage, and opportunities for expansion.'],
    ['ss-us','exploration-colonization','westward expansion','Which development most directly accelerated migration to the U.S. West during the nineteenth century?',['Transportation improvements and access to new lands','The permanent closure of western territories','The disappearance of mineral discoveries','A federal ban on overland travel'],0,'Transportation networks, land policies, economic opportunities, and resource discoveries all encouraged westward migration.'],
    ['ss-us','revolution-founding','articles confederation','A major weakness of the Articles of Confederation was that the national government',['lacked strong power to tax and enforce national policies','had an executive branch with unlimited power','could easily overrule state governments in every matter','controlled a permanent national school system'],0,'The Articles created a deliberately weak central government. Congress struggled to raise revenue and enforce national decisions.'],
    ['ss-us','revolution-founding','checks balances','Which example best illustrates checks and balances?',['The president vetoes a bill passed by Congress.','A governor appoints a city mayor in every municipality.','A citizen votes in a local election.','A state redraws a county road map.'],0,'A presidential veto is an executive check on legislation passed by the legislative branch.'],
    ['ss-us','government-citizenship','federalism','Federalism in the United States refers to',['the division of power between national and state governments','the concentration of all power in one national legislature','rule by judges without elected officials','direct voting on every national law'],0,'Federalism divides governing authority between the national government and state governments.'],
    ['ss-us','government-citizenship','civic responsibility','Which is a civic responsibility rather than a constitutionally protected right?',['Serving on a jury when legally summoned','Freedom of speech','Protection from unreasonable searches','Free exercise of religion'],0,'Jury service is a civic duty imposed under law. The other choices are constitutional rights.'],
    ['ss-us','documents-cases','bill rights','Which protection is found in the First Amendment?',['Freedom of speech','A two-term limit for presidents','Direct election of senators','A guarantee of public employment'],0,'The First Amendment protects speech, religion, press, assembly, and petition.'],
    ['ss-us','documents-cases','civil rights','Brown v. Board of Education is most closely associated with',['rejecting racial segregation in public schools as unconstitutional','establishing judicial review','creating the Electoral College','expanding presidential treaty power'],0,'Brown held that state-mandated racial segregation in public schools violated equal protection.'],
    ['ss-us','us-history','civil war','Which issue was central to the sectional conflict that led to the U.S. Civil War?',['The expansion and preservation of slavery','Whether the United States should adopt the metric system','The location of the national capital after 1900','Whether railroads should use steam engines'],0,'Slavery, including its expansion into territories and the political power surrounding it, was central to sectional conflict.'],
    ['ss-us','us-history','great depression','Which federal response is most associated with the Great Depression?',['New Deal programs expanded federal involvement in relief, recovery, and reform.','The government eliminated all banking regulation.','Congress abolished federal taxation permanently.','The United States stopped using currency.'],0,'The New Deal involved a broad set of federal programs and reforms aimed at relief, recovery, and financial/economic reform.'],
    ['ss-us','us-history','civil rights movement','Which strategy was widely used by the U.S. civil rights movement of the 1950s and 1960s?',['Nonviolent protest and legal challenges','Ending all court cases involving equal protection','Avoiding public demonstrations entirely','Replacing elections with hereditary offices'],0,'Boycotts, marches, sit-ins, voter registration efforts, and court challenges were important civil-rights strategies.'],
    ['ss-geo','world-regional-geography','longitude','Longitude is measured east or west from the',['Prime Meridian','Equator','Tropic of Cancer only','International Date Line only'],0,'Longitude measures angular distance east or west of the Prime Meridian.'],
    ['ss-geo','world-regional-geography','map scale','A map scale is most useful for determining',['the real-world distance represented by a distance on the map','the political ideology of a region','the age of every landmark shown','the annual rainfall without other data'],0,'Scale links map distance to actual distance.'],
    ['ss-geo','human-environment','resource settlement','Why have many cities historically developed near rivers or coastlines?',['Waterways support transportation, trade, water access, and other economic activities.','Waterways make agriculture impossible everywhere.','People cannot build roads away from water.','All climates near water are identical.'],0,'Navigable water and access to resources often support trade, transportation, settlement, and industry.'],
    ['ss-geo','human-environment','adaptation environment','Which is an example of people adapting to an environment rather than modifying it?',['Designing buildings with steep roofs in a snowy climate','Draining a wetland to build houses','Constructing a dam across a river','Cutting a canal through an isthmus'],0,'A steep roof is a design adaptation to snowy conditions. The other examples physically modify environments.'],
    ['ss-geo','culture-society','migration','Which is a pull factor in migration?',['Availability of jobs in the destination','War in the place of origin','A destructive drought at home','Political persecution in the origin country'],0,'Pull factors attract people to a destination; job opportunities are a common example.'],
    ['ss-geo','culture-society','social institutions','Schools, families, governments, and religious organizations are examples of',['social institutions','lines of longitude','physical landforms','monetary policies'],0,'Social institutions are organized structures through which societies meet needs and transmit norms and practices.'],
    ['ss-world','world-history','agriculture civilizations','The development of agriculture most directly contributed to',['more permanent settlements and population growth','the immediate end of trade','the disappearance of social specialization','the elimination of all infectious disease'],0,'Reliable food production supported permanent settlements, larger populations, specialization, and increasingly complex societies.'],
    ['ss-world','world-history','industrial revolution','One major effect of the Industrial Revolution was',['increased factory production and urbanization','the end of mechanized production','a universal return to rural subsistence farming','the disappearance of international trade'],0,'Mechanized factory production expanded and helped drive rapid urbanization and new labor systems.'],
    ['ss-world','world-history','global exchange','The Columbian Exchange refers to the large-scale movement of',['plants, animals, people, diseases, and goods between the Americas and Afro-Eurasia','only coins within Europe','only religious texts across Asia','industrial machinery between the poles'],0,'After sustained Atlantic contact, organisms, people, commodities, and diseases moved between hemispheres on a massive scale.'],
    ['ss-world','economics','supply demand','If demand for a product rises while supply stays the same, what generally happens to market price, all else equal?',['It tends to rise.','It must fall to zero.','It cannot change.','It becomes unrelated to scarcity.'],0,'Greater demand competing for unchanged supply generally places upward pressure on price.'],
    ['ss-world','economics','specialization trade','Why can specialization encourage trade?',['People or regions can focus on what they produce relatively efficiently and exchange for other goods.','Specialization makes exchange impossible.','It guarantees every producer has identical resources.','It removes all opportunity costs.'],0,'Specialization can increase productivity and creates reasons to exchange for goods and services others produce.'],
    ['ss-world','economics','public goods','Which is the best example of a public good commonly provided by government?',['Street lighting','A private restaurant meal','A personal smartphone','A ticket to a private concert'],0,'Street lighting is broadly shared and difficult to exclude nonpayers from using, making it a classic public-good example.']
  );

  conceptBanks['5005'].push(
    ['sci-earth','earth-structure','earth layers','Which Earth layer is primarily liquid iron and nickel?',['Outer core','Inner core','Crust','Upper mantle'],0,'The outer core is liquid and composed largely of iron and nickel; the inner core is solid under immense pressure.'],
    ['sci-earth','earth-structure','mineral properties','Which property is most useful for identifying a mineral?',['A combination of properties such as hardness, streak, and cleavage','The color of the box it was stored in','The weather on the day it was found','Whether it is larger than a pebble'],0,'Minerals are identified using characteristic physical properties, often in combination.'],
    ['sci-earth','earth-processes','plate boundaries','Most earthquakes occur near tectonic plate boundaries because',['plates interact and stress can be released suddenly along faults','gravity stops working at plate boundaries','ocean tides disappear there','all plate boundaries are volcanoes'],0,'Plate motion builds stress in rocks; sudden slip along faults releases energy as earthquakes.'],
    ['sci-earth','earth-processes','water cycle','Which process changes liquid water at Earth’s surface into water vapor?',['Evaporation','Condensation','Precipitation','Deposition'],0,'Evaporation occurs when liquid water gains enough energy for molecules to enter the gas phase.'],
    ['sci-earth','earth-history','relative dating','In an undisturbed sequence of sedimentary rock layers, which layer is generally oldest?',['The lowest layer','The highest layer','Every layer is the same age','The thinnest layer'],0,'The law of superposition states that in an undisturbed sequence, older sedimentary layers lie below younger layers.'],
    ['sci-earth','earth-history','fossils','An index fossil is especially useful for',['correlating the relative ages of rock layers in different locations','measuring current wind speed','determining daily tides','identifying the chemical formula of water'],0,'Widespread organisms that lived during limited time intervals can help correlate rock layers by relative age.'],
    ['sci-earth','space','moon phases','Why does the Moon appear to change phase over a month?',['We see changing portions of its sunlit half as it orbits Earth.','Earth’s shadow covers the Moon every night.','The Moon produces different amounts of light each week.','Clouds permanently block different sections of the Moon.'],0,'Half the Moon is illuminated by the Sun at nearly all times; its orbital position changes how much of that lit half we see.'],
    ['sci-earth','space','solar eclipse','A solar eclipse occurs when',['the Moon passes between Earth and the Sun','Earth passes between the Sun and Moon','the Sun passes between Earth and Moon','Mars blocks the Moon every month'],0,'During a solar eclipse, the Moon is positioned between Earth and the Sun so its shadow falls on part of Earth.'],
    ['sci-life','cells-systems','cell organelles','Which cell structure contains genetic material and directs many cell activities in eukaryotic cells?',['Nucleus','Cell wall','Vacuole only','Ribosome membrane'],0,'The nucleus contains most of a eukaryotic cell’s DNA and helps regulate cell activity through gene expression.'],
    ['sci-life','cells-systems','plant function','Which plant structure primarily absorbs water and minerals from soil?',['Roots','Flowers','Fruits','Petals'],0,'Roots anchor the plant and absorb water and dissolved minerals from the soil.'],
    ['sci-life','heredity','genes chromosomes','Genes are best described as',['segments of DNA that influence inherited traits and biological functions','types of cells found only in muscles','energy molecules used only during exercise','minerals stored in bones'],0,'Genes are DNA sequences that contribute to inherited characteristics and cell functions.'],
    ['sci-life','heredity','variation','Which process produces offspring that usually have a new combination of parental genes?',['Sexual reproduction','Binary fission only','Evaporation','Photosynthesis'],0,'Sexual reproduction combines genetic material from two parents, creating new allele combinations.'],
    ['sci-life','evolution-adaptation','adaptation','Which trait is best described as an adaptation?',['A heritable feature that increases reproductive success in a particular environment','A temporary suntan acquired during one summer','A skill learned by one animal but not inherited','Any trait an organism wishes to have'],0,'An adaptation is a heritable characteristic shaped by natural selection because it improves fitness in a given environment.'],
    ['sci-life','evolution-adaptation','classification','Organisms are classified partly to',['organize biological diversity based on shared characteristics and evolutionary relationships','prove all organisms are unrelated','eliminate the need for scientific names','group organisms only by body size'],0,'Classification provides a structured way to organize diversity and increasingly reflects evolutionary relationships.'],
    ['sci-life','ecosystems','producer consumer','Which organism is a producer in most ecosystems?',['A green plant','A hawk','A mushroom','A rabbit'],0,'Green plants use photosynthesis to capture energy and build organic molecules, forming the base of many food webs.'],
    ['sci-life','ecosystems','population community','All the different populations living and interacting in one area form a',['community','single organism','mineral','gene'],0,'A population is one species in an area; multiple interacting populations form a community.'],
    ['sci-physical','matter','states matter','Which change is condensation?',['Water vapor becoming liquid water','Liquid water becoming vapor','Ice becoming liquid water','Liquid water becoming ice'],0,'Condensation is the change from gas to liquid.'],
    ['sci-physical','matter','density','Two objects have the same volume. Object A has greater mass than object B. Which has greater density?',['Object A','Object B','They must have equal density','Density cannot depend on mass'],0,'Density = mass ÷ volume. With equal volumes, the object with greater mass has greater density.'],
    ['sci-physical','force-motion','friction','Friction generally acts',['opposite relative motion between surfaces in contact','only upward','only when objects are motionless','in the same direction as every applied force'],0,'Friction resists relative motion or attempted motion between surfaces.'],
    ['sci-physical','force-motion','balanced forces','A book rests motionless on a table. Which statement is correct?',['The upward normal force balances the downward gravitational force.','No forces act on the book.','Only gravity acts on the book.','The book has a large horizontal net force.'],0,'Gravity pulls downward while the table exerts an upward normal force of equal magnitude, producing zero net force.'],
    ['sci-physical','energy','heat transfer','A metal spoon becomes hot after sitting in soup. The main energy-transfer process through the spoon is',['conduction','photosynthesis','evaporation','nuclear fusion'],0,'Conduction transfers thermal energy through direct particle interactions within the metal.'],
    ['sci-physical','energy','sound','Sound requires a medium because it is',['a mechanical wave produced by vibrations of matter','a form of visible light','a stream of electrons only','independent of particles'],0,'Sound is a mechanical wave and travels by vibrations passing through matter; it cannot travel through a perfect vacuum.'],
    ['sci-physical','inquiry','control group','Why is a control group useful in an experiment?',['It provides a baseline for comparison with the treatment condition.','It guarantees the hypothesis is correct.','It changes all variables at once.','It eliminates the need to collect data.'],0,'A control provides a comparison condition, helping isolate the effect of the independent variable.'],
    ['sci-physical','inquiry','reliability','Which change would most improve confidence in an experimental result?',['Repeating trials and obtaining consistent results','Changing several variables at once','Recording only results that support the hypothesis','Using a sample size of one whenever possible'],0,'Replication and consistent results increase reliability and reduce the chance that a finding is due to random variation.']
  );

  function mathGenerator(seed, domain, topic){
    const r=rng(seed*1009 + topic.length*37); let base;
    if(topic==='place-value'){
      const d=1+Math.floor(r()*8), place=pick(r,[10,100,1000,10000]); const n=(Math.floor(r()*700)+200)*place+d*place+Math.floor(r()*place);
      const correct=d*place; base=q({subtest:'5003',domain,topic,skill:'digit value',difficulty:'easy'},`In the number ${n.toLocaleString()}, what is the value of the digit ${d} in the ${place===10?'tens':place===100?'hundreds':place===1000?'thousands':'ten-thousands'} place?`,[correct,d,place,correct*10],0,`A digit’s value equals the digit multiplied by its place value. ${d} × ${place.toLocaleString()} = ${correct.toLocaleString()}.`);
    } else if(topic==='rational-operations'){
      const b=4+Math.floor(r()*8), groups=3+Math.floor(r()*8), extra=Math.floor(r()*b); const total=b*groups+extra;
      base=q({subtest:'5003',domain,topic,skill:'division remainder interpretation'},`${total} students are placed into teams of ${b}. How many full teams can be formed?`,[groups,groups+1,extra,total-b],0,`${total} ÷ ${b} = ${groups} remainder ${extra}. The question asks for full teams, so the remainder does not form another full team.`);
    } else if(topic==='fractions-decimals'){
      let a=1+Math.floor(r()*4), b=2+Math.floor(r()*5), c=1+Math.floor(r()*4), d=2+Math.floor(r()*5); if(a>=b)a=b-1;if(c>=d)c=d-1;
      const den=lcm(b,d), num=a*(den/b)+c*(den/d), g=gcd(num,den), ans=`${num/g}/${den/g}`;
      base=q({subtest:'5003',domain,topic,skill:'fraction addition'},`What is ${a}/${b} + ${c}/${d}?`,[ans,`${a+c}/${b+d}`,`${a+c}/${den}`,`${num}/${den+1}`],0,`Use a common denominator of ${den}: ${a}/${b} = ${a*(den/b)}/${den} and ${c}/${d} = ${c*(den/d)}/${den}. Add to get ${num}/${den}, which simplifies to ${ans}.`);
    } else if(topic==='factors-multiples'){
      const a=pick(r,[6,8,9,10,12,14,15]), b=pick(r,[12,18,20,21,24,30]); const ans=lcm(a,b);
      base=q({subtest:'5003',domain,topic,skill:'least common multiple'},`What is the least common multiple of ${a} and ${b}?`,[ans,a*b,gcd(a,b),ans+Math.min(a,b)],0,`The least common multiple is the smallest positive number divisible by both ${a} and ${b}. Listing multiples or using prime factors gives ${ans}.`);
    } else if(topic==='estimation'){
      const a=40+Math.floor(r()*60), b=15+Math.floor(r()*35), exact=a*b, est=Math.round(a/10)*10*Math.round(b/10)*10;
      base=q({subtest:'5003',domain,topic,skill:'reasonableness'},`Without calculating exactly, which is the best estimate of ${a} × ${b}?`,[est,Math.round(est/10),est*10,Math.abs(a-b)],0,`Round to friendly tens: ${a} ≈ ${Math.round(a/10)*10} and ${b} ≈ ${Math.round(b/10)*10}. Their product is about ${est.toLocaleString()}, which is close to the exact value ${exact.toLocaleString()}.`);
    } else if(topic==='expressions'){
      const x=2+Math.floor(r()*8), m=2+Math.floor(r()*6), b=1+Math.floor(r()*12), y=m*x+b;
      base=q({subtest:'5003',domain,topic,skill:'solve equation'},`Solve for x: ${m}x + ${b} = ${y}`,[x,x+b,y-b,Math.floor(y/m)],0,`Subtract ${b}: ${m}x = ${y-b}. Then divide by ${m}: x = ${x}.`);
    } else if(topic==='linear'){
      const m=2+Math.floor(r()*5), x=2+Math.floor(r()*7), b=1+Math.floor(r()*8), y=m*x+b;
      base=q({subtest:'5003',domain,topic,skill:'linear relationship'},`A table follows the rule y = ${m}x + ${b}. What is y when x = ${x}?`,[y,m+x+b,m*x,y+b],0,`Substitute x = ${x}: y = ${m}(${x}) + ${b} = ${y}.`);
    } else if(topic==='patterns'){
      const start=1+Math.floor(r()*5), step=2+Math.floor(r()*6); const seq=[0,1,2,3].map(i=>start+i*step); const next=start+4*step;
      base=q({subtest:'5003',domain,topic,skill:'arithmetic pattern'},`What is the next number in the pattern ${seq.join(', ')}, ...?`,[next,next+step,next-1,seq[3]*2],0,`Each term increases by ${step}. Add ${step} to ${seq[3]} to get ${next}.`);
    } else if(topic==='geometry'){
      const w=3+Math.floor(r()*9), h=3+Math.floor(r()*9), area=w*h, per=2*(w+h);
      base=q({subtest:'5003',domain,topic,skill:'area vs perimeter'},`A rectangle is ${w} units by ${h} units. What is its area?`,[area,per,w+h,area*2],0,`Area measures the surface inside the rectangle: ${w} × ${h} = ${area} square units. ${per} is the perimeter.`);
    } else if(topic==='measurement'){
      const yd=1+Math.floor(r()*8), ft=yd*3;
      base=q({subtest:'5003',domain,topic,skill:'customary conversion'},`How many feet are in ${yd} yard${yd===1?'':'s'}?`,[ft,yd+3,yd*12,yd/3],0,`There are 3 feet in 1 yard, so ${yd} × 3 = ${ft} feet.`);
    } else if(topic==='data-statistics'){
      const vals=[4+Math.floor(r()*5),6+Math.floor(r()*5),7+Math.floor(r()*6),8+Math.floor(r()*6),50+Math.floor(r()*40)].sort((a,b)=>a-b); const median=vals[2];
      base=q({subtest:'5003',domain,topic,skill:'median with outlier'},`For the data set ${vals.join(', ')}, which measure best represents a typical central value if the largest value is an unusual outlier?`,['Median','Mean','Range','Maximum'],0,`The outlier strongly pulls the mean upward. The median (${median}) is resistant to extreme values and better represents the center here.`);
    } else {
      const red=1+Math.floor(r()*5), blue=1+Math.floor(r()*5), total=red+blue; const g=gcd(red,total), ans=`${red/g}/${total/g}`;
      base=q({subtest:'5003',domain,topic:'probability',skill:'theoretical probability'},`A bag contains ${red} red counters and ${blue} blue counters. If one counter is chosen at random, what is the probability it is red?`,[ans,`${blue}/${total}`,`${red}/${blue}`,`${total}/${red}`],0,`Probability = favorable outcomes ÷ total outcomes = ${red}/${total}, which simplifies to ${ans}.`);
    }
    return base;
  }

  function rlaGenerator(seed, domain, topic){
    const r=rng(seed*1931 + topic.length); let base;
    if(topic==='language-vocab'){
      const sets=[
        ['After hiking for hours in steep heat, Lena found the final climb grueling.', 'What does “grueling” most nearly mean as used in the sentence?', ['extremely tiring','brief and effortless','quietly humorous','carefully hidden'], 0, 'The context describes hours of difficult hiking and a final climb, so “grueling” means extremely tiring or demanding.'],
        ['The coach’s concise directions took less than a minute but told everyone exactly what to do.', 'What does “concise” most nearly mean?', ['brief and clear','angry and confusing','highly repetitive','uncertain and indirect'],0,'The sentence contrasts the short amount of time with complete directions, supporting the meaning “brief and clear.”'],
        ['Unlike the noisy hallway, the library was tranquil.', 'What does “tranquil” most nearly mean?', ['calm and peaceful','crowded and loud','brightly decorated','difficult to enter'],0,'The contrast with a noisy hallway signals that “tranquil” means calm and peaceful.'],
        ['The first model was fragile, so the students handled it with unusual care.', 'What does “fragile” most nearly mean?', ['easily broken','very expensive','brightly colored','difficult to understand'],0,'The need for unusual care indicates that “fragile” means easily broken or damaged.'],
        ['Because the evidence was compelling, even the skeptical committee members changed their minds.', 'What does “compelling” most nearly mean?', ['convincing','irrelevant','secret','ordinary'],0,'The evidence caused skeptical people to change their minds, so “compelling” means convincing or persuasive.']
      ];
      const z=pick(r,sets); base=q({subtest:'5002',domain,topic,skill:'vocabulary in context'},`${z[0]}\n\n${z[1]}`,z[2],z[3],z[4]);
    } else if(['key-ideas','text-structure'].includes(topic)){
      const p=pick(r,readingPassages); const type=topic==='key-ideas'?pick(r,['main','infer','detail']):'purpose';
      let stem, correct, wrong;
      if(type==='main'){stem=`Read the passage.\n\n${p.text}\n\nWhich statement best expresses the central idea?`;correct=p.main;wrong=['The passage mainly lists unrelated facts with no central focus.','The passage argues that every community should copy the exact same action.','The passage focuses primarily on a minor detail rather than the overall idea.'];}
      else if(type==='detail'){stem=`Read the passage.\n\n${p.text}\n\nWhich detail is explicitly stated in the passage?`;correct=p.detail;wrong=['A detail that is plausible but not stated in the passage.','A conclusion that goes beyond the evidence provided.','An idea that contradicts the passage.'];}
      else if(topic==='text-structure'){stem=`Read the passage.\n\n${p.text}\n\nWhat is the author’s main purpose?`;correct=p.purpose;wrong=['to entertain only with an unrelated fantasy','to give step-by-step directions for completing a task','to persuade readers to buy a specific product'];}
      else {stem=`Read the passage.\n\n${p.text}\n\nWhich inference is best supported by the passage?`;correct=p.infer;wrong=['A claim that is possible but unsupported by the passage.','A statement contradicted by details in the passage.','A broad generalization that the passage does not justify.'];}
      base=q({subtest:'5002',domain,topic,skill:type,difficulty:'medium'},stem,[correct,...wrong],0,`The best answer is supported by the passage as a whole. It fits the stated details without adding information the text does not justify.`);
    } else if(topic==='phonological-awareness'){
      const sets=[
        ['phoneme blending',`A teacher says ${pick(r,['/s/ /u/ /n/','/m/ /a/ /p/','/f/ /i/ /sh/'])} and asks a student to say the whole word. Which skill is being assessed?`,['Phoneme blending','Phoneme deletion','Syllable counting','Print awareness'],0,'Combining separately spoken phonemes into a whole word is phoneme blending.'],
        ['phoneme segmentation',`A student hears the word “${pick(r,['ship','map','fish','sun'])}” and says each sound separately. Which skill is the student demonstrating?`,['Phoneme segmentation','Letter naming','Sight-word recognition','Sentence fluency'],0,'Breaking a spoken word into its individual phonemes is phoneme segmentation.'],
        ['onset and rime',`In the one-syllable word “${pick(r,['cat','shop','light','green'])},” which description best identifies onset and rime?`,['The onset is the sound(s) before the vowel; the rime begins with the vowel and includes what follows.','The onset is the final sound only; the rime is the first sound only.','Onset and rime are printed punctuation marks.','Every syllable has two separate vowels called onset and rime.'],0,'In a syllable, the onset is the consonant sound(s) before the vowel; the rime contains the vowel and following sounds.']
      ]; const z=pick(r,sets); base=q({subtest:'5002',domain,topic,skill:z[0]},z[1],z[2],z[3],z[4]);
    } else if(topic==='phonics-word-analysis'){
      const sets=[
        ['syllable type',`Which word begins with an open syllable?`,shuffle(r,['robot','basket','rabbit','napkin']),0,'An open syllable ends in a vowel sound, as in “ro-” in robot.'],
        ['morphology',`A student uses the prefix “un-” and the base word “happy” to interpret “unhappy.” Which word-analysis strategy is this?`,['Using morphology','Phoneme deletion','Prosody practice','Alphabetizing'],0,'Prefixes, roots, bases, and suffixes are meaningful word parts studied through morphology.'],
        ['decoding',`Which word is most directly decodable using a common consonant-vowel-consonant pattern?`,['map','said','one','was'],0,'“Map” follows regular letter-sound correspondences for a simple CVC pattern; the others are high-frequency words with irregular features.'],
        ['CVe',`Which word most clearly demonstrates a consonant-vowel-consonant-silent-e pattern?`,['hope','hop','boat','coin'],0,'“Hope” follows the CVCe pattern in which final silent e is associated with a long vowel sound.']
      ]; const z=pick(r,sets); base=q({subtest:'5002',domain,topic,skill:z[0]},z[1],z[2],z[3],z[4]);
    } else if(topic==='fluency'){
      const issue=pick(r,[['reads 95% of words correctly but pauses after nearly every word','rate/automaticity'],['reads quickly but substitutes several words','accuracy'],['reads accurately and smoothly but with no phrasing or expression','prosody']]);
      const correct=issue[1]==='accuracy'?'Accuracy':issue[1]==='prosody'?'Prosody':'Rate/automaticity';
      base=q({subtest:'5002',domain,topic,skill:'fluency components'},`A student ${issue[0]}. Which fluency component most needs attention?`,[correct,...['Accuracy','Prosody','Rate/automaticity'].filter(x=>x!==correct),'Phonemic awareness'].slice(0,4),0,`Fluency includes accuracy, appropriate rate/automaticity, and prosody. The described behavior points most directly to ${correct.toLowerCase()}.`);
    } else if(topic==='writing-types'){
      const sets=[
        ['argument',`Which assignment most clearly calls for opinion/argument writing?`,['Choose the best school-lunch change and support your claim with reasons and evidence.','Explain how a seed becomes a plant.','Write a story about getting lost in a museum.','List the steps for washing a paintbrush.'],0,'Argument writing makes a claim and supports it with reasons and evidence.'],
        ['informative',`Which purpose is primarily informative/explanatory?`,['Explain why eclipses occur using accurate facts and diagrams.','Convince readers to adopt a class pet.','Tell a fictional story about an astronaut.','Write only dialogue between two characters.'],0,'Informative writing explains a topic using accurate information and appropriate organization.'],
        ['narrative',`Which feature is most central to narrative writing?`,['A sequence of events involving characters or experiences','A claim supported only by cited evidence','A neutral definition list with no sequence','A bibliography as the main text'],0,'Narratives develop experiences or events, often using characters, setting, sequence, description, and dialogue.']
      ]; const z=pick(r,sets); base=q({subtest:'5002',domain,topic,skill:z[0]},z[1],z[2],z[3],z[4]);
    } else if(topic==='writing-process'){
      const sets=[
        [`A draft contains good evidence, but the paragraphs are in an illogical order. What should the writer do first?`,['Revise the organization.','Proofread spelling only.','Publish immediately.','Change the font.'],0,'Moving or restructuring ideas is revision because it changes organization and meaning.'],
        [`A writer notices repeated comma errors after the ideas and organization are already strong. What is the best next step?`,['Edit for conventions.','Replace the topic entirely.','Add unrelated evidence.','Delete the conclusion automatically.'],0,'Editing targets grammar, usage, mechanics, spelling, and other conventions after larger content decisions are in place.'],
        [`Which change is a revision rather than an edit?`,['Adding evidence to clarify an underdeveloped reason','Correcting a misspelled word','Fixing a missing period','Changing a lowercase letter to a capital'],0,'Adding evidence changes development and meaning, so it is revision.']
      ]; const z=pick(r,sets); base=q({subtest:'5002',domain,topic,skill:'revision and editing'},z[0],z[1],z[2],z[3]);
    } else if(topic==='grammar-usage'){
      const singular=pick(r,[['Each of the players','is'],['Neither of the answers','is'],['The basket of apples','is'],['One of the students','has']]);
      const verb=singular[1]; const wrong=verb==='is'?'are':'have';
      base=q({subtest:'5002',domain,topic,skill:'subject-verb agreement'},`Which sentence uses correct subject-verb agreement?`,[`${singular[0]} ${verb} ready.`,`${singular[0]} ${wrong} ready.`,`The students in the group is ready.`,`The list of names are on the desk.`],0,`Agreement is controlled by the grammatical subject, not a nearby plural noun. “${singular[0]}” takes “${verb}.”`);
    } else if(topic==='research'){
      const task=pick(r,['current state population','average annual rainfall for a city','official election turnout totals','historical text of a federal law']);
      base=q({subtest:'5002',domain,topic,skill:'source credibility'},`A student needs reliable information about ${task}. Which source is generally strongest?`,['A relevant recent government or primary-source publication','An anonymous undated blog post','An advertisement with no cited evidence','A social-media comment that gives no source'],0,'For factual research, prefer sources with relevant expertise, transparent evidence, appropriate currency, and a clear purpose. Government or primary-source publications are often strong for official data and texts.');
    } else if(topic==='speaking-listening'){
      const sets=[
        ['active listening',`Which behavior best demonstrates active listening?`,['Paraphrasing a speaker’s idea before responding','Waiting only for a chance to change the subject','Repeating a prepared comment regardless of what was said','Interrupting to speak more loudly'],0,'Paraphrasing accurately shows the listener processed the speaker’s idea.'],
        ['presentation',`Which change would most improve an oral presentation that is accurate but difficult to follow?`,['Use a clear structure and signal transitions between ideas.','Speak as quickly as possible.','Avoid eye contact and visual organization.','Add unrelated details to make it longer.'],0,'Clear organization and transitions help an audience follow the speaker’s reasoning.'],
        ['discussion norms',`During a collaborative discussion, which response best builds on another student’s idea?`,['“I agree with your point about evidence, and this example adds another reason…”','“I already decided my answer before you spoke.”','“Your idea does not matter because mine is longer.”','“I will repeat my original sentence without responding.”'],0,'Effective discussion responds directly to others and extends, questions, or connects ideas with reasons and evidence.']
      ]; const z=pick(r,sets); base=q({subtest:'5002',domain,topic,skill:z[0]},z[1],z[2],z[3],z[4]);
    } else {
      const candidates=conceptBanks['5002'].filter(x=>x[1]===topic); const x=pick(r,candidates.length?candidates:conceptBanks['5002']);
      base=q({subtest:'5002',domain:x[0],topic:x[1],skill:x[2]},x[3],x[4],x[5],x[6],x[7]||[]);
    }
    return base;
  }

  function curatedGenerator(subtest,seed,domain,topic){
    const r=rng(seed*1877+topic.length*71); const bank=conceptBanks[subtest].filter(x=>x[0]===domain && x[1]===topic); const x=pick(r,bank.length?bank:conceptBanks[subtest]);
    let stem=x[3];
    const intros=['','Consider the following question. ','Which response is best? ']; stem=pick(r,intros)+stem;
    return q({subtest,domain:x[0],topic:x[1],skill:x[2],difficulty:pick(r,['easy','medium','medium','hard'])},stem,x[4],x[5],x[6],x[7]||[]);
  }

  function generateOne(subtest, domain, topic, seed, serial=0){
    let base;
    if(subtest==='5003') base=mathGenerator(seed+serial*17,domain,topic);
    else if(subtest==='5002') base=rlaGenerator(seed+serial*19,domain,topic);
    else base=curatedGenerator(subtest,seed+serial*23,domain,topic);
    return finalize(base,seed,serial);
  }

  function weightedDomain(r, subtest){
    const ds=B.config.subtests[subtest].domains; const x=r(); let acc=0; for(const d of ds){acc+=d.weight;if(x<=acc)return d.id;} return ds[ds.length-1].id;
  }
  function topicsFor(subtest,domain){return B.topics[subtest].filter(t=>t.domain===domain);}
  function session(subtest,count,opts={}){
    const seed=opts.seed ?? (Date.now()%1000000000); const r=rng(seed); const recent=new Set(opts.recentFingerprints||[]); const weakness=opts.weakness||{}; const out=[]; const used=new Set(); let guard=0;
    while(out.length<count && guard++<count*80){
      let st=subtest;
      if(st==='MIXED') st=pick(r,['5002','5003','5004','5005']);
      let domain;
      if(opts.topic){ domain=B.topics[st].find(t=>t.id===opts.topic)?.domain; }
      if(!domain && opts.smart && Object.keys(weakness).length && r()<0.60){
        const weak=Object.entries(weakness).filter(([k,v])=>k.startsWith(st+':')).sort((a,b)=>a[1]-b[1]); if(weak.length) domain=weak[Math.floor(r()*Math.min(3,weak.length))][0].split(':')[1];
      }
      domain=domain||weightedDomain(r,st);
      const ts=topicsFor(st,domain); let topic=opts.topic||pick(r,ts).id;
      const item=generateOne(st,domain,topic,seed+guard*13,out.length);
      if(used.has(item.id)||recent.has(item.fingerprint)) continue;
      used.add(item.id); out.push(item);
    }
    return out;
  }

  window.PRAXIS_QUESTIONS={generateOne,session,readingPassages,conceptBanks};
})();
